### ISSUE TITLE
Chartkick is not defined

### ISSUE THREAD

**Issue by elsom25** [ankane/chartkick#1]
I have ChartKick referenced as outlined in the docs:

```
- content_for :head do
  = javascript_include_tag '//www.google.com/jsapi', 'chartkick'
```

(even referencing in head instead of at bottom of body!) and `chartkick is not defined` is being thrown. In the inspector, on line 355 of chartkick.js:

```
Uncaught TypeError: Cannot read property 'innerText' of undefined 
```

Any ideas?

**Comment by mk-nyein** [comment]
We have to change config.serve_static_files = true in production.rb.
