### ISSUE TITLE
No options from chartkick.json in Highcharts

### ISSUE THREAD

**Issue by omcdr** [ankane/chartkick#102]
Scenario:
Based on http://www.highcharts.com/demo/spline-symbols code.
1. In demo example in charts.html comment Google Chart and ucomment Highcharts:
2. chartkick.json file content:
   
   <pre>
   [
   {
       "id": "temperature",
       "title": { "text": 'Monthly Average Temperature'},      
       "yAxis": {"title": { "text": 'Temperature °C'}}        
   }
   
   {
       u'name': u'Tokyo',  
       "marker": {"symbol": 'square'}
   }
   ]       
   </pre>

Observed error: Charts are visible, but without titles.

BTW, how to set options only for specific dataset like Tokyo and symbol square ?

**Comment by ankane** [comment]
Cleaning up issues
