### ISSUE TITLE
formatting tooltips with Highcharts.dateFormat

### ISSUE THREAD

**Issue by pelcasandra** [ankane/chartkick#104]
I'm having difficulties when try to use `Highcharts.dateFormat` on `tooltip.formatter` using ruby because part of the code is javascript.

http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/stock/tooltip/formatter/

How would be possible to pass the js `Highcharts.dateFormat` call to the chart?

**Comment by ankane** [comment]
Cleaning up stale issues. Hope you're doing well @pelcasandra
