### ISSUE TITLE
Add support for trendlines

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick#109]

**Comment by jandillmann** [comment]
+1

**Comment by jeremystarcher** [comment]
+1

**Comment by jayzalowitz** [comment]
+1

**Comment by ajkost** [comment]
+1

**Comment by pruzicka** [comment]
+1

**Comment by Maikell84** [comment]
+1

**Comment by craigbrott** [comment]
+1

**Comment by jodydawkins** [comment]
+1

**Comment by aaronsama** [comment]
+1

BTW, trendlines already work for me when plotting a `scatter_chart` and using Google as provider if I pass

```
library: {
    trendlines: { 0 => { /* trendline options */ } }
}
```

However, I have been unable to make them work with line charts or column charts even though they are supported by the provider.

**Comment by jmccartie** [comment]
FYI: This seems to work now using @aaronsama 's code above:

![image](https://dl.dropboxusercontent.com/s/cpuh1dqo4u5rq74/Screenshot%202018-03-13%2014.40.04.png)

**Comment by ankane** [comment]
Thanks everyone for all of the feedback.

It looks like it's possible for Google Charts with the `library` option (thanks @aaronsama!) and for Chart.js with the [chartjs-plugin-trendline](https://github.com/Makanz/chartjs-plugin-trendline).

I still think it's a neat feature for Chartkick but likely not trivial to implement and maintain, so don't plan to add 1st class support for it.
