### ISSUE TITLE
Support for Highstocks?

### ISSUE THREAD

**Issue by jarrrosh** [ankane/chartkick#11]
Can this work with Highstocks? The time range feature would fit nicely with groupdate. :)

**Comment by StepanKuzmin** [comment]
+1

**Comment by itschn** [comment]
1+

**Comment by tothestar** [comment]
+1

**Comment by jmosmap** [comment]
+1

**Comment by hspazio** [comment]
+1

**Comment by gavinbelson** [comment]
+1

**Comment by ankane** [comment]
For those following along, I don't plan to support additional chart types at this time. Chartkick.js has experimental support for custom adapters, so someone could try to implement this chart type as a separate gem. https://github.com/ankane/chartkick.js#custom-adapters
