### ISSUE TITLE
Timeline doesn't support Advanced Timeline configuration

### ISSUE THREAD

**Issue by auzroz** [ankane/chartkick#113]
Specifically a fourth data column to allow for [putting bars on one row](https://developers.google.com/chart/interactive/docs/gallery/timeline#BarsOneRow).

**Comment by ehannes** [comment]
If someone would like to implement a fourth data column (and the `groupByRowLabel` option to support both bars in one line and bars in two lines with labels on them), how would one proceed?

I tried the naive solution to just add the following to the `renderTimeline` function:

```
var data = new google.visualization.DataTable();
data.addColumn({type: "string", id: "Name"});
data.addColumn({type: "string", id: "Label"});
data.addColumn({type: "date", id: "Start"});
data.addColumn({type: "date", id: "End"});
data.addRows(chart.data);
```

but when I check the `chart` variable, I see that the second column in `rawData` has `InvalidDate` as value. I got stuck searching for where the data is parsed...

How much work do you think is needed to support labels for Timechart @ankane?

**Comment by ehannes** [comment]
I actually got it to work if I placed the data in a fourth column in the Ruby code, like this:

``` ruby
<%= timeline [
    ["Week 49", "2016-12-05", "2016-12-12", "Label one"],
    ["Room 0", "2016-12-05 10:00", "2016-12-05 11:00", "Label two"],                           
    ["Room 1", "2016-12-06", "2016-12-16", "Label three"],                                   
    ["Room 2", "2016-12-05", "2016-12-05", "Label four"]
  ],
  library: { timeline: { showRowLabels: true } } %>
```

and then just switching column 2 and 4 in `renderTimeline` (since Google assumes the label is in column 2 and not 4 as in the example). Since this small example works, I guess it is not huge amount of work to implement this feature. I would gladly help creating such a pull request with a little help and guidelines :)

![screenshot from 2016-12-08 14-33-53](https://cloud.githubusercontent.com/assets/5365246/21012009/41f0c158-bd54-11e6-947b-5f7d94d37aa3.png)

**Comment by dnorthrupva** [comment]
@ehannes Late reply, but do you know how you got it to work? It rejects mine every time claiming:
`Uncaught (in promise) Error: Row given with size different than 3 (the number of columns in the table).`

**Comment by ehannes** [comment]
@dnorthrupva I cannot say I remember exactly how I implemented it, but I have it running in production. If you are interested, we could have a little chat about it :)

**Comment by dnorthrupva** [comment]
@ehannes  Would love too. Still struggling to get this to work on me end. Customization/advanced options within the wrapper seem to be issues.

**Comment by ehannes** [comment]
If anyone else is interested, here is my ugly but working implementation: https://github.com/ehannes/chartkick/commit/fab5aef6868a33f8ef35eb20e1278819dfb97191

I would gladly improve the code and open a PR if someone wants to help me out :)

**Comment by ankane** [comment]
For those following along, at the moment, there are no plans to add support more columns to timeline charts. I'd recommend using Google Charts directly if you need this.
