### ISSUE TITLE
Language definition overrides Chartkick object

### ISSUE THREAD

**Issue by ramongr** [ankane/chartkick#118]
<script>
  var Chartkick = {"language": "pt"};
</script>

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

**Comment by irenenirgendwo** [comment]
I think I have the same problem. I included 

     <script>
        var Chartkick = {"language": "de"};
     </script>
     <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
in the head part of my application-Layout.

But when I use chartkick, the shown language has not changed and is still english.

**Comment by CUnknown** [comment]
I have the same issue
