### ISSUE TITLE
Not all dots connect in multiple series line chart

### ISSUE THREAD

**Issue by terenceleejx** [ankane/chartkick#137]
I'm testing Chartkick and I notice there's an issue with a multiple series line chart (see screenshot). A dot in one of the series isn't connecting.  But when I set the last data points in both series to the same date, all the dots join up. 

Not sure if this is a bug or I'm doing something wrong.
![screenshot 2014-10-10 23 37 54](https://cloud.githubusercontent.com/assets/3685593/4594865/7f5cb856-5093-11e4-926d-4f4d39be64f7.png)

**Comment by TomasBarry** [comment]
Hey @ankane, we have run into this issue as well.

Is there any intention to solve it or is it not considered a bug?

**Comment by ankane** [comment]
As far as I can tell, this is a limitation of Google Charts. Chart.js has a `spanGaps` option, but not sure I like it better than the gaps.

**Comment by acrogenesis** [comment]
Found a solution to this here: https://stackoverflow.com/questions/18037925/google-chart-two-date-series-on-the-same-chart
It joins the two date series on the same chart, I'm just not entirely sure how to implement this with chartkick. Any idea @ankane?
