### ISSUE TITLE
Setting GeoChart region to "US" ignored

### ISSUE THREAD

**Issue by Chris-VorData** [ankane/chartkick#140]
Looking through the Chartkick and Google Charts code it seems I should be able to specify a region in the options hash to have the GeoChart just draw the US and its states, but it doesn't seem to work.  I'm doing it like this:

<%= geo_chart Scan.group(:state).count, { region: 'US', resolution: 'provinces' } %>

Is this the right way to display just a geochart of the US?

**Comment by ankane** [comment]
Cleaning up issues

**Comment by hafezbusra** [comment]
hi can i know what format to call data from 'state'?
