### ISSUE TITLE
Multiple series rendered differently in Chrome/Safari and Firefox

### ISSUE THREAD

**Issue by NiklasGronblom** [ankane/chartkick#141]
The following data series are rendered correctly (IMHO) using Google Charts  in Chrome and Safari , but Firefox produces a chart with the wrong order on the horizontal axis.

```
[{:name=>"PhD theses",
  :data=>
   {1978=>1,
    1996=>1,
    1998=>1,
    1999=>3,
    2000=>3,
    2001=>1,
    2002=>1,
    2003=>1,
    2004=>4,
    2005=>4,
    2006=>6,
    2007=>6,
    2008=>3,
    2009=>5,
    2010=>3,
    2011=>5,
    2012=>4,
    2013=>7,
    2014=>10}},
 {:name=>"Masters theses",
  :data=>
   {1982=>1,
    1983=>2,
    1984=>6,
    1985=>5,
    1986=>4,
    1987=>2,
    1988=>11,
    1989=>14,
    1990=>18,
    1991=>8,
    1992=>8,
    1993=>12,
    1994=>4,
    1995=>7,
    1996=>12,
    1997=>6,
    1998=>8,
    1999=>7,
    2000=>12,
    2001=>20,
    2002=>18,
    2003=>23,
    2004=>39,
    2005=>36,
    2006=>46,
    2007=>37,
    2008=>59,
    2009=>36,
    2010=>30,
    2011=>22,
    2012=>33,
    2013=>26,
    2014=>12}}]
```
### Chrome

![screenshot 2014-10-29 19 02 13](https://cloud.githubusercontent.com/assets/2726652/4830523/6130e44c-5f8e-11e4-8305-ae3dcb631a18.png)
### Safari

![screenshot 2014-10-29 19 08 54](https://cloud.githubusercontent.com/assets/2726652/4830535/75f032b6-5f8e-11e4-9ab4-a8eb180750aa.png)
### Firefox

![screenshot 2014-10-29 19 02 38](https://cloud.githubusercontent.com/assets/2726652/4830529/6a8a6608-5f8e-11e4-8c38-fb5b3b9f01f3.png)

Is this a browser issue, Google Charts issue, or a chartkick issue? I would want Firefox to produce the same chart as Chrome and Safari.

**Comment by jaimerson** [comment]
Any news on this?

**Comment by rjrobinson** [comment]
Also getting this error

**Comment by ankane** [comment]
With the latest version of Chartkick, it looks like they all render the same (as Firefox does in your example). This is due to lack of support for a numeric column type. I added this as a todo in https://github.com/ankane/chartkick.js/issues/78.

**Comment by ankane** [comment]
Added in https://github.com/ankane/chartkick.js/issues/78
