### ISSUE TITLE
Google Charts creating material bar charts

### ISSUE THREAD

**Issue by ryanoff** [ankane/chartkick#143]
How can we create material design bar charts?

In the Google Charts reference, they have included a section about updating the design of charts to Material Design. 

See the section on Material Design Charts
https://google-developers.appspot.com/chart/interactive/docs/gallery/columnchart

> Creating a Material Column Chart is similar to creating what we'll now call a "Classic" Column Chart. You load the Google Visualization API (although with the 'bar' package instead of the 'corechart' package), define your datatable, and then create an object (but of class google.charts.Bar instead of google.visualization.ColumnChart).

**Comment by chr1s1** [comment]
+1 it would be really cool to the the material charts with chartkick

**Comment by cmalpeli** [comment]
+1

**Comment by jordanful** [comment]
+1 !

**Comment by stevenspiel** [comment]
+1

**Comment by bjgaynor** [comment]
+1

**Comment by lucianoiscool** [comment]
+1

**Comment by tonyvince** [comment]
+1

**Comment by ankane** [comment]
Unfortunately, I don't think I have the bandwidth to officially support another charting library right now. Even if it's somewhat similar to an existing one, will still need to test changes against it.

I'm sure it's not the outcome this thread wanted, but I appreciate all of the feedback. Someone is welcome to maintain a fork of Chartkick.js that supports it (like @logicalgroove started). Users should be able to use the official Chartkick gem and simply drop the forked JS file into their app (or install it via webpack).
