### ISSUE TITLE
Currency formatting in pie charts

### ISSUE THREAD

**Issue by julescopeland** [ankane/chartkick#145]
Hi,

Googling is getting me nowhere with this... Is there a straight forward method for getting a pie chart to display £23,456 instead of 23456 ? 

I've got the values to display, rather than the percentages, but as most of the numbers are over 1,000 they look odd without the comma separators, and the currency symbol would help too.

Thanks.

**Comment by rafanasil** [comment]
I have the exact same problem.

**Comment by pabloalr** [comment]
+1

**Comment by l0c0luke** [comment]
+1

**Comment by ankane** [comment]
Good to know there's interest in this feature.  Pull requests welcome.

**Comment by vhilly** [comment]
any update?

**Comment by vhilly** [comment]
how do i make it comma separted for thousands

**Comment by aaronpark** [comment]
I would like this option as well

**Comment by ankane** [comment]
This was added in 2.3.
