### ISSUE TITLE
Installation issues for Rails related to Sinatra

### ISSUE THREAD

**Issue by isc** [ankane/chartkick#148]
Hi,

I've had to explicitly require Sinatra (it was already present in the Gemfile.lock as a dependency of Resque) in the Gemfile of my Rails application to be able to use Chartkick.
Without the explicit require, I couldn't boot the app because of the following error:
```
/Users/ivan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/chartkick-1.3.2/lib/chartkick/sinatra.rb:2:in `<class:Base>': undefined method `helpers' for Sinatra::Base:Class (NoMethodError)
	from /Users/ivan/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/chartkick-1.3.2/lib/chartkick/sinatra.rb:1:in `<top (required)>'
```

**Comment by ankane** [comment]
Hey Ivan, thanks for reporting.  This should be fixed with the commit above.
