### ISSUE TITLE
Mulitple colors in bar chart

### ISSUE THREAD

**Issue by jdubhub** [ankane/chartkick#149]
Perhaps this is more a support question rather than a bug, I'm trying to create a multicoloured colum_chart. I can't seem to set different colours for each series. Can you please advise where the issue is. Thankyou

```
  `  <%= column_chart  [
    ["Deferred", @repair.deferred_count],
    ["Monitored", @repair.monitor_count],
    ["Important", @repair.important_count],
    ["Urgent", @repair.urgent_count],
  ],
    colors: ["#00639c", "blue","yellow", "red"],
    :height => "210px", 
    :library => {
      :backgroundColor => "#002f4c",
      :chartArea => {:width =>'100%', :height => '100%'},
      :legend => "none",
      :vAxis => { :gridlines => {:color => "#002f4c"}, :baselineColor =>  "002f4c"}
    } %> `
```

**Comment by buren** [comment]
@adelivuk, @jdubhub
I've created bar/column charts with different colours with this code:
```ruby
# charts/gender.html.erb
column_chart(charts_gender_path)
```
And `charts_gender_path` answers with this JSON:
```JSON
[{"name":"Male","data":{"Gender":38}},{"name":"Female","data":{"Gender":59}}]
```

**Comment by adelivuk** [comment]
I can confirm that @buren JSON structure will use different color for the ```column_cart```.

Just a note, you have to first speficy the colors in your ```config/initializers/chartkick.rb```:

```
Chartkick.options = {
  colors: ["#color1", "#color2", "#color3", "#color4", "#color5"]
}
```

**Comment by leonardk1** [comment]
@buren It has worked for me, and yes you have to specify the colors as @adelivuk has pointed out

**Comment by leonardk1** [comment]
however I had to edit this
`[{"name":"Male","data":{"Gender":38}},{"name":"Female","data":{"Gender":59}}]` to 
`[{name: "Male", data: {"Gender": 38}}, {name: "Female", data: {"Gender": 59 } }]`

to use the new supported hash structure

**Comment by ankane** [comment]
Sounds like this was solved. For future readers, you can use the multiple series format for different colors for the bars.
