### ISSUE TITLE
chartkick.js isn't precompiled

### ISSUE THREAD

**Issue by futura** [ankane/chartkick#150]
The installation instructions say: "chartkick.js runs as a Rails engine - no need to install it."

But out of the box on Rails 3.2, I got:
ActionView::Template::Error (chartkick.js isn't precompiled)

Gemfile:
gem 'rails', '~> 3.2'
gem 'chartkick'
...

View:
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>

I finally fixed it by manually adding chartkick.js to my app/assets/javascripts directory and to my precompile paths ...

config/environments/production.rb:
config.assets.precompile += %w( calendar/_.js local/_.js jquery_calendar/*.css chartkick.js )

Then rake:assets precompile on the server.

Is this how it's supposed to work?

**Comment by Nmuta** [comment]
I actually have a similar problem perhaps ? I put chartkick in my Gemfile, and I did a bundle install, and then   I'm doing this in a view:   ( shouldn't this work? ) 

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %
<%= pie_chart({"Football" => 10, "Basketball" => 5}) %>


Instead, I get a no method error... it's clearly not loading chartkick.  Here is the error:
undefined method `pie_chart' for #<#<Class:0x007fb90f1a2848>:0x007fb90f515200>

So I included the online source instead :
<%= javascript_include_tag "https://raw.githubusercontent.com/ankane/chartkick/master/app/assets/javascripts/chartkick.js" %>

And I still get the same issue. 

This is a widely used gem , so clearly I'm doing something wrong.  What's my error ?
