### ISSUE TITLE
no lines in multiple lines chart

### ISSUE THREAD

**Issue by mkssion** [ankane/chartkick#152]
I don't know if this is already known, but if you draw multiple lines in a line chart, where the data hasn't got matching x-axis-values then the lines won't connect.

Is there any workaround?

It also got discussed here: http://stackoverflow.com/questions/25799877/rails-chartkick-lines-not-drawing-in-multi-series-line-chart

**Comment by ankane** [comment]
Yeah, this is how the underlying charting library behaves. If someone knows of a solution, please let me know or submit a PR.
