### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Nmuta** [ankane/chartkick#154]
I put chartkick in my Gemfile, and I did a bundle install, and then I'm doing this in a view: ( shouldn't this work? )

<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= pie_chart({"Football" => 10, "Basketball" => 5}) %>

Instead, I get a no method error... it's clearly not loading chartkick. Here is the error:
undefined method `pie_chart' for #<#Class:0x007fb90f1a2848:0x007fb90f515200>

So I included the online source instead :
<%= javascript_include_tag "https://raw.githubusercontent.com/ankane/chartkick/master/app/assets/javascripts/chartkick.js" %>

And I still get the same issue.

This is a widely used gem , so clearly I'm doing something wrong. What's my error ?
(incidentally, when I call the Chartkick object in irb, I can access the object.  However, when I try to do the initializer ( config/initializers/chartkick.rb ) ,  it chokes when I try to run the server, saying that Chartkick is an uninitialized constant.  So something is wrong where Charkick is not being loaded at the right time? ) 

BTW I'm using Rails 3.2

**Comment by Nmuta** [comment]
Same problem when I take the js includes out of the view and put the following line in application.js:

 <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

**Comment by Nmuta** [comment]
![image](https://cloud.githubusercontent.com/assets/924079/5600198/77f7ca74-9292-11e4-8bea-df19afb787a9.png)

**Comment by ankane** [comment]
Hey @Nmuta, did you restart your Rails server after installing?  Also, be sure `chartkick` comes after `rails` in your Gemfile.

**Comment by Nmuta** [comment]
@ankane , yes, I restarted the server, and just now, trying it again, I restarted the server again.  I seem to have everything set up correctly...... has anything changed recently with this project ? I've never tried it before but I wonder if anything has changed recently that would make it NOT work according to the instructions given.

**Comment by ankane** [comment]
No, I don't think so

**Comment by Nmuta** [comment]
I really appreciate your attentiveness on this issue.  I tried combing the
forums here and I just can't find anything that I'm doing wrong.  I really
want this to work and I'm excited about getting these graphs.  Is there
anything else that I should be checking for ? I'm sure that my error is
something small and stupid.

**Comment by Nmuta** [comment]
Ah yes.... lo and behold, it was something very small, and very stupid. It was in fact the ordering of the gemfile.  Thank you.   Problem solved.

**Comment by ankane** [comment]
Awesome, glad it's working!

**Comment by Nmuta** [comment]
Yes... now the fun begins. This is an awesome charting resource for Rails.....

**Comment by barmmie** [comment]
@Nmuta 
Same issue
Sorry to bug. but what was wrong with the ordering of your gemfile.
