### ISSUE TITLE
How to add a name to a chart, x- and y-axis?

### ISSUE THREAD

**Issue by rdudacz** [ankane/chartkick#155]
Hello,

I am fighting with adding labels from the subject to the graph. I've tried different ways to add these labels to the graph, but never been successful.

Here's how I am trying to achieve that:
`area_chart [
      {name: "Tooltip text", data: @users.group_by_day(:created_at), :id => "stats", library: {hAxis: {title: "X-label"}, vAxis: {title: "Y-label"}, title: {text: "Graph title label"}}}
    ]`

I am attaching an image with red text that shows what I am trying to achieve, but still looking for the proper code to do that.

![screen shot 2015-01-04 at 20 49 26](https://cloud.githubusercontent.com/assets/3080919/5607283/81f03920-9455-11e4-8696-6f1d2458202f.jpg)

How to add the red labels to the graph?

Thank you.

**Comment by rdudacz** [comment]
Fixed:

`area_chart [ {name: "Tooltip text", data: @users.group_by_day(:created_at)}], :id => "stats", :library => {hAxis: {title: "X-label"}, vAxis: {title: "Y-label"}, title: "Graph title label"} `

**Comment by Iqlaas** [comment]
Helped me. Thanks.
