### ISSUE TITLE
generate image

### ISSUE THREAD

**Issue by reginato** [ankane/chartkick#156]
hi guys

Is it possible create chart image without render a chart on the browser? 
Like a background job, i need attach this chart on report.

**Comment by ankane** [comment]
I haven't tried this, but maybe someone else who's used this gem has.

**Comment by MaicolBen** [comment]
+1 

Duplicated with https://github.com/ankane/chartkick/issues/29

**Comment by ankane** [comment]
Cleaning up issues. If someone puts together instructions on how to do this, please report back!
