### ISSUE TITLE
Text rotation labels - google charts

### ISSUE THREAD

**Issue by cmrp** [ankane/chartkick#158]
Hi, first of all thanks for charkickt is very usefull for me.

I would like to ask for some help because I have a problem with labels, in the photo the labels in x-axis don't rotate like in the other photo and I don't understand why?.

![image](https://cloud.githubusercontent.com/assets/726550/5762078/79d2b378-9cd7-11e4-9622-a212c4cb8cb3.png)

![image](https://cloud.githubusercontent.com/assets/726550/5762353/6e274f8c-9cd9-11e4-830f-34f24a32946c.png)

 I put in my file this line
 <%= column chart @measures , id: "graph-chart" %> 
I don't know if it necessary some additional parameter. I hope that you can help me to understand the problem. 

Thanks so much

**Comment by nikhilthombare** [comment]
I think this link is help you http://stackoverflow.com/questions/17750007/google-charts-change-axis-title-orientation
