### ISSUE TITLE
Change chart after initial load?

### ISSUE THREAD

**Issue by karimmtarek** [ankane/chartkick#160]
I'm using chartkick with rails app, I was wondering if it's possible to update the chart after the initial load based on a form submit, like apply some kind of a filter to dates or something similar.

Is it possible?

**Comment by buren** [comment]
@karimmtarek you could do something like this to update against a remote url:
```
var dataSource = "<%= raw charts_some_path_path %>?" + formParams;
new Chartkick.LineChart('your-chart-id',  dataSource);
```
`dataSource` could also be a JavaScript Array which you could filter in JS in your on function:
```
var dataSource
```

**Comment by karimmtarek** [comment]
@buren thanks, I really appreciate it.

**Comment by buren** [comment]
@karimmtarek :+1:
