### ISSUE TITLE
Graphing Times

### ISSUE THREAD

**Issue by daveharris** [ankane/chartkick#161]
Hi,

I have a set of cycle race data - reduced to dates and times/duration which I am trying to graph to show the general trend year-over-year.

I store the number of number of seconds in the database which can easily be graphed - however displaying time in seconds is not very helpful. I want to be able to graph points with values in `hh:mm:ss` format, i.e. `3:52:10`. I use the awesome [ChronicDuration](https://github.com/hpoydar/chronic_duration) gem to convert and parse `hh:mm:ss` format into seconds and vice versa. Using this, the graphing library converted `3:52:10` into the number `3` - which is understandable but not very helpful!

As a workaround, I convert the number of seconds into decimal hours, so `3:52:10` gets turned into `3.87`hours. This works, but it looks a bit weird to have decimal hours, see below:

![graph](https://cloud.githubusercontent.com/assets/111275/5850275/41399a1a-a257-11e4-87ce-9270c345ec07.png)

I'm using the Google Chart API in the background, so I presume it's that that doesn't support graphing times? Does anyone know how I could get around this? I haven't tried using the Highcharts.js 'backend', as I was a little put off by their complex setup and licensing (even if it's free). 

Does anyone know how I can graph times in the format `hh:mm:ss`?

I got Chartkick up and running really quickly and it's super easy to use, nice work!!! Sorry to raise an issue for a question.

Dave

**Comment by glundgren** [comment]
I'm having the same problem, did you find a workaround?

**Comment by daveharris** [comment]
Hi,

Originally I went down the approach of setting the y-axis type to `datetime` and then formatted the results in what I thought it needed. Something similar to [this Stackoverflow thread](http://stackoverflow.com/questions/19591770/chartkick-y-axis-uncorrect-labeling).

I haven't yet but I know how to do it. I was at a Rails camp in Auckland, NZ over the weekend and thankfully someone else was doing the same thing. What you need to do is just set the y-axis `formatter` function, which converts pure seconds onto some format - which Highcharts then uses to create the correct axis. I'm pretty sure this only works with Highcharts and not the Google Charts API.

To do this, you need to set a formatter, which is described in #60. As that bug says, defining the `formatter` function needs to be in javascript, not in ruby as it can't be serialised to JSON.

I am going to work on it this weekend hopefully so when I've got it, I'll post the solution here (or maybe you could if?)

Dave

**Comment by glundgren** [comment]
hey dave, try this gem: https://github.com/airblade/chartjs-ror i was able to solve it very easily.

**Comment by abuisman** [comment]
@glundgren Thanks for the tip. I am not sure what I have to do though. Where did you put the above? (if you still remember)

**Comment by glundgren** [comment]
hey @abuisman, good question :) i took a look here and i added it on some .js, when i setted some stuff on Chart.js:

```Chart.defaults.global.responsive = true;
Chart.defaults.global.tooltipCornerRadius = 14;
Chart.defaults.global.tooltipCaretSize = 7;
Chart.defaults.global.tooltipXPadding = 10;
Chart.defaults.global.tooltipFillColor = '#484848';
Chart.defaults.global.animationEasing = "easeOutQuart";
Chart.defaults.global.scaleLabel = "<%= moment.utc(moment.duration(value *60*60* 1000).asMilliseconds()).format('HH[h]mm[m]') %>" ;
Chart.defaults.global.tooltipTemplate = "<%= moment.utc(moment.duration(value *60*60* 1000).asMilliseconds()).format('HH[h]mm[m]') %>" ;
Chart.defaults.global.tooltipXOffset = 100;

These tags <%= %> are not related to rails, it something that Chart.js used, i don't  know if it still works.

**Comment by abuisman** [comment]
Hi @glundgren thanks a lot for having a look!

The `<%= %>` got me confused. It doesn't seem like it is still a thing in the newer version. I can't really figure out how to do the same in the newer version though. But it will just be a matter of time before I get it fixed.

Thanks for having a look! :)

**Comment by daveharris** [comment]
Hi @glundgren,

Check out my [full working example](http://cycling.harris.org.nz/races/taupo-cycle-challenge). Rather than mucking around with chartjs-ror, I have switched to using straight ChartJS.

The flow of events is:
1. My [controller](https://github.com/daveharris/cycling.harris.org.nz/blob/master/app/controllers/races_controller.rb#L9) calls my [model](https://github.com/daveharris/cycling.harris.org.nz/blob/master/app/models/race.rb#L25) which produces the data in the correct format
1. My [view](https://github.com/daveharris/cycling.harris.org.nz/blob/master/app/views/races/show.html.erb#L3) defines a HTML `canvas` element with the data as HTML5 `data` attributes
1. Then the [javascript](https://github.com/daveharris/cycling.harris.org.nz/blob/master/app/assets/javascripts/race_chart.js) comes along and uses native ChartJS (i.e. `new Chart(element, options)` to produce the chart. The values are read directly off the `data` attributes, (i.e. `resultDurationCanvas.data('duration')`). This is where I convert the number of seconds to `hh:mm:ss` format for the labels

I realise it's quite complicated but it allows me do the heavy lifting in ruby while giving me full power over the presentation of the labels etc without having to dance around with `<%= %>` in my erb.

This is just one of many possibilities, but it may help you think about options.

Let me know if you need any help with anything else!

Dave

**Comment by abuisman** [comment]
@daveharris Thanks Dave!

I had found your answer here: https://github.com/chartjs/Chart.js/issues/2791

But for some reason your functions do not work when I set them on the global options, so I had to resort to passing the options to the Chart constructor. 

It works though! Thanks!
