### ISSUE TITLE
Changing language does not work

### ISSUE THREAD

**Issue by kreintjes** [ankane/chartkick#163]
Hi,

I am trying to change the language for the Google Charts library, but it is not working. I am following the instructions provideded here: https://github.com/ankane/chartkick#localization. Although, even when I put the language code **before** the inclusion of the JavaScript files, it still does not work.

I think my issue may be related to https://github.com/ankane/chartkick/issues/118

Any help with this would be appreciated.

Kevin

**Comment by voldenuit** [comment]
I have the same issue. Here is my code:

 ```
<script>
   var Chartkick = {"language": "it"};
</script>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<%= javascript_include_tag "application" %>
 ```

**Comment by ankane** [comment]
Cleaning up issues. The `language` setting seems to work fine, but let me know if you're still having issues. There's a new way to specify the language now (see readme for details).
