### ISSUE TITLE
change legend name when data given in single series

### ISSUE THREAD

**Issue by TanakaYutaro** [ankane/chartkick#165]
Is it possible change dafault legend name "Value", when data given in single series?

Following code, display "Value" on legend.

``` ruby
<%= area_chart @data,
    discrete: true,
    library: {
        legend: {position: "right"},
    }
%>
```

![2015-01-30 18 01 10](https://cloud.githubusercontent.com/assets/3489430/5973304/0475a930-a8aa-11e4-8053-e769a7d279d3.png)

**Comment by ankane** [comment]
Hey Yutaro, try this instead:

```erb
<%= area_chart [{name: "Not Value", data: @data}] %>
```

**Comment by TanakaYutaro** [comment]
@ankane thanks, it was suceeded!

But is it impossible change legend name when single chart, not multiple chart?

example, following code.
```ruby
<%= area_chart @data,
    discrete: true,
    library: {
        legend: {position: "right", name: "legend name"},
    }
%>
```

**Comment by ankane** [comment]
I don't think there's a way to do it with the `library` option.

**Comment by TanakaYutaro** [comment]
Ok, thanks a lot!
