### ISSUE TITLE
Question... charkick with 100 charts on a single page

### ISSUE THREAD

**Issue by abitdodgy** [ankane/chartkick#170]
I have a situation where a single page must load around 70 to 100 charts. That's a lot. I'm passing charkick a path so the graph loads remotely.

```
<%= line_chart chart_path %>
```

Even though I'm loading the charts remotely, that's a lot of requests. I'm thinking about loading some of them on demand. So the user clicks a UJS/Javascript link, and that loads the graph.

I'm wondering, has anyone had a similar requirement and how did they go about solving it?

Thanks.

**Comment by andrewkdesigns** [comment]
Doing something similar for loading partials with ajax (on click).

Maybe you can do something like this? (untested with chartkick)
```javascript
    $("#items_grid").html("<%= escape_javascript(line_chart chart_path) %>"); 
```

**Comment by ankane** [comment]
Cleaning up issues.
