### ISSUE TITLE
add event listener on horizontal axis label text for line chart

### ISSUE THREAD

**Issue by pbharadiya** [ankane/chartkick#172]
Hello,
I want to add event listener say 'onhover' event in labels of horizontal axis.
e.g in the below chart, I want to add 'onhover' event on 'Task 1' etc.
I tried a lot but couldn't find any solution.

Can anybody please help?

![chartkick-linechart](https://cloud.githubusercontent.com/assets/3007434/6511876/c28a9a60-c395-11e4-8c0d-000ff5b595f0.png)

P.S I am using this line to generate chart.

<code><%= line_chart data, {discrete: true, library: {
                            width: 650,
                            height:301,
                            vAxis: {
                              ticks: (1..7).to_a
                            }
                          }
                        } %></code>

**Comment by ankane** [comment]
Chartkick doesn't provide a way to add event listeners.
