### ISSUE TITLE
Interpolation in line graphs

### ISSUE THREAD

**Issue by celiamoreno** [ankane/chartkick#175]
I've a table with binaries datas, so I'd like to represent them in a linear graph with timestamps, but I I've an interpolation between values. 
![graph](https://cloud.githubusercontent.com/assets/11521885/6690479/17393e34-ccc1-11e4-9560-3fac05f34716.png)

I need to represent digital values like that:
![5vgraph](https://cloud.githubusercontent.com/assets/11521885/6690489/20d28e6e-ccc1-11e4-952a-375125dc240b.jpg)

Someone knows how could I do it? Thank you

**Comment by yifeiwu** [comment]
Couldn't you plot it in a column chart?

**Comment by auzroz** [comment]
Can you provide a sample of the data? Are there duplicate values you are dealing with?

**Comment by ankane** [comment]
Chartkick doesn't have a great way to represent digital values unfortunately.
