### ISSUE TITLE
Add support for Highcharts yAxis allowDecimals

### ISSUE THREAD

**Issue by dugjason** [ankane/chartkick#176]
http://api.highcharts.com/highcharts#yAxis.allowDecimals

I have charts which present decimals on the yAxis; in some cases this is great, however in some cases (like the example below) it does not make sense to list decimal values as I am measuring something discrete. For example, the number of tickets raised in an hour:

![screen shot 2015-03-18 at 11 34 37](https://cloud.githubusercontent.com/assets/273718/6707855/0cd59562-cd63-11e4-8aa3-7bcb3bf1eeb0.png)

Could we look at implementing support for the Highcharts allowDecimals option to turn off decimal values on the yAxis?

**Comment by ankane** [comment]
You can use the `library` option for any Highcharts options.
