### ISSUE TITLE
Line charts show wrong axis values 

### ISSUE THREAD

**Issue by ignazioc** [ankane/chartkick#178]
When a `line_chart` graph is used the X axis automatically try to display date/time instead of the real values.

This is the basic map 
````
@result_test = {"sample"=> 30, "sample2" => 42}
````
and this is the code for generating the graphs
````
<%= column_chart @result_test, library: {backgroundColor: "#eee", title: 'Sample Graph', vAxis: {title: "QT"}, hAxis: {title: 'Date'}} %>
<%= line_chart   @result_test, library: {backgroundColor: "#eee", title: 'Sample Graph', vAxis: {title: "QT"}, hAxis: {title: 'Date'}} %>
````

The result should be the same except for the design, but this is the result
![screenshot 2015-04-03 12 18 38](https://cloud.githubusercontent.com/assets/645715/6981027/971c84ac-d9fb-11e4-8230-6585fc474811.png)

**Comment by ankane** [comment]
@ignazioc Try `discrete: true` for the line chart.

**Comment by ignazioc** [comment]
:+1: 
This is the final code, as a reference
````
<%= line_chart @result_start_app, discrete: true, library: {backgroundColor: "#eee", curveType: 'function',title: 'Avvio Applicazione', vAxis: {title: "QT"}, hAxis: {title: 'Date'}} %>
````
