### ISSUE TITLE
Show original value rather percentage in PIE and line chart

### ISSUE THREAD

**Issue by kashifnaseer** [ankane/chartkick#180]
I've data like 
`{"Commercial"=>364,
 "Residential"=>463,
 "Hospitality"=>150,
 "Industrial"=>20,
 "Laboratory"=>1}`

when i add this in the pie chart, it displays the chart with percentage of each option, I wan to display the value rather percentage, How i can do this,

**Comment by irenenirgendwo** [comment]
You can use the library of google charts with
options = {"library" => {"pieSliceText" => "value", "tooltip" => {"text" => "value"}}}
pie_chart(data, options)

**Comment by ankane** [comment]
Cleaning up issues. Thanks for helping out @irenenirgendwo 👍
