### ISSUE TITLE
x-axis time not changing to days

### ISSUE THREAD

**Issue by razvanh** [ankane/chartkick#184]
I have 4 days worth of data on a chart but the labels never change to daily format.

![screen shot 2015-05-08 at 7 38 53 am](https://cloud.githubusercontent.com/assets/3977750/7536426/632c78c6-f555-11e4-91ae-57f4eafeb3a6.png)

I don't use group_by_day - the data set is an array with the value & created_at timestamp.

Any way of manually changing the way it labels the x axis?

**Comment by dugjason** [comment]
I believe I had a similar problem. I think I solved it by using discrete values:
```
<%= line_chart @results, height: "500px", discrete: true %>
```
This seems like a similar report to #191 and #91

**Comment by ankane** [comment]
@razvanh Not that I'm aware of. If you find a way with Google Charts, feel free to submit a PR.
