### ISSUE TITLE
None of the Chart sizing options work

### ISSUE THREAD

**Issue by Maverick494** [ankane/chartkick#185]
titlePosition - doesn't work, chartArea - doesn't work, changing just height: and width: just moves the chart around on the page adding white space.  Also, trying to add discrete and hAxis {minTextSpacing: '20'} does nothing either.

For some reason the count column chart I made is sized just fine, but it is the sum charts that are small and the above do not work.  I have not tried the above on the count table because I don't want it to mess up.

![chartkick issue](https://cloud.githubusercontent.com/assets/12422275/7612079/4f24c4fa-f93d-11e4-96d1-403ef5ca5807.PNG) 
This is a sum graph

![chartkick issue 2](https://cloud.githubusercontent.com/assets/12422275/7612106/8d92d376-f93d-11e4-8bfa-ef9b84d1eb50.PNG)
This is a sum graph

![normal chartkick](https://cloud.githubusercontent.com/assets/12422275/7612109/93ed762c-f93d-11e4-89dd-8ab22c3a77ec.PNG)
This is a count graph

**Comment by yifeiwu** [comment]
Not sure if we have the same issue, but I've seen something similar when I don't have proper container divs around my charts. Another thing that happens is the chart dimensions are pulled at loading time. So if you happen to be using bootstrap tabs/pills they can get messed up.

**Comment by ankane** [comment]
Hey @Maverick494, thanks for reporting. If this is still an issue, please paste the code to reproduce.
