### ISSUE TITLE
How to change the text 'Value' in Chartkick's geochart

### ISSUE THREAD

**Issue by bnussey** [ankane/chartkick#189]
I am rendering a geochart with the following:

    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

    <%= geo_chart Company.group(:country).count, colors: ["#33C1FF", "#008ED6"] %>

This works great, but the text used on the map to specify the count for each country is 'Value'.

I am using the Google Charts API to do this, and looking at their documentation, they are able to use 'Popularity' instead of 'Value' by doing this:

    var data = google.visualization.arrayToDataTable([
          ['Country', 'Popularity'],
          ['Germany', 200],
          ['United States', 300],
          ['Brazil', 400],
          ['Canada', 500],
          ['France', 600],
          ['RU', 700]
        ]);

I've tried to replicate this by adding it directly to geo_chart, and still 'Value' appeared. You can see my attempt below:

    <%= geo_chart [['Popularity'], ['Germany', 200], ['United States', 300], ['Brazil', 400], ['Canada', 500], ['France', 600], ['RU', 700]], colors: ["#33C1FF", "#008ED6"] %> 

Any ideas?

Thanks

**Comment by alanchavezgar** [comment]
https://github.com/ankane/chartkick/issues/46

**Comment by bnussey** [comment]
Hey @alanchavezgar thanks for that.. Do you know if that works for the geomap as well? Looks like it's for highcharts

**Comment by ankane** [comment]
This is now possible with the `label` option.

**Comment by juanroldan1989** [comment]
Hello @ankane is also possible to customize **Geo Charts** with the **label** option ? I can't find docs about it. Thanks for any advise here : )
