### ISSUE TITLE
group_by_month not showing correct results

### ISSUE THREAD

**Issue by ryanoff** [ankane/chartkick#191]
I'm not sure if this is an issue with Chartkick or group_by_month. 
The group_by_month function does not appear to working correctly. 

I have a daily set of data that I am using with Chartkick where I am plotting a chart with each point showing a summed month's worth of data.

The data is not 100% correct and is also not showing up in the correct month.

Here is the group_by_month code that is not working correctly.

    @Reservations.group_by_month(:date).order("month desc").sum(:move_ins)

This rails code does return the correct values, but doesn't play nice with Chartkick:

    @Reservations.select("DATE_TRUNC('month', date) AS month, sum(move_ins) AS move_ins_per_month").group('month')

**Comment by ryanoff** [comment]
I found a solution to this using group_by_month's format option and discrete: true as shown in this post: https://github.com/ankane/chartkick/issues/91

**Comment by ankane** [comment]
Yeah, not super intuitive.  Chartkick 2.0 will most likely detect discrete series.
