### ISSUE TITLE
Updating chart via ajax runs over other charts.

### ISSUE THREAD

**Issue by ozkar99** [ankane/chartkick#193]
Basically when you have an ujs handler like `update.js.erb` and you have something inside like:

``` Ruby
 $("#chart").html("<%= line_chart @data %>")
```

It will search for the div element with id: `chart-1` instead of creating a new one, since ajax would reset the `@chartkick_chart_id` counter in the `helper.rb` file.  (https://github.com/ankane/chartkick/blob/master/lib/chartkick/helper.rb#L39)

PR to fix this right here:  #192

P.S.:

Of course you can just pass the id of the element as an option in the options hash, but it took me so long to find out, that i had to go and read the code, so i suppose more people will have the same problem as me, this PR fixes it.

**Comment by abrahamks** [comment]
Hi @ozkar99, I also got the same problem like yours (can't create chart via ajax).
Do you mind to explain me where to put / how to use options hash to resolve the problem?

Thanks

**Comment by ozkar99** [comment]
@abrahamks, should be on any helper as the last argument (optional).

for example:
`column_chart [ {name: 'data 1', data: data_for_chart} ], {id: 'column_chart_x' }`

you can see how its implemented on this file:
https://github.com/ankane/chartkick/blob/master/lib/chartkick/helper.rb#L39

(and `id` specifically the line highlighted)

**Comment by abrahamks** [comment]
@ozkar99 I don't know if it's a different issue or not

I put this line of code on my .js.erb
```$('#segmentationResult').html('<%= line_chart @hashes_of_date_values, {id: "chart1"} %>');```

And it failed to render a graph. After I traced the console using firebug. It retuns the .js.erb like this
```$('#segmentationResult').html('<div id="chart1" style="height: 300px; text-align: center; color: #999
; line-height: 300px; font-size: 14px; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana,
 Arial, Helvetica, sans-serif;">Loading...</div><script type="text/javascript">
  new Chartkick.LineChart("chart1", [{"2015-08-04":3741,"2015-08-05":0,"2015-08-06":0,"2015-08-07":0
,"2015-08-01":2258,"2015-08-02":3346,"2015-08-03":1927}], {});
</script>
');```

I tried to copy the response and run it through firefox's console and it returned an error like this:

```SyntaxError: unterminated string literal	
...e', Verdana,
 Arial, Helvetica, sans-serif;">Loading...</div><script type="text/...
/* EXPR...: 14px; (line 2)```


It looks like there is a mistype in ```font-family``` part.

Have you encountered this error before?

**Comment by ozkar99** [comment]
wow, no not really, have you tried inverting the quotes?

instead of `$('#segmentationResult').html('<%= line_chart @hashes_of_date_values, {id: "chart1"} %>');`

try:

`$('#segmentationResult').html("<%= line_chart @hashes_of_date_values, {id: 'chart1'} %>");`

? thats the only different thing i can think that you are making from my use cases...

**Comment by alejorivera** [comment]
Just had the same issue. 

+1 to merging #192.

**Comment by ankane** [comment]
Closing - see #192 for explanation.
