### ISSUE TITLE
Area chart with multiple values not rendering properly.

### ISSUE THREAD

**Issue by grimmwerks** [ankane/chartkick#195]
I was hoping to implement an area chart with overlapping values much like I was implemeting a line chart, but there's something flaky going on with the drawing.

These images hold the same values:
![screenshot 2015-08-10 16 24 06](https://cloud.githubusercontent.com/assets/210795/9183302/534ca5c2-3f7c-11e5-9618-242c4ade9f3a.png)
![screenshot 2015-08-10 16 24 25](https://cloud.githubusercontent.com/assets/210795/9183305/5b439dda-3f7c-11e5-8eb0-26db2050a2a3.png)

It might be clearer in this video:  https://www.dropbox.com/s/1hd6qznnw3sdcjt/Screenshot%202015-08-10%2016.24.25.png?dl=0

**Comment by ankane** [comment]
Area charts are stacked by default. I just added support to disable this on master.
