### ISSUE TITLE
Bar and column chart don't formats datetime

### ISSUE THREAD

**Issue by phlegx** [ankane/chartkick#196]
If I use column or bar chart the axis with the datetime gets not formatted like in the line chart. What can I do? Any idea why `processColumnData` has `processSeries(..., ..., false)`?

``` js
function processColumnData(chart) {
    chart.data = processSeries(chart.data, chart.options, false);
    renderChart("ColumnChart", chart);
  }
```

**Comment by swrobel** [comment]
Here are screenshots for comparison (data is identical):

`line_chart`
<img width="434" alt="screenshot 2016-08-19 06 52 33" src="https://cloud.githubusercontent.com/assets/157270/17811969/ec1275c8-65d9-11e6-8666-50a08d6d0b8f.png">

`column_chart`
<img width="319" alt="screenshot 2016-08-19 06 55 41" src="https://cloud.githubusercontent.com/assets/157270/17811987/0489bf12-65da-11e6-8513-50187ab21150.png">

**Comment by ankane** [comment]
Chartkick doesn't support dates/times for bar or column charts. You'll want to use `strftime` or similar to convert the dates to the labels you want before passing them to Chartkick.
