### ISSUE TITLE
How to add percentage labels to pie chart?

### ISSUE THREAD

**Issue by phlegx** [ankane/chartkick#197]
How can I add percentage labels to pie charts? Any idea?

**Comment by kashifnaseer** [comment]
I'm also looking for it. any solution ?

**Comment by ankane** [comment]
Google Charts should add percentage labels by default. For Highcharts, you'll need to use the `library` option to accomplish this.

**Comment by kashifnaseer** [comment]
I actually want to have output present in http://jsfiddle.net/hAnCr/31/ . it uses labelFormatter to show percentage with a Function call. As i understand, this gem will start supporting Function() in future releases. How i can achieve it or any work around to get this working.

```
labelFormatter: function() {
                    total += this.y;
					return '<div style="width:200px"><span style="float:left">' + this.name + '</span><span style="float:right">' + this.y + '%</span></div>';

```

**Comment by kissu** [comment]
Hi, I cannot find which `library` option to pass for highchart. :(
None of those are working: https://stackoverflow.com/questions/17246187/displaying-percentage-in-y-axis-of-highcharts-column-chart
