### ISSUE TITLE
Format currency in tooltip

### ISSUE THREAD

**Issue by jtlindsey** [ankane/chartkick#200]
Hello,

I'm using a column chart with rails and managed to get currency working on the y axis, but not in the tool tip.
![screen shot 2015-08-19 at 8 00 20 pm](https://cloud.githubusercontent.com/assets/7409277/9372480/fbaf4152-46ac-11e5-8546-d9f9e857e612.png)

Here is my original code in helper.rb

```
  def networth_data
    [
      {name: "Assets", data: {"NetWorth": Account.assets(current_user)}}, 
      {name: "Liabilities", data: {"NetWorth": Account.liabilities(current_user)}}
    ]
  end
```

And in view

```
<%= column_chart networth_data, colors: ["green", "#FF0000"], library: {pointSize: 0, vAxis:  {format: "currency"}, backgroundColor: "#FFF", height: 265} %>
```

![screen shot 2015-08-19 at 7 58 08 pm](https://cloud.githubusercontent.com/assets/7409277/9372461/b2b5f02c-46ac-11e5-8138-4ea089b57501.png)

Im not sure what to change to get the tooltip displaying the currency instead of raw number. Is there a way to change this?

**Comment by jjahaziel** [comment]
I have the same problem

**Comment by jtlindsey** [comment]
I ended up turning the tooltip off. See example.

```ruby
<%= column_chart networth_data, colors: ["green", "#FF0000"], library: {pointSize: 0, vAxis:  {format: "currency"}, legend: { position: 'none'}, backgroundColor: "#FFF", height: 265} %>

```

**Comment by ankane** [comment]
It'd be great to have a `prefix` option for this (and a `suffix` one for things like percentages).

**Comment by alexperezpaya** [comment]
@ankane any updates on prefix / suffix?

**Comment by ankane** [comment]
No, it's not something I'm actively working on, but anyone can give it a shot. Chartkick.js issue is here: https://github.com/ankane/chartkick.js/issues/74

**Comment by ankane** [comment]
The `prefix` option was added in 2.3.0.
