### ISSUE TITLE
Charts show Dates with 0 value for Non-Existent Days

### ISSUE THREAD

**Issue by trendwithin** [ankane/chartkick#204]
I've been learning  Chartkick with Groupdate using  Google jsapi over the past couple days but have reached a point where I'm stumped and haven't found documentation on how exactly to address my problem since it could be related to any of these.  My data intentionally has non-existent days as there will only be input for Mon-Fri, but the chart still renders weekends (empty dates).

Here's and abridged version of my seed file I'm checking against

```
High.create symbol: 'A', saved_on: DateTime.now
High.create symbol: 'A', saved_on: DateTime.now - 1.days
High.create symbol: 'BOOM', saved_on: DateTime.now - 4.days
High.create symbol: 'DOOM', saved_on: DateTime.now - 5.days
High.create symbol: 'ZOOM', saved_on: DateTime.now - 6.days
```

simple line_chart

```
 <%= line_chart High.group_by_day(:saved_on, format: "%B %d, %Y").count, discrete: true %>
```

And my chart: 

<img width="150" alt="chart" src="https://cloud.githubusercontent.com/assets/8145031/10032519/67f7343c-6138-11e5-8021-1d1e581516f3.png">

Any pointers on this would be greatly appreciated.

**Comment by ankane** [comment]
You can use Groupdate's `series: false` option to get rid of the zeros.
