### ISSUE TITLE
chartkick.js is returned as text/html instead of text/javascript

### ISSUE THREAD

**Issue by alexhanh** [ankane/chartkick#205]
This started happening maybe 1-2 weeks ago, before that we've been using Chartkick without this problem. Thus, it might be related to some recent update.

For some reason, on our production server (Nginx + Passenger), the server sometimes (unpredictably and semi-randomly) returns chartkick.js as text/html and the response contains our main layout rendered.

![chartkick](https://cloud.githubusercontent.com/assets/386490/10086678/64a6781a-6318-11e5-850d-9dee4ef2fc57.jpg)
![chartkick2](https://cloud.githubusercontent.com/assets/386490/10086682/6983b866-6318-11e5-8317-ff20848c7d0b.jpg)
![chartkick3](https://cloud.githubusercontent.com/assets/386490/10086769/e4552aca-6318-11e5-8aff-7fe3ba2ef982.jpg)

As you can see, for some reason it renders the application layout and returns that as a response.

It's weird, because most of the times it does work and Chartkick's Javascript is returned properly.

**Comment by ankane** [comment]
This look like an issue with your web server configuration.

**Comment by alexhanh** [comment]
Hey! Looks like you are right, the issue seems to have disappeared. Apolohizes for the trouble and thank you for providing a great library!
