### ISSUE TITLE
Can't create a stacked column chart

### ISSUE THREAD

**Issue by guyisra** [ankane/chartkick#206]
the helper generate this js

```
new Chartkick.ColumnChart("chart-3", [{"name":"None","data":{"none":501}},{"name":"Shoes","data":[["None",1],["Flats & Loafers",1]]},{"name":"Bottoms","data":[["Skirts",1]]},{"name":"Jewelry","data":[["None",1]]},{"name":"Accessories","data":[["Belts",1]]},{"name":"Bags","data":[["None",1]]},{"name":"Dresses","data":[["None",116],["Midi",6],["Maxi",4]]},{"name":"Tops","data":[["None",6],["Shirts",6],["Sweaters & Cardigans",1]]}], {"stacked":true});
```

but the chart doesn't stack, and only shows a single bar in None. Seeing the js object resulting, the value of any data is NaN

Basically what I was  hoping for is a column per type series which is divided by its data (sub categories of those items)

**Comment by ankane** [comment]
Hey @guyisra, thanks for reporting 👍 

With the latest version of Chartkick, this example seems to work for Google Charts and Highcharts. With Chart.js, I'm getting odd `NaN` values.

**Comment by ankane** [comment]
For reference, this is fixed on Chart.js master. Will close when Chart.js 2.7.1 is released.

**Comment by ankane** [comment]
It was just released :)
