### ISSUE TITLE
Tmeline - undefined method error

### ISSUE THREAD

**Issue by annieogrady** [ankane/chartkick#207]
With chartkick and ruby on rails, I am using google charts.  I was trying the sample code on chartkick.com  .  I am getting an error message on trying to use this timeline code:

<%= timeline [
  ["Washington", "1789-04-29", "1797-03-03"],
  ["Adams", "1797-03-03", "1801-03-03"],
  ["Jefferson", "1801-03-03", "1809-03-03"]
] %>

i am getting this error:  undefined method `timeline' for #<#<Class:0x007fc63ecad738>:0x007fc625ccb3a0>

nb:  all the other examples are working 

Does timeline work with google charts?  do you recommend highcharts over google?

**Comment by ankane** [comment]
Hey @annieogrady, what version of chartkick are you running?

**Comment by annieogrady** [comment]
hi Andrew,

Thanks for the question!

by default (i did not set the version), it installed -

based on your question, i reviewd the change log and noticed the timeline
was a higer version.

many thanks for your help.

really like the product - hope you all keep up the great work.
if you need me to beta test or anything, let me know.

thanks
annie

Annie O'Grady
Co-founder
AgentBright, Inc
3544 Crown Point Road
Louisville, TN 37777
860-575-6950
