### ISSUE TITLE
Chartkick 2.0, Take 2

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick#208]
Game plan - breaking changes
- [x] default to [Chart.js v2](https://github.com/nnnick/Chart.js#v20-development) - yay open source!
- [x] default to discrete chart if date/time format not detected
- [x] detect dates

Game plan - non-breaking
- [x] add official JS API
- [x] clean up chartkick.js code

Chart.js
- [x] single data point - https://github.com/chartjs/Chart.js/issues/2354
- [x] position legend to the right - https://github.com/chartjs/Chart.js/issues/2059 and others
- [ ] stacked area chart color blending (need to file issue)

Chart.js bonus
- [x] Scatter plot - https://github.com/dima117/Chart.Scatter but for Chart.js 2.0
- [ ] Better display for large number of labels

**Comment by cycomachead** [comment]
Chart.js also makes it easy to save as images (#29 and #156)
http://www.chartjs.org/docs/#advanced-usage
