### ISSUE TITLE
Pie with 3d option

### ISSUE THREAD

**Issue by glpunk** [ankane/chartkick#211]
Sorry if is duplicated, I tried to search a similar question but didn't find. 
I'm trying to put pie chart with option3d, like this one:

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/3d-pie/

With this code, passing library options:

pie_chart data, library: { chart: { type: 'pie', options3d: { enabled: true, alpha: 45, beta: 0 } },  tooltip: { pointFormat: "Valor: {point.y:.2f}%" } }

I tried some variations, but the result is always the same, the chart render fine but in 2d. By the way, the "tooltip" option always works fine. 

any clue? 

thank you so much, very nice tool.

**Comment by marshallmassengill** [comment]
I hope you managed to solve this but if you didn't then there are two things you need to do. You need to enable/add the javascript file for highcharts-3d (//= require highcharts/highcharts-3d) and then you'll also need to add in the other options and not just the sub-options so your call to library should look more like this: 
library: {chart: { options3d: {enabled: true,alpha: 45,beta: 0}},plotOptions: {pie: {depth: 35}}

**Comment by glpunk** [comment]
Works fine! thank you!

**Comment by HardikPurohit** [comment]
It does't work I tried like : <%= pie_chart [["Football", 10], ["Basketball", 5]] ,library: {chart: { options3d: {enabled: true,alpha: 45,beta: 0}},plotOptions: {pie: {depth: 35}}}%>
