### ISSUE TITLE
Chart didnt load at the first time page load

### ISSUE THREAD

**Issue by andreasarnold02** [ankane/chartkick#213]
Im using ajax to change the statistics
But when i change, some of the chart wont loaded at the first time, but when i change again its back to normal.
![screenshot from 2015-10-20 11 44 17](https://cloud.githubusercontent.com/assets/8788689/10598193/0ac4edc8-7721-11e5-9290-8f94d60a1fba.png)
Im using json to pass the data.
Is there any problem with turbolinks?
- Sorry for my bad English

**Comment by existent-co-uk** [comment]
This is affecting me too; seems like it might be a bad interaction with Turbolinks...

**Comment by tomtom87** [comment]
Having the same problem here, just installed and all I get is loading... message

**Comment by ankane** [comment]
This could be due to Turbolinks. There's a good discussion in #225 about it, so going to close this one.
