### ISSUE TITLE
Bad request for Google WebFonts

### ISSUE THREAD

**Issue by existent-co-uk** [ankane/chartkick#215]
The following error message is logged in the JavaScript console.

```
GET https://fonts.googleapis.com/css?family=%27Lucida+Grande%27,+%27Lucida+Sans+Unicode%27,+Verdana,+Arial,+Helvetica,+sans-serif 400 (OK)
```

**Comment by ankane** [comment]
Hi @existent-co-uk, I haven't seen this before. Is it still happening?

**Comment by existent-co-uk** [comment]
Yes, still happening I'm afraid. I'm guessing it's because the URL

https://fonts.googleapis.com/css?family=%27Lucida+Grande%27,+%27Lucida+Sans+Unicode%27,+Verdana,+Arial,+Helvetica,+sans-serif

specifies fonts that are not freely available from Google Web Fonts.

**Comment by ankane** [comment]
Not sure I really understand this issue. Feel free to add repro instructions and reopen.
