### ISSUE TITLE
How to specify color of a given slice of a Pie chart?

### ISSUE THREAD

**Issue by dugjason** [ankane/chartkick#220]
Disclaimer - this is a support request!
I'm trying to create a pie chart of satisfaction ratings; I know my possible values will be either 'good', 'bad' or 'offered'. I can not ensure I will always get values for each of these three values.
Ideally I'd like to be able to ensure that my 'good' results are always colored green, the 'bad' ones red, etc.
I'm having trouble specifying consistent colors for each score value; unfortunately I keep seeing results like the following: 

![screen shot 2015-11-20 at 16 18 57](https://cloud.githubusercontent.com/assets/273718/11305000/6f5db762-8fa2-11e5-90ce-b11e8386478a.png)

The code in my view right now is:

```
pie_chart(@user.ratings.order(:score).group(:score).count)
```

Does anyone know how I can ensure specific 'score' values are always colored the same way?
I'm using the Google Charts adapter, and have been unable to figure it out from [their docs](https://google-developers.appspot.com/chart/interactive/docs/gallery/piechart) so far

**Comment by michaelanhari** [comment]
I think you might be able to do it like this:
``` ruby
pie_chart(@user.ratings.order(:score).group(:score).count), colors: ['#111, #222, #333']
```

with the array passing colors to the first, second, and third sections of the pie chart.

**Comment by dugjason** [comment]
Thanks for the response Michael. Unfortunately it doesn't quite work like that. If we provide three colors; ```[red, green, blue]```, the first three elements returned will be (Bad, Good, Offered), will be colored red, green, blue. If we have a case where no values are returned for the 'Bad' score, 'Good' will be colored red, and 'Offered' will be colored green, as that is the order in which they were specified. 

Ideally I'm looking for a solution similar to the following to ensure an element with a given key is given a specific color:

```
pie_chart(
  @user.ratings.order(:score).group(:score).count, 
  colors: ['bad': '#111', 'good': '#222', 'offered': '#333']
)
```

**Comment by michaelanhari** [comment]
I think I found a solution. I believe you'll have to pass in your code as a series, something like:

``` ruby
<%= pie_chart [
  {
    name: "bad",
    @user.ratings.group(:score).where(score: "bad").count
  },
  {
    name: "good",
    @user.ratings.group(:score).where(score: "good").count
  },
  {
    name: "offered",
    @user.ratings.group(:score).where(score: "offerred").count
  },
],
colors: [ '#111', '#222', '#333' ]
%>
```

I haven't used `pie_chart` yet, but i wanted to do something similar with `column_chart` and this worked out for me. Hope it helps!

**Comment by dugjason** [comment]
Thanks Michael. While this absolutely works by ensuring we always create a record for each possible key-value pair, it does involve running the same query multiple times.
If something similar to the solution I suggested previously does not exist, I suppose I will be left with no choice but to use a method similar to your suggestion

**Comment by jasonivers** [comment]
You can pass this type of thing in library (you'll have to check your logic to see if the key value pair exists, but you won't have to run the query multiple times if you throw it in a variable):  slices: { '0': { color: '#2196F3' }, '1': { color: '#EEEEEE' } }

**Comment by jeremygradisher** [comment]
I needed 7 specific colors so the Google chart colors would match a lease plan. Even if a few of the status's are missing, I needed specific colors according to the status. This is the way that I got it to work. 

`<div id="chart-8" style="height: 300px; width: 100%; text-align: center; color: #999; line-height: 300px; font-size: 14px; font-family: Helvetica, sans-serif;">Loading...</div>`
    <script type="text/javascript">
      new Chartkick.PieChart("chart-8", {"01 Available":<%= @areas.where(status: "01 Available").count %>,
      "02 LL Construction":<%= @areas.where(status: "02 LL Construction").count %>, 
      "03 Tenant Design":<%= @areas.where(status: "03 Tenant Design").count %>, 
      "04 Tenant Fit-Out":<%= @areas.where(status: "04 Tenant Fit-Out").count %>, 
      "05 Open for Business":<%= @areas.where(status: "05 Open for Business").count %>,
      "06 Close-Out":<%= @areas.where(status: "06 Close-Out").count %>,
      "07 Operating":<%= @areas.where(status: "07 Operating").count %>}, 
      {"donut":true,"library":{"pieSliceText":"value","backgroundColor":"none","pieHole":0.4,
      "legend":{"position":"none"},
      "slices":[{"color":"#c7232a"},{"color":"#f15b28"},{"color":"#d7b920"},{"color":"#89cadc"},{"color":"#38b449"},{"color":"#561871"},{"color":"#337198"}]}});
    </script>

<img width="964" alt="google-chart-colors" src="https://cloud.githubusercontent.com/assets/9622011/21706271/c5bfcbaa-d393-11e6-92a5-1bce68007383.png">

**Comment by ankane** [comment]
You can accomplish this while keeping a single query with something like:

```ruby
data = @user.ratings.order(:score).group(:score).count
score_colors = {"good" => "blue", "offered" => "red"}
colors = []
data.each do |score, _|
  colors << score_colors[score]
end

# and later
line_chart data, colors: colors
```

**Comment by anselmobattisti** [comment]
Its old but can help others :)

in vuejs:

`<pie-chart :colors="['red', 'orange', 'green']" :data=myData()></pie-chart>`
