### ISSUE TITLE
Security Bug:  Missing Subresource Integrity Protection

### ISSUE THREAD

**Issue by ACPK** [ankane/chartkick#222]
When meeting W3C specifications, there is issue with code below as there isn't an SRI hash:

    <script src="//www.google.com/jsapi"></script>

From TinfoilSecurity:

All externally loaded resources must have their content pinned using the subresource integrity mechanisms provided by modern browsers. This involves computing a hash of the contents of the resource, and specifying this hash when loading that resource. In the case of a script, this might look like the following:

Example

    <script src="https://example.com/include.js"
            integrity="sha256-Rj/9XDU7F6pNSX8yBddiCIIS+XKDTtdq0//No0MH0AE="
            crossorigin="anonymous"></script>

**Comment by ankane** [comment]
Hi @ACPK, if you want to use subresource integrity, you can follow [the instructions here](http://githubengineering.com/subresource-integrity/) when you include the Javascript files. Closing as not an issue.

**Comment by nickrivadeneira** [comment]
I don't believe a SRI hash will work with the `google.com/jsapi` script. After attempting to turn it into a hash with https://www.srihash.org/, it fails because the response header does not include `Access-Control-Allow-Origin`.
