### ISSUE TITLE
group_by_month(:date) returns number of entries under that month instead of month_name

### ISSUE THREAD

**Issue by acp15ak** [ankane/chartkick#224]
I have an application under which I have purchase_date, quantity and price.

When I use column_chart (uing haml):
'=column_chart PurchaseHistory.group_by_month(:purchase_date).sum("price \* quantity")'
it returns number of items under that month instead of the name of the month.

Is there any way to achieve this?
![report_screenshot](https://cloud.githubusercontent.com/assets/16144644/11580152/537f971a-9a2c-11e5-8758-2862b81c1770.png)

Note: i used Dateslices (https://rubygems.org/gems/dateslices); without it group_by_month gives SQLLite error

**Comment by ankane** [comment]
Hi @acp15ak, you'll want to make sure your data is in [this format](https://github.com/ankane/chartkick#data).

**Comment by acp15ak** [comment]
Okay.. But I cannot figure out how to get name of the month when I use the graph.. Is there a way to do it? Really appreciate your help!

    <%= column_chart({20.day.ago => 5, 1368174456 => 4, "2013-05-07 00:00:00 UTC" => 7})%>

![chartkick_andrew](https://cloud.githubusercontent.com/assets/16144644/11588280/0f678ccc-9a77-11e5-8bcb-46af8a37422d.png)

**Comment by acp15ak** [comment]
this is weird
If I use line_chart instead of column_chart, the name of the month shows up!

**Comment by jdraths** [comment]
@acp15ak, can you strftime it?  (2013-05-07 00:00:00 UTC).strftime("%b %Y")

**Comment by acp15ak** [comment]
@jdraths Hey BigRon..
I am sorry I cannot try your solution now. The project was finished in January and I no longer have any access to it. The client (the teacher) was happy with the line chart so we moved on to other aspects of the system. But I don't understand why it would work differently for different chart types? Shouldn't the axis be the same if the parameters are same same well?

**Comment by ankane** [comment]
Cleaning up issues
