### ISSUE TITLE
Adding a transparent background 

### ISSUE THREAD

**Issue by arun1595** [ankane/chartkick#229]
How can I add a transparent background to the container displaying the pie chart? By default, its white and as per the documentation, only hex colors are supported. Is there a way to do it?

**Comment by ankane** [comment]
For Google Charts, you can use:

```ruby
pie_chart data, library: {backgroundColor: "transparent"}
```

**Comment by ankane** [comment]
Cleaning up issues

**Comment by vaibhav101** [comment]
Has this functionality been removed now? It does not seem to work and I could not find it in the code
