### ISSUE TITLE
Gantt Chart Support

### ISSUE THREAD

**Issue by kyleoliveira** [ankane/chartkick#231]
Any chance you could add support for Gantt Charts? Google Charts just added one (it's in beta) and Highcharts has one on their roadmap (http://www.highcharts.com/support/roadmap).

If I wanted to try to implement it myself, where would be the best place to start?

**Comment by francesco-loreti** [comment]
any news?

**Comment by ankane** [comment]
Sorry for the very delayed response. There are no plans to support other chart types at this time.
