### ISSUE TITLE
Pie Chart with Series Data

### ISSUE THREAD

**Issue by bsbodden** [ankane/chartkick#232]
I'm trying to recreate one the basic highcharts examples at
http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/pie-basic/

The reason I want use the series format for the data is that I have a Web Service endpoint that already returns series data and I don't want to write a different one just for pie chart data (otherwise I could get away with the simple `[[foo: 0.5], [bar: 0.25], [baz: 0.25]]` format. Any ideas. I also tried used the `library` option but don't know what to pass for the data (tried null, [], {} but none worked). Thanks.

Here's what the series data from the example looks like: 

```
series: [{
            name: 'Brands',
            colorByPoint: true,
            data: [{
                name: 'Microsoft Internet Explorer',
                y: 56.33
            }, {
                name: 'Chrome',
                y: 24.03,
                sliced: true,
                selected: true
            }, {
                name: 'Firefox',
                y: 10.38
            }, {
                name: 'Safari',
                y: 4.77
            }, {
                name: 'Opera',
                y: 0.91
            }, {
                name: 'Proprietary or Undetectable',
                y: 0.2
            }]
        }]
```

**Comment by bsbodden** [comment]
This is what all of my attempts endup looking like: 
![pie_chart_with_series_data](https://cloud.githubusercontent.com/assets/24109/12992573/7451c3c8-d0d2-11e5-8946-86836319be64.png)

**Comment by bsbodden** [comment]
I see from https://github.com/ankane/chartkick/blob/master/app/assets/javascripts/chartkick.js#L368 that for the pie chart the data is passed as the data of a single series:

```
          options.series = [{
            type: "pie",
            name: "Value",
            data: chart.data
          }];
          new Highcharts.Chart(options);
```

So I'm guessing that the only work around would be to somehow override the whole `options.series` and somehow prevent that assignment from happening.

**Comment by bsbodden** [comment]
I'll work around it on the client side of my app and I'll send a PR if I come up with an elegant solution for this. Thanks, awesomely convenient gem btw.

**Comment by glpunk** [comment]
Hi, this looks very old, but I'm having the same problem, did you found any solution?

**Comment by bsbodden** [comment]
@glpunk I ended just transforming the data into an array of arrays:

```
# transform data to flat array or array format for pie charts
if @chart_type == :pie
  @chart_data = @chart_data.map { |s| s.map { |k,v| v }}
end
``

**Comment by glpunk** [comment]
Thank you @bsbodden !

I'm needing the other format to pass "custom" data to show into the tooltips, I mean, right now I have flat array and works fine, but for custom data I need array of objects.

I downloaded the gem source and trying to modified the JS source.

**Comment by ankane** [comment]
Pie charts only support a single series, so the multiple series format doesn't work.
