### ISSUE TITLE
Rails 4.2 javascripts/chartkick.js 404

### ISSUE THREAD

**Issue by tomtom87** [ankane/chartkick#233]
Just followed the installation instructions and installed via the gem. 

The gem is installed:

```
$ bundle show chartkick
/Users/tom/.rvm/gems/ruby-2.1.5/gems/chartkick-1.4.1
```
I add the google jsapi also

```
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
```

I enable it in my apps `assets/javascripts/application.js` with `//= require chartkick` and add a bit of ruby for testing purposes from the examples:

```
<%= pie_chart [["Football", 10], ["Basketball", 5]] %>
```

_Nothing_ happens. No graph displays. But the app loads.

On closer inspection, navigation to the javascripts/chartkick.js is a 404.

I unpacked the gem manually and `cp` the chartkick.js over to the javascripts directory. Now I get a loading... message and nothing else.

I include the chartkick.js with this in order to get the loading.. message, that is the only output I have been succesful with so far

```
<%= javascript_include_tag "application", "chartkick" %>
```

Turbolinks is not installed.

Thank you very much for your help on this issue.

**Comment by seanfcarroll** [comment]
I have the same issue on Rails 4.2

**Comment by aried3r** [comment]
I'm facing the same problem, it works in development, but fails with the 404 error in production.

**Comment by ankane** [comment]
You may need to set:

```ruby
config.serve_static_files = true
# previously named serve_static_assets
```

in `config/production.rb`.

**Comment by ankane** [comment]
Cleaning up issues. Let me know if you find anything new.
