### ISSUE TITLE
Continuous value linecharts

### ISSUE THREAD

**Issue by reisner** [ankane/chartkick#234]
Hi there, I can't seem to figure out how to make a continuous valued line chart without dates.

For example, with this example:

<% data = [
[1,1],[2,3],[3,5],[4,8],[6,4],[7,2]
] %>

<%= line_chart data,  {discrete: true, library: {width: 600} }%>

The value for 5 is not on the x axis. How do I also show the value of 5?

**Comment by ankane** [comment]
Hi Roman, only date/time and discrete/category scales are supported.
