### ISSUE TITLE
Line Chart is showing current Date counts on its previous date

### ISSUE THREAD

**Issue by kashifnaseer** [ankane/chartkick#240]
Line Chart is showing current Date counts on its previous day. In the below mentioned HASH, It clearly shows 49 count on August 23, 2015. But when it renders the chart. it shows 49 on August 22, 2015. am i missing something? Any idea, how i can fix it ?

 `@timeline_chart ={["Team", "August 21, 2015"]=>0,
 ["Team", "August 22, 2015"]=>1,
 ["Team", "August 23, 2015"]=>7,
 ["Company", "August 21, 2015"]=>1,
 ["Company", "August 22, 2015"]=>4,
 ["Company", "August 23, 2015"]=>49}`

Query:
`@timeline_chart = impressions.group(:impressionable_type).group_by_day(:created_at, format: "%B %d, %Y").count`
call:
`line_chart @timeline_chart`

I'm using chartkick with highcharts.

**Comment by ankane** [comment]
Hey @kashifnaseer, does this still happen in Chartkick 2.0? If so, can you paste the generated JavaScript?

**Comment by ankane** [comment]
Cleaning up issues. Please re-open if you have more info.
