### ISSUE TITLE
Implement box chart / candlestick chart

### ISSUE THREAD

**Issue by rajsahae** [ankane/chartkick#241]
I'm curious why Google Candlestick Charts (aka Highcharts Box Plot) isn't implemented? Would be really nice to have.

**Comment by benprew** [comment]
Looks like it's not provided in charkick.js[1], which is where you'd need have it supported first.  This gem is mostly a wrapper around those calls.  Note: I would also like to see CandleStick chart supported.

[1] https://github.com/ankane/chartkick.js

**Comment by rajsahae** [comment]
Good point. I knew the gem was mostly a wrapper around chartkick.js but I didn't realize it was in a different repo. Should I close this request and open a new request in that repo?

**Comment by rajsahae** [comment]
I posted a request  in the chartkick.js repo. Will leave this request open assuming that if/when the feature is added to chartkick.js, there will need to be some work done in this repo to wrap that capability in.

**Comment by ankane** [comment]
For reference, there are no plans to support other chart types at this time.
