### ISSUE TITLE
Hide series by clicking on legend

### ISSUE THREAD

**Issue by vasilakisfil** [ankane/chartkick#243]
Do you know how can I acheive this? Given that this lib uses Highcharts, shouldn't be supported by default?

Take a look here on what I mean: http://www.highcharts.com/demo/line-basic (click on one legend)

**Comment by ddd1600** [comment]
It uses google charts, not highcharts

**Comment by ankane** [comment]
Chartkick supports this for Chart.js and Highcharts. For Google Charts, you'll probably need to use the library directly and do [something like this](http://stackoverflow.com/questions/22777344/google-charts-api-show-hide-series-on-legend-click-how).
