### ISSUE TITLE
Flask, chart not rendering when parameter added to url

### ISSUE THREAD

**Issue by rob3rt-keating** [ankane/chartkick#244]
@route('/chart/<env>')
def get_environment_chart(env):
    data = Results.query.filter(Result.env == env).all()

The data comes back fine and I format it into a dict and print it on the template.  But the page shows a blank chart and 'loading...' appears in place of the chart.

If I hard code the env and remove the parameter from the route and def, it works fine...

Your module works great, and I love how easy it is to use.

.

**Comment by ankane** [comment]
Hey @rob3rt-keating, that looks like Python. You'll want to re-file the issue here: https://github.com/mher/chartkick.py
