### ISSUE TITLE
Problems with Time zone and Mysql

### ISSUE THREAD

**Issue by EwertonRossi** [ankane/chartkick#248]
I try to run:

<%= line_chart Usuario.group_by_day(:created_at).count %>

an these problem appers:

Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql

I also try:

<%= line_chart Usuario.group_by_day(:created_at, time_zone: "Pacific Time (US & Canada)").count %>

**Comment by ankane** [comment]
Hi @EwertonRossi, try upgrading the Groupdate gem to the latest version - `2.5.3` - and following the instructions at that link.

**Comment by EwertonRossi** [comment]
I follow the instruction but i still have the same issues

**Comment by ankane** [comment]
Try using the `debug_time_zone_support` branch of `groupdate`.  In your Gemfile:

```ruby
gem "groupdate", github: "ankane/groupdate", branch: "debug_time_zone_support"
```

and `bundle install` again.

**Comment by ankane** [comment]
It should throw a more useful error, which would be great if you could paste back.

**Comment by ankane** [comment]
Cleaning up issues. Please refile under https://github.com/ankane/groupdate/issues when you're ready.
