### ISSUE TITLE
Overlapping data in a mutli series chart

### ISSUE THREAD

**Issue by ElliottRoche** [ankane/chartkick#252]
I've been looking around the docs to see if there's an option to display all the names of the series that share a value. In the example below, if I hover over the intersection of the red and purple lines, I only see 'Eat breakfast' and its value of 2, even though 'Go to concert' also has a value of 2.

![2016-04-28 at 1 12 pm](https://cloud.githubusercontent.com/assets/3212954/14896376/106dcc0a-0d43-11e6-95a2-4121f11e068d.gif)

Is there an option I can pass when creating the graph to show all series names and values for overlapping/stacked intersections like this?

P.S. This is a tremendously useful and well made tool!

**Comment by ankane** [comment]
Hi Elliott, you should be able to use the `library` option to accomplish this.  I believe what you want is `{focusTarget: "category"}`. https://developers.google.com/chart/interactive/docs/gallery/linechart#configuration-options

**Comment by ElliottRoche** [comment]
We're actually using the highcharts library, and I found a similar option in their docs after seeing Google's approach.

```{ tooltip: { shared: true }  }```

Thanks for pointing me in the right direction!
