### ISSUE TITLE
Adding Javascript Tests

### ISSUE THREAD

**Issue by jasper-lyons** [ankane/chartkick#253]
Some questions to answer regarding js tests:
- How do we feel about adding them?
- Which test frame work should be used and in which way?
- What about adding dependencies (development) to the project?

My initial thoughts were:
- I want tests so that I can check to see that the charts I'm implementing work without using external local dependencies / depending on my fork of this project for my work.
- Using Mocha or Jasmine seem like a sensible way to go (my preference is Mocha)
- This would introduce a dependency on nodejs (unless we ran tests in browser)

**Comment by ankane** [comment]
Hi Jasper, I'm happy to consider adding tests.  I'm curious to see what you had in mind.  They should probably be added to https://github.com/ankane/chartkick.js rather than here.  I haven't done much JavaScript testing, but Mocha looks like a fine option.  A node dev dependency should be fine for chartkick.js.

**Comment by jasper-lyons** [comment]
Hey Andrew, sounds good!

I'll throw together a pull request on https://github.com/ankane/chartkick.js with some basic outline tests + docs.

I'm going to assume that the js in the gem is updated from https://github.com/ankane/chartkick.js ? Is this done automatically or manually?

**Comment by ankane** [comment]
Correct. It's done manually on new releases of chartkick.js, and occasionally in between releases when it'll benefit someone.

**Comment by ankane** [comment]
Cleaning up stale issues, but still open to adding tests to Chartkick.js.
