### ISSUE TITLE
Unable to create a drilldown using the highcharts library.

### ISSUE THREAD

**Issue by Mbuckley0** [ankane/chartkick#260]
I have been unable to do a drilldown (http://www.highcharts.com/docs/chart-concepts/drilldown) using the highcharts library as an adapter. Perhaps I just haven't been able to find the correct code to use. I would love to know if it is even possible and if so what code is required to get it to work.

**Comment by ankane** [comment]
Drilldown is a neat concept, but I think it's outside the scope of Chartkick.

**Comment by JSanderbeck** [comment]
Sad this is outside of the scope of Chartkick. This is a feature that is sorely needed. Even if you allowed the drilldown to pass through with the library options it could possibly be implemented.
