### ISSUE TITLE
TimeZone problem in TimeLine chart

### ISSUE THREAD

**Issue by jatinha** [ankane/chartkick#261]
Controller:
```
    def chart
        @monitors = [];
        @monitors.push ["No Ar", "2016-05-20  00:00", "2016-05-20 14:50"]
        @monitors.push ["Fora do Ar", "2016-05-20 15:00", "2016-05-20  16:00"]
        @monitors.push ["No Ar", "2016-05-20 16:00", "2016-05-20  17:00"]
    end
```

View:
```
        <%= timeline @monitors  %>
         <%= yield :charts_js %>
```

**expected return:**
Show a timeline with the first value from 00:00 to 14:50 , the second from 15:00 to 16:00 ...

**obtaned return:**
The timeline is the first value from 21:00 to 23:50 , the second from 00:00 to 01:00 ...

**Comment by ankane** [comment]
For best results, include the time zone.  Otherwise, your browser may think it's UTC.

**Comment by jatinha** [comment]
Where I include the time zone in my code?

**Comment by ankane** [comment]
In the data, like:

```ruby
@monitors.push ["No Ar", "2016-05-20 00:00:00 PDT", "2016-05-20 14:50:00 PDT"]
```

**Comment by jatinha** [comment]
When I put @monitors.push ["No Ar", "2016-05-20 00:00:00 PDT", "2016-05-20 14:50:00 PDT"]

The return is: 04:00 -> 18:50.

I try put @monitors.push ["No Ar", "2016-05-20 00:00:00 BRT", "2016-05-20 14:50:00 BRT"]

But the google graphics return error:
Cannot read property 'datefield' of undefined

**Comment by jatinha** [comment]
I add -3 after PDT and the problem is resolved:

@monitors.push ["No Ar", "2016-05-20 00:00:00 PDT-3", "2016-05-20 14:50:00 PDT-3"]

Thanks!
