### ISSUE TITLE
Mixed Chart Types using Highcharts

### ISSUE THREAD

**Issue by jamesconnolly93** [ankane/chartkick#263]
I'm trying to create a mixed column/line chart using Highcharts.

I've been trying to use the `library` functionality to set one of my data series to be of type "line". I have tried a few different approaches, but I can't seem to figure out how to pass the type parameter of a given series using the Highcharts API.

`<%= column_chart( ChartData.new(@forecast).revenue_and_net_income, library: {
      title: {
        text: "Revenue and Net Income"
      },
      series: [{
        1 => {
          type: "line"
        }
      }],
    } ) %>`

Where my data come from the following method:

`def revenue_and_net_income
    data = [
      {
        name: "Revenue",
        data: revenue_by_year
      },
      {
        name: "Net Income",
        data: net_income_by_year,
      }
    ]
  end`

Not sure if I'm just doing something wrong? I only seem to be able to access the Highcharts API methods listed under 'Chart', none of the series options etc. seem to work.

**Comment by dagumak** [comment]
Also trying this as well, but haven't been successful. I even tried "spline". I dived deep into the library, and it just seems like this isn't supported. Perhaps, I might be doing something wrong, but there doesn't seem to be a way to merge the options.

**Comment by daapower** [comment]
trying to do this too.  are mixed charts not supported with highcharts or chart.js?

**Comment by ankane** [comment]
Chartkick doesn't currently support any type of combo chart.
