### ISSUE TITLE
Chartkick w Chart.js

### ISSUE THREAD

**Issue by tknazn** [ankane/chartkick#265]
I encounter the issue: **_Error Loading Chart: No adapter found_** when trying to set up chartkick with Chart.js. Though Highchart.js & Google chart are both working fine.

![screen shot 2016-06-03 at 4 14 14 pm](https://cloud.githubusercontent.com/assets/751046/15795430/51ae1b00-29a6-11e6-9ab5-e33ec5f18c64.png)

Wonder if anyone experienced the same problem and figured out solution ?

**Comment by bearded** [comment]
Chartjs works for me using:

```
//= require moment.min
//= require Chart.min
//= require chartkick
```
in app/assets/javascripts/application.js

**Comment by ankane** [comment]
Hey @tknazn, are there any error in loading `Chart.js` in the console? Also, what version of Chartkick are you on?

**Comment by SeriusDavid** [comment]
hey ankane! i have the same issue and this is shows on the console
Cannot read property 'length' of undefined its seems that chart.js its not initializing

**Comment by ankane** [comment]
Hey @SeriusDavid, this sounds like a different error. Can you create a new issue with a JSFiddle to reproduce?

**Comment by ankane** [comment]
Cleaning up issues
