### ISSUE TITLE
Can't set xtitle and ytitle when draw bar chart

### ISSUE THREAD

**Issue by bdsword** [ankane/chartkick#266]
Got **Error Loading Chart: setXtitle is not a function** when trying to draw a bar chart.

Does chartkick support this feature? Thx

**Comment by maasomalam** [comment]
new Chartkick.ColumnChart("chart-ab", data, {"xtitle": "Country", "ytitle": "Hits"});

**Comment by bdsword** [comment]
@maasomalam Thanks for your reply.

Sorry for not describing my problem precisely.

But I'm actually using rails to render the chart.

With:

```erb
<%= bar_chart data, xtitle: 'Countery', ytitle: 'Hits' %>
```

**Comment by ankane** [comment]
This is a bug with chartkick.js https://github.com/ankane/chartkick.js/commit/11dea94a50b35c35d42479ff8142f1413c434c61

Will be fixed in the next release.  Thanks for reporting!
