### ISSUE TITLE
Change values on Y-axis from float to Integer

### ISSUE THREAD

**Issue by mahendhar9** [ankane/chartkick#269]
Hello. Thanks for the great gem.
How can I change the type of values on Y-axis to integer rather than float?

![chart](https://cloud.githubusercontent.com/assets/10587160/15994461/d941ad9c-3122-11e6-8a53-899eac083c7a.JPG)

**Comment by mahendhar9** [comment]
Found out the solution. Just add `library: {yAxis: {allowDecimals: false }}`

**Comment by echan00** [comment]
I suppose this is only for line charts?

**Comment by andreibondarev** [comment]
Is there an option for the `bar_chart`?
