### ISSUE TITLE
ComboChart

### ISSUE THREAD

**Issue by jatinha** [ankane/chartkick#270]
Hello, I need add combo chart in my project, but this is a old topic.

How I use ComboChart in Chartkick?

Today I use timelineChart and in my view I put this code... and I don't have problems...

```

        <div style="height: 115px;">
          <%= timeline @monitors  %>
          <%= yield :charts_js %>
        </div>
```

Thanks.

**Comment by ankane** [comment]
Hey @jatinha, Chartkick doesn't support any type of combo chart.
