### ISSUE TITLE
Article about Chartkick

### ISSUE THREAD

**Issue by bodrovis** [ankane/chartkick#271]
Good day! Recently I've penned an article about this gem https://www.sitepoint.com/make-easy-graphs-and-charts-on-rails-with-chartkick/ so maybe you'd want to display this link somewhere in the docs :) P.S. I'm planning to do a second part as well.

**Comment by ankane** [comment]
Thanks Ilya, nice article!

I've added a tutorials section to the readme.

**Comment by bodrovis** [comment]
Great! The second part is coming out pretty soon
