### ISSUE TITLE
How to update chart libraries?

### ISSUE THREAD

**Issue by elsurudo** [ankane/chartkick#272]
It would make sense if this was in the docs somewhere.

**Comment by ankane** [comment]
Can you explain more?

**Comment by elsurudo** [comment]
Well, I've got chartkick in my Gemfile, and am using the default charting library (charts.js). I do a `= javascript_include_tag 'charts'`, which must be using a vendored version in the gem.

What if I want to use a more up-to-date version of charts.js?

**Comment by ankane** [comment]
You can download the latest version and place it in `app/assets/javascripts`.

**Comment by elsurudo** [comment]
That's very simple, thanks.
