### ISSUE TITLE
Rendering Issue with Firefox and Safari

### ISSUE THREAD

**Issue by rjrobinson** [ankane/chartkick#274]
I'm having some weird behavior with rendering. 

I'm using the Highcharts package. I'm having a rendering issue. Seems that it works fine with Chrome. 
 Seems that in FF it bunches up in the top left. 
![screen shot 2016-06-27 at 10 46 50 am](https://cloud.githubusercontent.com/assets/3730551/16384001/605a6458-3c55-11e6-8a32-f4a66a628a79.png)

any ideas?

**Comment by ankane** [comment]
Can you use JSFiddle to reproduce? https://jsfiddle.net/

**Comment by rjrobinson** [comment]
Just a note on this. Looks like if you include chartkick in the application.js, and also have it in a javascript_include tage on the application.html.erb, this is what causes the error.

**Comment by ankane** [comment]
👍  Thanks for the update. Someone will probably find this useful / time-saving.
