### ISSUE TITLE
vAxis currency formatting for column_chart

### ISSUE THREAD

**Issue by 0ldtimer** [ankane/chartkick#275]
Have tried a number of ways to address formatting, and have scoured the issues here.  Cannot seem to get currency formatting working correctly for column_chart.  For example, this code:

<%= column_chart @impact, library:{vAxis:{format: "currency"}} %>

Renders the following:

  new Chartkick.ColumnChart("chart-1", {"Impact":2101068751}, {"library":{"vAxis":{"format":"currency"}}});

Any thoughts?

![screen shot 2016-07-11 at 6 46 06 pm](https://cloud.githubusercontent.com/assets/9030319/16749388/c5c80668-4797-11e6-9b98-5e1b7de9b545.png)

**Comment by ankane** [comment]
Hey @0ldtimer, I don't know how to do this off the top of my head. There's currently a proposal for an option to make this simpler: https://github.com/ankane/chartkick.js/issues/74
