### ISSUE TITLE
Localization: Translate chart doesn't work

### ISSUE THREAD

**Issue by fabiancarlos** [ankane/chartkick#277]
I tried everthing, and i cant translate.

Using Rails '4.2.6' and geoip '1.6.1'.

Using Line hart, Pie and Geo.

**Comment by ankane** [comment]
Hey Fabian, it's going to be hard for someone to help without more info.  Can you create a JSFiddle?

**Comment by fabiancarlos** [comment]
That's not another way to put a locale translation? 
I will try to put in JSFiddle, but i`m using Rails, soo maybe somethings work fine of the framework.

**Comment by ankane** [comment]
Cleaning up issues. Feel free to reopen if you put together a reproducible example.
