### ISSUE TITLE
Bootstrap Tabs + Chartkick: No chart until Inspect Element on latest Chrome

### ISSUE THREAD

**Issue by krainboltgreene** [ankane/chartkick#28]
Here's an example: http://jsfiddle.net/zPEML/

In this one it doesn't load even when inspecting the element.

**Comment by naoa** [comment]
This is worked well in my environment.

``
  window.dispatchEvent new Event('resize')
``

**Comment by bqst** [comment]
This is my fix :
```javascript
  $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
    var ev = document.createEvent('Event');
    ev.initEvent('resize', true, true);
    window.dispatchEvent(ev);
  });
```

**Comment by irstacks** [comment]
@bqst that works for me! thanks!

**Comment by trungnguyencmu** [comment]
@bqst: That works but I have new problem http://prntscr.com/bh09ho

**Comment by ankane** [comment]
Chartkick now has a `redraw` function for this.

```ruby
Chartkick.charts["chart-id"].redraw()
```
