### ISSUE TITLE
Please set source_code_uri for the gem

### ISSUE THREAD

**Issue by amatsuda** [ankane/chartkick#281]
Could you please set the source_code_uri for this gem as `https://github.com/ankane/chartkick`?

This attribute could be used from some external tools, scripts, or services (in my case, an rbenv plugin named [gem-src](https://github.com/amatsuda/gem-src)).

This should be able to be done via https://rubygems.org/gems/chartkick => Edit

Thanks!

**Comment by ankane** [comment]
Thanks for the suggestion, should be good now.

**Comment by amatsuda** [comment]
@ankane Thanks! ✨
