### ISSUE TITLE
Passing BigDecimal as min/max to chart.js results in Error Loading Chart: tickValue.toFixed is not a function

### ISSUE THREAD

**Issue by swrobel** [ankane/chartkick#282]
Using one of the examples, with a slight modification:

``` ruby
line_chart({20.day.ago => 5, 1368174456 => 4, "2013-05-07 00:00:00 UTC" => 7}, min: BigDecimal.new(0))
```

The chart renders the following in red text:

`Error Loading Chart: tickValue.toFixed is not a function`

This does not happen when the value is an integer or float, or if Highcharts or Google Charts are used.

**Comment by ankane** [comment]
Thanks for reporting @swrobel 👍  This should be fixed on master.
