### ISSUE TITLE
Charkick not defined

### ISSUE THREAD

**Issue by ACPK** [ankane/chartkick#287]
The chart is not loading for me in a Rail5 application.

In my application.js:

```
//= require jquery
//= require jquery_ujs
//= require chartkick
//= require highcharts
```

User view:

```
= line_chart User.group_by_day(:created_at).count
```

As seen in other closed stories, moving "render "javascript"" from the footer to the header fixed the problem. Should this be mentioned in the Gemfile and any other alternative fix?

**Comment by ankane** [comment]
Cleaning up issues. There is already a note in the instructions.

> Note: In the instructions below, application.js must be included before the helper methods in your views, unless using the :content_for option.
