### ISSUE TITLE
Unable to show referenced record name instead of id

### ISSUE THREAD

**Issue by jorgecuevas92** [ankane/chartkick#288]
I'm trying to use a pie chart that uses the model `invoice_item` and takes its `product_id` to identify which are the most coveted products. 

The problem is that I need it to show the name of the product instead of just its id and I've been trying different things with no luck.

I figured there must be a way of overwriting the default titles assigned to the chart, just like we are able to override the default colors.

Is there already a way of doing this?

This is my code:

`<%= pie_chart InvoiceItem.group(:product_id ).count, colors: ["#607D8B", "#3F51B5"] %>`

**Comment by ankane** [comment]
You'll need to pass the product names to the chart. Try:

```ruby
InvoiceItem.joins(:product).group("products.name").count
```
