### ISSUE TITLE
Question: Is there any way to set the opacity in area_chart?

### ISSUE THREAD

**Issue by fanjieqi** [ankane/chartkick#289]
Excuse me, I'd like to set the params[:stacked] is true while using the area_chart. But the area is a little transparent, cause discoloring the the area layer by layer. Therefore, could you please add the opacity as the params in area_chart. Thank you.
(Sorry for my grammar mistakes.)

**Comment by ankane** [comment]
You may be able to do this with the `library` option, but I don't know off the top of my head.
