### ISSUE TITLE
specifying string label for tooltip

### ISSUE THREAD

**Issue by jmfriend** [ankane/chartkick#292]
This is my scenario, for each student there is an amount of time spent, and number of exercises completed. The scatter graph plots the time spent vs number of exercises completed for each student. The teacher needs to be able to see the name of the student when they hover over a point.

Having looked at the underlying google chart it looks like this is supported: https://developers.google.com/chart/interactive/docs/customizing_tooltip_content 

Is there a way of passing the tooltip string in so that I can specify the name of each student?

**Comment by ankane** [comment]
There's no way right now, but it's a todo on Chartkick.js if you want to add it. https://github.com/ankane/chartkick.js/issues/76
