### ISSUE TITLE
Multi-series charts don't show the full data

### ISSUE THREAD

**Issue by edw8** [ankane/chartkick#294]
Looks like if you are using a chart with multiple datasets, you have pre-sort the sets before utilizing the view method (e.g. column_chart). Otherwise, you are missing data.

For example in the first screenshot, I'm using Groupdate to sort my data by quarter, and 2014 items are not being shown:
![screen shot 2016-09-30 at 9 12 57 am](https://cloud.githubusercontent.com/assets/3008055/18998669/80165bba-86ee-11e6-81ef-e5e959623ce6.png)

But, if I simply move 'Series3' ahead of 'Series1', the chart completely changes. 
![screen shot 2016-09-30 at 9 16 32 am](https://cloud.githubusercontent.com/assets/3008055/18998718/a5f987b2-86ee-11e6-8d77-f91d97cda0e8.png)

Is this expected?

**Comment by WeTheSheeple** [comment]
Also, it looks like using a line_chart works as expected, so it seems to be limited to column_chart
![screen shot 2016-09-30 at 10 33 20 am](https://cloud.githubusercontent.com/assets/3008055/19000817/6e625ab2-86f9-11e6-8add-0b28217baf2a.png)

**Comment by ankane** [comment]
Missing data isn't good - definitely not intentional. Can you paste the exact JavaScript that's generated?

**Comment by edw8** [comment]
Here is my data:

`testing_data = []
testing_data << {name:'series1', data:{'Thu, 01 Jan 2015'=>1, 'Wed, 01 Apr 2015'=>4, 'Wed, 01 Jul 2015'=>4, 'Thu, 01 Oct 2015'=>4, 'Fri, 01 Jan 2016'=>29, 'Fri, 01 Apr 2016'=>27, 'Fri, 01 Jul 2016'=>11}}
testing_data << {name:'series2', data:{'Wed, 01 Apr 2015'=>3, 'Wed, 01 Jul 2015'=>2, 'Thu, 01 Oct 2015'=>9, 'Fri, 01 Jan 2016'=>14, 'Fri, 01 Apr 2016'=>9, 'Fri, 01 Jul 2016'=>5}}
testing_data << {name:'series3', data:{'Tue, 01 Apr 2014'=>3, 'Tue, 01 Jul 2014'=>0, 'Wed, 01 Oct 2014'=>0, 'Thu, 01 Jan 2015'=>2, 'Wed, 01 Apr 2015'=>2, 'Wed, 01 Jul 2015'=>7, 'Thu, 01 Oct 2015'=>3, 'Fri, 01 Jan 2016'=>11, 'Fri, 01 Apr 2016'=>19, 'Fri, 01 Jul 2016'=>2}}
testing_data << {name:'series4', data:{'Tue, 01 Apr 2014'=>12, 'Tue, 01 Jul 2014'=>8, 'Wed, 01 Oct 2014'=>0, 'Thu, 01 Jan 2015'=>0, 'Wed, 01 Apr 2015'=>6, 'Wed, 01 Jul 2015'=>11, 'Thu, 01 Oct 2015'=>9, 'Fri, 01 Jan 2016'=>13, 'Fri, 01 Apr 2016'=>22, 'Fri, 01 Jul 2016'=>14}}
testing_data << {name:'series5', data:{'Fri, 01 Jan 2016'=>8, 'Fri, 01 Apr 2016'=>6, 'Fri, 01 Jul 2016'=>15}}`

And, here is the JS:

`<script type="text/javascript">
  new Chartkick.ColumnChart("chart-2", [{"name":"series1","data":{"Thu, 01 Jan 2015":1,"Wed, 01 Apr 2015":4,"Wed, 01 Jul 2015":4,"Thu, 01 Oct 2015":4,"Fri, 01 Jan 2016":29,"Fri, 01 Apr 2016":27,"Fri, 01 Jul 2016":11}},{"name":"series2","data":{"Wed, 01 Apr 2015":3,"Wed, 01 Jul 2015":2,"Thu, 01 Oct 2015":9,"Fri, 01 Jan 2016":14,"Fri, 01 Apr 2016":9,"Fri, 01 Jul 2016":5}},{"name":"series3","data":{"Tue, 01 Apr 2014":3,"Tue, 01 Jul 2014":0,"Wed, 01 Oct 2014":0,"Thu, 01 Jan 2015":2,"Wed, 01 Apr 2015":2,"Wed, 01 Jul 2015":7,"Thu, 01 Oct 2015":3,"Fri, 01 Jan 2016":11,"Fri, 01 Apr 2016":19,"Fri, 01 Jul 2016":2}},{"name":"series4","data":{"Tue, 01 Apr 2014":12,"Tue, 01 Jul 2014":8,"Wed, 01 Oct 2014":0,"Thu, 01 Jan 2015":0,"Wed, 01 Apr 2015":6,"Wed, 01 Jul 2015":11,"Thu, 01 Oct 2015":9,"Fri, 01 Jan 2016":13,"Fri, 01 Apr 2016":22,"Fri, 01 Jul 2016":14}},{"name":"series5","data":{"Fri, 01 Jan 2016":8,"Fri, 01 Apr 2016":6,"Fri, 01 Jul 2016":15}}], {"xtitle":"Quarterly","stacked":true});
</script>`

**Comment by ankane** [comment]
Thanks @edw8, should be fixed on master. Chart.js didn't like undefined values for sparse datasets. Unfortunately, it has tooltips that show `NaN`, which isn't great, but think this needs to be fixed in Chart.js.

**Comment by edw8** [comment]
Cheers!
