### ISSUE TITLE
Line and Area missing when deployed.

### ISSUE THREAD

**Issue by thomasjedstrom** [ankane/chartkick#295]
Hey Guys,

I'm not sure what's happening here, but when I run my rails app using chartkick locally, everything is kosher and works as expected.  Once deployed, my pie graph, geolocation, and bar graph work as expected but the area and line charts are missing their lines.  The charts are obviously updating as the y-axis grows with site visits (the line chart is for gross-site-activity and the area chart shows site visits), but the line isn't there.  I'm not seeing any unexpected errors in either the console or my logs so I'm really at a loss as to where to even start debugging this.

You can see the deployed app here:

http://66.172.11.195:32778/

Any thoughts of what's going on?

**Comment by ankane** [comment]
Hey @thomasjedstrom, the link doesn't appear to be working.

**Comment by thomasjedstrom** [comment]
Sorry, giant sigh, on an unrelated note, my server kept crashing so they moved me to a different data center (as in maybe about an hour ago, which is why it wasn't working when you checked it).  Since rebooting the server and subsequently redeploying, everything is now working.  I don't know what the issue was and can't even begin to guess on how to replicate it, but all is good now.

You can see it (now functioning) here (and this time it should work):

http://66.172.11.195:32776/

**Comment by benortiz** [comment]
I'm experiencing a similar situation. It's only my line charts that aren't working and only on some pages. The difference with my situation is that the line charts aren't loading on mobile, but work fine on desktop, even with the same browser width. iOS Safari and Chrome.

I've made sure that each page has the google jsapi included before the chartkick js. 

The only difference I have been able to find through inspection between desktop and mobile is in the "tabular representation of the data in the chart". When a chart is loaded on mobile, I get:

``` html
<div aria-label="A tabular representation of the data in the chart." style="position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden;">
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Follows</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td> NaN, NaN, 12:NaN:NaN AM</td>
        <td>18</td>
      </tr>
    </tbody>
  </table>
</div>
```
Which looks like:
![img_0019](https://cloud.githubusercontent.com/assets/681189/19533285/f2c31d24-95f3-11e6-8089-20fc3dce7d20.png)

On desktop, the same page and the same chart load with: 
``` html
<div aria-label="A tabular representation of the data in the chart." style="position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden;">
  <table>
    <thead>
      <tr>
        <th></th>
        <th>Follows</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Nov 1, 2014</td>
        <td>8</td>
      </tr>
      <tr>
        <td>Dec 1, 2014</td>
        <td>10</td>
      </tr>
      <!-- continues on -->
    </tbody>
  </table>
</div>
```
Which looks like:
![follows admin oppsites 2016-10-19 12-03-00](https://cloud.githubusercontent.com/assets/681189/19533302/05265044-95f4-11e6-8792-3cc23ced68f4.png)

I am not using any sort of content blocker on mobile. On other pages in my app I can load line charts on mobile with trend lines. All other charts load fine, even on the pages that also have line charts.

If I should open this as a separate issue, let me know.

Thanks for your help!

**Comment by ankane** [comment]
Hey @benortiz, can you create a JSFiddle for this to make it easier to investigate?
