### ISSUE TITLE
Chart.js reverse yAxes option not transferring over 

### ISSUE THREAD

**Issue by aaron-coding** [ankane/chartkick#296]
Chart.js supports inverse / reverse yAxes in their api:
https://github.com/chartjs/Chart.js/issues/129
https://github.com/chartjs/Chart.js/commit/76d2a782fc966a1e697e07dfa92687ef4d810ac6 

However, when using chartkick it seems impossible to send this option to Chart.js. I've tried the following: (And yes, I am installed correctly into Chart.js)

`<%= area_chart(
                data,
                { :library => {
                    :options => {scales: { yAxes:  { reverse: true } } }
                  }
                }
            ) 
%>`

`<%= area_chart(
                data,
                { :library => {
                    { yAxes:  { reverse: true } }
                  }
                }
            ) 
%>`

`<%= area_chart(
                data,
                { :library => {
                  {scales: { yAxes:  { reverse: true } }
                  }
                }
            ) 
%>`

`<%= area_chart(
                data,
                { :library => {
                    { yAxis:  { reverse: true } }
                  }
                }
            ) 
%>`

If this is not the proper place to discuss this, I am sorry, I'd be happy to move it to a more appropriate location.

**Comment by ankane** [comment]
Try:

```erb
<%= area_chart data, library: {scales: {yAxes: [{ticks: {reverse: true}}]}} %>
```

**Comment by aaron-coding** [comment]
Hey @ankane,

Thanks so much, that worked! 

I didn't find that in the documentation or chartkick or Chart.js, but people will probably be able to find it right here now.

**Comment by aaron-coding** [comment]
Hey @ankane,

Thanks so much, that worked! 

I didn't find that in the documentation or chartkick or Chart.js, but people will probably be able to find it right here now.

**Comment by ankane** [comment]
Fwiw, this was under "Tick Configuration" in the [Chart.js docs](http://www.chartjs.org/docs/).
