### ISSUE TITLE
hAxis format not followed for column chart

### ISSUE THREAD

**Issue by portwood** [ankane/chartkick#298]
Hi.
I have a chart with the following "hAxis: { format: 'MM/dd' ...}"
The above works properly on a line_chart and give 'YYYY-MM-DD' for column_chart.
I expect it to honor the hAxis format regardless of chart type. Please let me know if I'm doing something incorrectly.

**Comment by ankane** [comment]
Similar reason as #299 - all columns are treated as discrete/categorical for line charts.
