### ISSUE TITLE
Column_chart not properly handling multiple columns

### ISSUE THREAD

**Issue by portwood** [ankane/chartkick#299]
Hi.
I have a column_chart with up to 5 columns for each date. Under some circumstances, the horizontal axis, which is date, becomes scrambled. Converting the same call to a line_chart provides the correct horizontal axis.

Here is the generated html for the column chart:

  <div class="row">
  	<div id="chart-4" style="height: 300px; width: 100%; text-align: center; color: #999; line-height: 300px; font-size: 14px; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif;">Loading...</div><script type="text/javascript">
  new Chartkick.ColumnChart("chart-4", [{"name":"New Companies","data":{"2016-10-17":1}},{"name":"New Domains","data":{"2016-10-11":2,"2016-10-12":0,"2016-10-13":0,"2016-10-14":2,"2016-10-15":0,"2016-10-16":1,"2016-10-17":1}},{"name":"New Email Addresses","data":{"2016-10-11":3,"2016-10-12":0,"2016-10-13":0,"2016-10-14":4,"2016-10-15":0,"2016-10-16":1}},{"name":"New Plus Email Addresses","data":{"2016-10-11":2,"2016-10-12":0,"2016-10-13":0,"2016-10-14":0,"2016-10-15":0,"2016-10-16":1,"2016-10-17":0,"2016-10-18":0,"2016-10-19":0,"2016-10-20":0,"2016-10-21":0,"2016-10-22":1}},{"name":"Notes Sent","data":{"2016-10-09":3,"2016-10-10":1,"2016-10-11":2,"2016-10-12":1,"2016-10-13":1,"2016-10-14":15,"2016-10-15":1,"2016-10-16":3}}], {"library":{"title":"Usage Last 30 Days","hAxis":{"format":"MM/dd","title":"Date"},"vAxis":{"title":"Count","discrete":true,"format":"#"}}});
</script>
</div>

Here is the generated html for the line chart:

  <div class="row">
  	<div id="chart-4" style="height: 300px; width: 100%; text-align: center; color: #999; line-height: 300px; font-size: 14px; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif;">Loading...</div><script type="text/javascript">
  new Chartkick.LineChart("chart-4", [{"name":"New Companies","data":{"2016-10-17":1}},{"name":"New Domains","data":{"2016-10-11":2,"2016-10-12":0,"2016-10-13":0,"2016-10-14":2,"2016-10-15":0,"2016-10-16":1,"2016-10-17":1}},{"name":"New Email Addresses","data":{"2016-10-11":3,"2016-10-12":0,"2016-10-13":0,"2016-10-14":4,"2016-10-15":0,"2016-10-16":1}},{"name":"New Plus Email Addresses","data":{"2016-10-11":2,"2016-10-12":0,"2016-10-13":0,"2016-10-14":0,"2016-10-15":0,"2016-10-16":1,"2016-10-17":0,"2016-10-18":0,"2016-10-19":0,"2016-10-20":0,"2016-10-21":0,"2016-10-22":1}},{"name":"Notes Sent","data":{"2016-10-09":3,"2016-10-10":1,"2016-10-11":2,"2016-10-12":1,"2016-10-13":1,"2016-10-14":15,"2016-10-15":1,"2016-10-16":3}}], {"library":{"title":"Usage Last 30 Days","hAxis":{"format":"MM/dd","title":"Date"},"vAxis":{"title":"Count","discrete":true,"format":"#"}}});
</script>
</div>

The former chart's left most date is 10/17, whereas the later is 10/09, which is correct.
Please let me know if I'm misusing this chart.

**Comment by ankane** [comment]
For column charts, all values are treated as discrete/categorical (there's no concept of a time axis as there is with a line chart), so the chart will return data in the order it is passed. I'd be open to pull request to add support for this.

**Comment by portwood** [comment]
Thanks for the clarification.
