### ISSUE TITLE
formatting x-axis legend

### ISSUE THREAD

**Issue by nicholasjstock** [ankane/chartkick#30]
This is an awesome library. Thanks! 
I'm pretty new to Ruby, so this could be a horrible question. Sorry if this is the case.
I'm just curious if there is an easy way to update the x-axis labels with formatted strings? I'm building a big hourly date time chart and the x-axis labels are cluttered because its a pretty huge chart.

Any suggestions are greatly appreciated, 

Thanks!

Nick

**Comment by martinwells** [comment]
Just for reference in case anyone needs it; this is how you can format axis as a passthrough to google charts:

    = column_chart formatted, library: {title: "A Title", vAxis:{textStyle:{color:'gray', fontSize:"8pt"}}, hAxis:{textStyle:{color:'green', fontSize:"8pt"}}}, height:'200px'
