### ISSUE TITLE
Data in x-axis not showing properly.

### ISSUE THREAD

**Issue by balakarthik2011** [ankane/chartkick#300]
I have tried the sample code that you have gave in the documentation for using [hashes/arrays](https://github.com/ankane/chartkick#data), but for a column chart the result i have got is 
![screen shot 2016-10-25 at 4 52 26 pm](https://cloud.githubusercontent.com/assets/16427474/19684276/048aa484-9ad4-11e6-887c-9de2f3a1ff19.png)
Data in X-axis is not displayed properly, its showing up only ...

**Comment by ankane** [comment]
Hey @balakarthik2011, can you paste the HTML and JavaScript generated?

**Comment by encorex** [comment]
so i have the same problem, it works in normal html view but if i render (Using Rails + wicked_pdf) the same as above.

**Comment by ankane** [comment]
Hey @encorex, Chartkick isn't designed to work with wicked_pdf.
