### ISSUE TITLE
Set decimal place tooltip ( using chartjs )

### ISSUE THREAD

**Issue by encorex** [ankane/chartkick#301]
Hi there ! I have no idea how to change the decimal place of a tooltip...

using ChartJS

![screen shot 2016-10-26 at 16 28 39](https://cloud.githubusercontent.com/assets/1597756/19730150/8a52bab4-9b99-11e6-9ed9-2cc442c89481.png)

**Comment by ACPK** [comment]
@encorex - Any luck?

**Comment by encorex** [comment]
No, unfortunately not - anyone ?

**Comment by ACPK** [comment]
@encorex - Yes, I created a helper file that formatted the JSON for the ChartsController. Also, I recommend checking out Highcharts.

**Comment by encorex** [comment]
@ACPK ok nice, can you show me your helper ?

**Comment by ankane** [comment]
My suggestion would be to round the data before passing it to Chartkick.
