### ISSUE TITLE
Best method to update chart data dynamically

### ISSUE THREAD

**Issue by chriso0710** [ankane/chartkick#304]
Hi all,

I am using chartkick (chart.js) in a sinatra app and loading chart data via JSON from the server.

Which would be the recommended way to update/reload new chart data regularly, i.e. via a javascript timer? Do I have to destroy the old chart which could result in some ugly screen flashing or will the chart somehow "smoothly" adjust? What would be the approach to this?
 
Thanks and best regards
Christian

**Comment by ankane** [comment]
There's no official way to update a chart, so you'll need to experiment and see what works best.

**Comment by chriso0710** [comment]
OK, thanks, I understand. 
I assumed that this is a question several people are facing. So those findings maybe might be a good addition to the docs...

**Comment by taylorbrooks** [comment]
@chriso0710 Not sure if this is helpful, but I have a this JS function:

````javascript
function redrawChart(url){
  new Chartkick.ColumnChart(
    "chart-1",
    url,
    {stacked: true}
  )
}
````
And then I have a bunch of listeners for different form values (date range picker, group by, etc.)

**Comment by chriso0710** [comment]
Thanks @taylorbrooks. So you just create a new chart and don't bother with updating data, screen refresh etc.?

**Comment by taylorbrooks** [comment]
Yep. Here's a fuller example: https://gist.github.com/taylorbrooks/2ef2a2469959a84875b3bcac37fcd3e6

**Comment by chriso0710** [comment]
Cool, thank you!
Would you also recommend your approach when you load new data every 10 or 20 seconds? Simply starting a timer plus destroying and recreating the whole chart?

**Comment by ankane** [comment]
Chartkick now has a `refresh` option to refresh the data at regular intervals.

Also, there's an official way to update charts.

```javascript
var chart = Chartkick.charts["chart-id"];
chart.updateData(newData);
```

Let me know if I missed anything.

**Comment by chriso0710** [comment]
@ankane Great!

**Comment by KickButtowski80** [comment]
what is newData here? 
I use ruby on rails
