### ISSUE TITLE
Tooltip not shown after ajex html load

### ISSUE THREAD

**Issue by phlegx** [ankane/chartkick#305]
Hi! I use `chartkick 2.1.1` with `highcharts 5.0.2` and I have a problem with the tooltip. I load the data like this:

```
<section id="mychart">
  <%= line_chart completed_tasks_charts_path, id: 'my-linechart' %>
</section>
```

Until here, all works fine. The tooltip is shown correctly. 

I wrote a javascript code, that replaces the HTML code of the section with id `mychart` with another chart code (rendered by rails). In simple words it replaces the `line_chart` with the `area_chart` and with the new id `my-areachart`. Here the partial that goes rendered and replaced:

```
  <%= area_chart completed_tasks_charts_path, id: 'my-areachart' %>
```

**The problem**

The new rendered chart loads the data and the area chart is shown correctly. But if I go over a point with the mouse, no tooltip is shown. I have spend many hours to find a solution but without success. Any idea?

If I show the `area_chart` by default and load the `line_chart` with ajax, same problem.

## UPDATE

- The problem occurs only with more different charts on the same view. If I remove the other charts from view all works fine.
- With Google library all works fine.
- Same problem using Highcharts without Chartkick helper and js. So it is a Highcharts problem.
- It is a browser bug. Opera and Chromium works fine. Firefox not.

**Comment by taylorbrooks** [comment]
@phlegx 

> I wrote a javascript code, that replaces the HTML code of the section with id mychart with another chart code (rendered by rails).

Would you mind sharing how you do this? Just started using ChartKick and I'm stuck here.
