### ISSUE TITLE
Stacked Column ordering is very unintuitive.

### ISSUE THREAD

**Issue by mijoharas** [ankane/chartkick#306]
Hi, I've got a stacked column graph that I was trying to sort by height, and I can't find a nice reasonable solution. I find the data format for stacked column_graph very unintuitive. For instance, I would expect the following data (stolen from a stackoverflow answer):

```
data = [
  {
    name: "Fantasy & Sci Fi", 
    data: [["2010", 10], ["2020", 16], ["2030", 28]]
  },
  {
    name: "Romance", 
    data: [["2010", 24], ["2020", 22], ["2030", 19]]
  },
  {
    name: "Mystery/Crime", 
    data: [["2010", 20], ["2020", 23], ["2030", 29]]
  }
]
```

to produce a chart with columns: `["Fantasy & Sci Fi", "Romance", "Mystery/Crime"]` rather than the interior ones. 

If the data doesn't get turned inside out in the process of drawing the graph it is nice and easy to sort by column height (note, my graph is to give insight into two different class labels, not dates which have their own ordering like the example data above):

```
data.sort_by {|hash| hash[:data].values.sum }
```

however, without that I can't figure out a nice way of sorting the graph. In addition, this is only for the case where all of the labels are present in every column, which is not the case with the data I'm trying to display.

**Comment by ankane** [comment]
Hey @mijoharas, thanks for the feedback. The current format is consistent with all of the underlying charting adapters, so don't think it makes sense to change.
