### ISSUE TITLE
xAxis labels set

### ISSUE THREAD

**Issue by Peddz24** [ankane/chartkick#307]
Is there a way for setting the labels next to the xAxis in a line chart?

For example:
I have a certain question that generate answers in a certain category based on a 5 point scale, but there are only answers for the values 2 and 4. This will generate a graph with only x labels 2 and 4. It will not show 1,3 and 5. How do I fix this, because I really want 1 to 5 as xAxis labels. 

Is there also a way to have pictures/emoticons as xAxis labels or do I have to do this myself? 

Great gem by the way!

**Comment by ankane** [comment]
Hey @Peddz24, you should be able to pass all 5 values in as the data, with null values for the ones that don't have answers. Let me know if that doesn't work (with generated JS).

There's no way to do pics/emoticons as far as I know. I'm not even sure the underlying libraries support it.

**Comment by Peddz24** [comment]
`[{:name=>"Test", :data=>[[Mon, 05 Dec 2016 13:32:17 UTC +00:00, 2], [Mon, 05 Dec 2016 13:32:22 UTC +00:00, 3], [Mon, 05 Dec 2016 13:32:26 UTC +00:00, 2], [Mon, 05 Dec 2016 13:32:30 UTC +00:00, 4]]}, {:name=>"Test", :data=>[[Tue, 06 Dec 2016 15:18:42 UTC +00:00, 3]]}, {:name=>nil, :data=>[[nil, nil], [nil, nil], [nil, nil], [nil, nil], [nil, nil]]}]`

That is the code I now have for the line chart. The name test is different every time, is just for this example. I have tried to add nil object to every data array but this doens't generate the xAxis labels either. And the code above doesn't work to. 

My line chart right now:
![screen shot 2016-12-07 at 13 26 44](https://cloud.githubusercontent.com/assets/11330872/20967671/f9595406-bc80-11e6-8049-ecdc2e704137.png)

**Comment by Peddz24** [comment]
You can close this one. Have this working with Highcharts:
`<%= line_chart line_data, adapter: "highcharts", library: {
                    title: {
                        text: 'questions'
                    },
                    yAxis: {
                        labels: {
                            enabled: true,
                        },
                        min: 1, max: 5, tickInterval: 1
                    }
                } %>`
