### ISSUE TITLE
Help with chart.setOptions()

### ISSUE THREAD

**Issue by nmrichards** [ankane/chartkick#308]
Hey All,
So I'm trying to set the options to some pie charts that I have. I would like for the charts to change background color when the chart is 'selected' which is basically just setting a class in the container to 'selected'. I've tried doing
```
var chart = Chartkick.charts["chart-2"]
chart.setOptions({library: {chart: {backgroundColor: '#609928'}}}) 
```
But I'm getting a setOptions is not a function. Am I calling the setOptions() incorrectly? Is there an easier way to dynamically change the highcharts background color of my pie charts? I looked through the issues and tried finding some solutions online but to no avail. I am fairly new to programming so if it's an easy solution, I apologize. 

Any help would be greatly appreciated.
Thanks,
Nick

**Comment by ankane** [comment]
Set options was added in 2.2.1, so make sure you're on the latest version, restarted Rails server, etc. Also make sure chart is not null.

**Comment by nmrichards** [comment]
Agh, I had 2.1.1. Thanks for the quick response.

**Comment by ankane** [comment]
Np
