### ISSUE TITLE
Customise legend in pie chart

### ISSUE THREAD

**Issue by balakarthik** [ankane/chartkick#309]
I am using highcharts library,

I need to customise the legend of the pie chart but I could able to do it.

My code is

`<%= pie_chart Question.group(:user_id).count %>`

I am getting the view as 
![image](https://cloud.githubusercontent.com/assets/16471633/21038537/aebd663a-bdfc-11e6-96a8-a94f00ec40b0.png)

But I need something like 

![image](https://cloud.githubusercontent.com/assets/16471633/21038547/d3a17298-bdfc-11e6-8dec-51fed9151d7e.png)

Don't consider the data in the legend, it's just sample data which may vary in two charts.
I need to if am making any mistake.

**Comment by Peddz24** [comment]
@balakarthik You can use something like this with the library option:

    library: {
plotOptions: {
pie: {
dataLabels: {
enabled: false
},
showInLegend: true
}}}

The seconds chart is a Chart.js chart so it would look different. Just a matter of taste.

**Comment by ankane** [comment]
@Peddz24's suggestion sounds like a good one 👍
