### ISSUE TITLE
Line chart with multiple series does not interpolate x axis data

### ISSUE THREAD

**Issue by sschroed** [ankane/chartkick#310]
I have 2 series to plot on a line chart with no guarantee there are shared x axis values.  How do I get the series to be super imposed over each other?  I would expect the data on the x axis to be combined and not listed sequentially by series.

![screen shot 2016-12-12 at 3 04 02 pm](https://cloud.githubusercontent.com/assets/3743/21116712/3e3ae874-c07c-11e6-9cc2-c74b83cd5788.png)

  
Here is my sample code...

```
<%= line_chart [  {name: "2.0",   data: [[63,148],[56,101],[54,101],[29,89],[11,94]]},
                  {name: "1.0",   data: [[55,87],[31,44],[27,40],[7,11]]}
                ],
                xtitle: "Days away from launch", 
                ytitle: "Open Issues" 
%>
```

**Comment by ankane** [comment]
Hey @sschroed, Chartkick only knows 2 axis types at the moment: discrete (categorical) and datetime. It sounds like you want a numeric axis. I imagine all of the underlying libraries support this, so just a matter of someone coding this up.

**Comment by RachilovKE** [comment]
I ran into this problem too. Developers, are you going to solve it?

**Comment by ankane** [comment]
For reference, you can now use `xtype: "number"` for a numeric x-axis. Chartkick 3.0 will likely detect a numeric axis and do this automatically.
