### ISSUE TITLE
keyTypes are hardcoded to chart types

### ISSUE THREAD

**Issue by ZackMattor** [ankane/chartkick#311]
https://github.com/ankane/chartkick/blob/2f1a492133f15a40f81a8110ad3dd4fc979b1069/app/assets/javascripts/chartkick.js#L1504-L1537

I'm trying to be able to have chartkick correctly parse my dates, and it seems like the keyTypes are hardcoded per chart type? Is this intentional?

```javascript
  function processColumnData(chart) {
    chart.data = processSeries(chart.data, chart.options, "string");
    renderChart("ColumnChart", chart);
  }
```

**Comment by ankane** [comment]
Yes, Chartkick doesn't support dates/times for column charts. You'll want to use `strftime` or similar to convert the dates to the labels you want before passing them to Chartkick.
