### ISSUE TITLE
Scatter chart does not allow two points with same x-axis value

### ISSUE THREAD

**Issue by mvgaaron** [ankane/chartkick#312]
I'm attempting to use scatter_chart with Google Charts. My ruby code returns 7 plot points; however, only 5 points are displayed on the chart.

First I limit my set of evaluations to those in scope:
```
@evaluations = Evaluation.where(:strategy_id => 1)
```
Note 7 records are in scope:
```
@evaluations.pluck(:id)
=> [2, 3, 4, 5, 6, 7, 1]
```
I then pluck two values from each of the 7 records:
```
@evaluations.pluck(:maturity, :value)
=> [[0, -5], [-10, -10], [5, 10], [-5, 5], [10, -5], [-10, 10], [-5, 10]]
```
I then plot those records on a scatter chart, but only 5 records are shown:
```
<%= scatter_chart @evaluation_values, 
      xtitle: "Maturity", 
      ytitle: "Importance", 
      library: {backgroundColor: "#f5f5f5", 
        hAxis: {gridlines: {color: '#333', count: 2}, viewWindow: {min: -10, max: 10}, textPosition: 'none'}, 
        vAxis: {gridlines: {color: '#333', count: 2}, viewWindow: {min: -10, max: 10}, textPosition: 'none'},
        pointSize: 12,
        tooltip: {trigger: 'none'}
      } %>
```
If I take the variables out of the mix, and pass the plot point values, still only 5 records are shown:
```
<%= scatter_chart [[0, -5], [-10, -10], [5, 10], [-5, 5], [10, -5], [-10, 10], [-5, 10]], 
      xtitle: "Maturity", 
      ytitle: "Importance", 
      library: {backgroundColor: "#f5f5f5", 
        hAxis: {gridlines: {color: '#333', count: 2}, viewWindow: {min: -10, max: 10}, textPosition: 'none'}, 
        vAxis: {gridlines: {color: '#333', count: 2}, viewWindow: {min: -10, max: 10}, textPosition: 'none'},
        pointSize: 12,
        tooltip: {trigger: 'none'}
      } %>
```
Note the last two pairs of values contain an x-axis value repeated from a previous pair. If I manually modify the x-axis values of the last two pairs, giving them unique values, all 7 plot points appear on the graph:
```
<%= scatter_chart [[0, -5], [-10, -10], [5, 10], [-5, 5], [10, -5], [-9, 10], [-6, 10]], 
      xtitle: "Maturity", 
      ytitle: "Importance", 
      library: {backgroundColor: "#f5f5f5", 
        hAxis: {gridlines: {color: '#333', count: 2}, viewWindow: {min: -10, max: 10}, textPosition: 'none'}, 
        vAxis: {gridlines: {color: '#333', count: 2}, viewWindow: {min: -10, max: 10}, textPosition: 'none'},
        pointSize: 12,
        tooltip: {trigger: 'none'}
      } %>
```
The last example is my expected behavior for a scatter chart. Note the example on Google Charts own page for this type of visualization includes repeated x-axis values:
https://developers.google.com/chart/interactive/docs/gallery/scatterchart

I appreciate your help.

**Comment by ankane** [comment]
Thanks for the report @mvgaaron 👍  This is fixed on master.
