### ISSUE TITLE
Increase space between chart and legend

### ISSUE THREAD

**Issue by Aravind6** [ankane/chartkick#315]
I am using chartkick gem with googlecharts. I need to add space between chart and legend text. [](http://stackoverflow.com/questions/41295169/how-to-increase-space-between-chart-and-legend-googlecharts) Any one help me?

**Comment by Peddz24** [comment]
It would say look in the Google Chart API and then add this through the library option:

> You can pass options directly to the charting library with:

`<%= line_chart data, library: {backgroundColor: "#eee"} %>
See the documentation for Chart.js, Google Charts, and Highcharts for more info.`

> See the documentation for Chart.js, Google Charts, and Highcharts for more info.

**Comment by ankane** [comment]
@Peddz24 suggestion sounds like a great one 👍
