### ISSUE TITLE
Custom dot size / Remove dot

### ISSUE THREAD

**Issue by StephaneJuban** [ankane/chartkick#316]
Is it possible to customise the dot size of a line chart ? Or to remove it at all ?

cf. [Post from Chart.js](https://github.com/chartjs/Chart.js/issues/2107)

Even if I put the correct option in my initializer, it is not working even if I see it in the option of the source code generated for my chart.

```
Chartkick.options = {
  elements:{point:{radius: 0}},
  discrete: true
}
```

Code generated :

> new Chartkick.LineChart("chart-1", [___MY_DATA___], {"elements":{"point":{"radius":0}},"discrete":true});

**Comment by ankane** [comment]
You can try to use the `library` option for this.
