### ISSUE TITLE
Custom color with transparency for area_chart

### ISSUE THREAD

**Issue by activestylus** [ankane/chartkick#317]
Specifying `colors: ["pink","#999"]` makes the area chart fill completely opaque.

Was hoping that it would mimic the default style where the filled portion is transparent.

![image](https://cloud.githubusercontent.com/assets/285/21541466/deac9e50-cdb6-11e6-8423-928b4893bcd3.png)

**Comment by ankane** [comment]
You'll need to use a hex color for opacity to work.

**Comment by activestylus** [comment]
That did the trick. Cheers
