### ISSUE TITLE
Can't get hightcharts library options to work

### ISSUE THREAD

**Issue by laetitiamassa** [ankane/chartkick#318]
Using Chartkick with Highcharts (5.0.6),
I can't get the library to work, whether in chartkick initializer or in my views.

Here is my syntax in my view: 
<%= line_chart  [
name: 'bla bla',
data: graph.data_type.where.not("#{graph.data}" => nil).group(:date).sum("#{graph.data}"),
library: {chart: {backgroundColor: "#555"}}
] %>

I have highcharts inserted in my application.js and in my application.html.erb.
Appart from the library options, everything works properly with highcharts.
I just can't figure out how to customize any of it.

Is there something I'm missing?

NB : i've updated my code sample

**Comment by ankane** [comment]
See #268.

**Comment by laetitiamassa** [comment]
I had already (as well as the issue 260), but don't see the answer to my question there. :/

**Comment by laetitiamassa** [comment]
Now it works!
It seems that the square brackets prevented it to work somehow...
