### ISSUE TITLE
Ajax Load Chart

### ISSUE THREAD

**Issue by DemisBand** [ankane/chartkick#321]
Hi,
I can not display a graph when I load a div in ajax
I just get: Loading ...

Is there a solution?

thank you,
Thomas.

**Comment by DemisBand** [comment]
Ok, I solved with :  "id: SecureRandom.hex(7)"

**Comment by kissu** [comment]
Hm, I got the same error today.
I have a `defer: true` on the initial html page load but I forgot to remove it from the AJAX partial... For future readers, don't be as baka as I did. :joy: :scream:
