### ISSUE TITLE
Border Colors for X and Y Axis

### ISSUE THREAD

**Issue by activestylus** [ankane/chartkick#322]
I have a chart sitting on a black background and as such the lines for x and y axis are not visible.

How do I change the border width/color for these?

**Comment by ankane** [comment]
You'll need to try the `library` option. Chartkick doesn't provide an official option for these.

**Comment by activestylus** [comment]
Seems I can't hook into the parameters I need. A sample:

```ruby
area_chart @visits.count, library: { title: {test: 'Hello World'}, xAxis: { gridLineColor:"#ff0000", lineWidth: 1, lineColor: "#ff0000" } }
```

I'm trying to get these options from highchart: http://api.highcharts.com/highcharts/xAxis.title

Am I missing a namespace or something?

**Comment by activestylus** [comment]
Update: I tried removing highcharts and using Chart.js instead. Same issue. I cant access any of the options via the library object
