### ISSUE TITLE
Charts.js labels truncated to unreadable sizes on mobile

### ISSUE THREAD

**Issue by stephen-puiszis** [ankane/chartkick#323]
Hey @ankane, thanks for the great gem. I'm using`charts.js` for their responsive features and came across a weird bug on mobile devices. I originally saw this on chartkick `2.2.1`, upgraded and am also seeing it on `2.2.2`. 

### Expectation & Bug Description 
I'm creating a time-series bar chart. On initial page load at a desktop screen width, everything looks fine as expected and when re-sizing the browser in chrome to a mobile width, the chart scales down appropriately, as expected. 

**Desktop**
<img width="539" alt="screen shot 2017-01-16 at 11 43 47 pm" src="https://cloud.githubusercontent.com/assets/1960738/22009600/f07c1e02-dc49-11e6-8257-2f69692ae8be.png">

However, on initial page load at a mobile width using iPhone 6S 375x667, all of the xAxis labels are truncated to an unreadable height. 

**iPhone 6s**
<img width="302" alt="screen shot 2017-01-16 at 11 43 24 pm" src="https://cloud.githubusercontent.com/assets/1960738/22009698/72c32d7e-dc4a-11e6-9314-ab69753ee6af.png">

#### View
```haml
  = column_chart @goal_report.chart_data, @goal_report.chart_library_options
```

#### Data (truncated for brevity) 

```
[["Jan 15", 0],
 ["Jan 16", 2],
 ["Jan 17", 0],]
```

#### Wrapper Object
```ruby
def chart_library_options
    {
      library: {
        scales: {
          xAxes: [{
            ticks: {
              autoSkip: true,
              autoSkipPadding: 10,
            }
          }],
          yAxes: [{
            ticks: { fixedStepSize: 1 },
          }],
        },
      }
    }
  end
```
### Questions
I did some digging and I think I found the culprit in the `setLabelSize` function. I don't fully understand what's going on but from my local test of changing the if condition `maxLabelSize - 2` to `maxLabelSize + 10` increased the label characters at mobile widths. 
https://github.com/ankane/chartkick/blob/master/app/assets/javascripts/chartkick.js#L1099

**How should I go about fixing this?**

**Test**
```
if (value.length > maxLabelSize) {
   return value.substring(0, maxLabelSize + 10) + "...";
  } else {
   return value;
}
```

**Before: iPhone 6S 375x667**
<img width="302" alt="screen shot 2017-01-16 at 11 43 24 pm" src="https://cloud.githubusercontent.com/assets/1960738/22009227/30b86294-dc47-11e6-8fd5-ab635a7a38af.png">

**After: iPhone 6S 375x667**
<img width="291" alt="screen shot 2017-01-16 at 11 52 30 pm" src="https://cloud.githubusercontent.com/assets/1960738/22009221/290e92f2-dc47-11e6-8d01-de4cfa43cc79.png">

**Comment by ankane** [comment]
Hey @stephen-puiszis, thanks for the detailed report. Chartkick isn't taking `autoSkip: true` into account when it's deciding how many labels it needs to plot. One option would be to use `maxLabelSize` (which is 25) if `autoSkip: true` is specified. Also, while looking at that code, if the user has `ticks.callback` set, Chartkick shouldn't override it.

**Comment by ankane** [comment]
Fixed in https://github.com/ankane/chartkick.js/commit/8e0151c124755bd263f6ebb614b729269d221dfb
