### ISSUE TITLE
How to approach Chart.js custom solutions using Chartkick?

### ISSUE THREAD

**Issue by patakijv** [ankane/chartkick#324]
I plan to work on implementing a scatter plot using the Chart.js options with Chartkick in a rails app with some specific customizations where I've found solutions for the Chart.js portion online but would like to approach this from Chartkick perspective.

For example: I want to add vertical and horizontal lines at specific points in the plot and I found these example solutions for Chart.js: http://stackoverflow.com/a/30323431/56082 (vertical) and http://stackoverflow.com/a/31092938/56082 (horizontal)

The other thing I need to add is the ability to shade/color a portion of the plot's background from the vertical and horizontal line over/under differently than the rest of the background. I haven't yet found an example solution for how to do it in Chart.js but when I do, like the above line drawing, is there an example of how to make these changes in a chartkick-like fashion so I can leverage the gem's abilities and ruby code/configuration style?

The goal of what I am shooting for is something like this
![image](https://cloud.githubusercontent.com/assets/110831/22188727/b3069124-e0cc-11e6-96d6-2a0d4e816062.png)

**Comment by ankane** [comment]
Hey @patakijv, you can try using the `library` option, but for highly customized charts, it's often easier to use the charting library directly (without Chartkick).

**Comment by patakijv** [comment]
Can you elaborate on how the 'library' option would be used for the example I referred to? It's not clear.

On Jan 22, 2017, at 6:35 PM, Andrew Kane <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @patakijv<https://github.com/patakijv>, you can try using the library option, but for highly customized charts, it's often easier to use the charting library directly (without Chartkick).

-
