### ISSUE TITLE
Removing padding to render chart in full area.

### ISSUE THREAD

**Issue by vijay-bigscal** [ankane/chartkick#325]
@ankane  That's nice chart tool.
Can you please describe how to remove spacing from all 4 directions, so chart render in full space?
I am attaching screenshot.

![padding issue](https://cloud.githubusercontent.com/assets/13792591/22370188/27d53338-e4b6-11e6-91e6-35f640b05165.PNG)

I am using Ruby. This is code :

<%= line_chart @activity, library: { curveType: "none", :hAxis=>{:format=>'dd MMM'}, pointSize: 3 }  %>

Please reply asap.

**Comment by ankane** [comment]
Hey @vijay-bigscal, use the library option. You'll need to look up how.
