### ISSUE TITLE
Question or Bug: The date in chart might not sort by order.

### ISSUE THREAD

**Issue by fanjieqi** [ankane/chartkick#327]
Excuse me, the date in chart might not sort by order when I use the line_chart and area_chart.

Here is my example:
```
example.html.haml
- chart = [{:name=>"dotinappat1i", :data=>{"2017-01-11"=>13.4, "2017-01-19"=>26.8}}, {:name=>"dotinappat3i", :data=>{"2017-01-17"=>13.4, "2017-01-18"=>67.0}}]
= line_chart chart, stacked: true, discrete: true

```

It would generate the chart:
![chartkick_bug_chart](https://cloud.githubusercontent.com/assets/5510776/22618083/20e51bba-eb0f-11e6-962a-5e60241d60ff.png)

As you see, the 2017-01-17 and 2017-01-18 are on the right of 2017-01-19.
Is there anything I did wrong?

And I use the version-2.2.1.

Sorry for my poor English.

**Comment by ankane** [comment]
Hey @fanjieqi, this is due to the `discrete: true` option. Data is rendered in the order it is passed to Chartkick.

**Comment by fanjieqi** [comment]
Thank you~
