### ISSUE TITLE
Google Charts Histogram support

### ISSUE THREAD

**Issue by juampi** [ankane/chartkick#328]
Are there plans to support [the Histogram chart from Google Charts](https://developers.google.com/chart/interactive/docs/gallery/histogram)?

I could help implement it if needed.

**Comment by ankane** [comment]
Hey @juampi, no plans to support other chart types at the moment.

**Comment by johnmcconnell** [comment]
Just bumping this for visilibility. I would like to see a histogram chart

**Comment by RailsCod3rFuture** [comment]
Still no support for histograms?

**Comment by joshm30** [comment]
Bump for histogram support
