### ISSUE TITLE
Animation option ignored in Rails 5

### ISSUE THREAD

**Issue by michaelneu** [ankane/chartkick#329]
It seems Chartkick somehow ignores the `animation` option for its charts. I'm using Rails 5, and wanted to create a line chart (with the Chart.js adapter) using 

```erb
<%= line_chart @values %>
```

When I checked the animation option of the underlaying Chart.js object, it's `false` (as mentioned in #279), even after I configured the `animation` options to be passed in an initializer like this:

```ruby
Chartkick.options = {
  animation: {
    duration: 200,
    easing: "linear"
  }
}
```

The above configuration yields something similar (depending on `@values`) as you can see below. I've formatted it and added the `animation` option so you can paste it into the devtools console. 

```javascript
new Chartkick.LineChart("chart-1", 
  [
    [0, 0],
    [1, 1],
    [2, 2]
  ],
  {
    "animation": {
      "duration": 200,
      "easing": "linear"
    }
  }
).chart.options.animation
```

I tried resetting the `animation` option on page load, however it seems it resets everytime I update the chart using `updateData`. 

Is this Chartkick's intended behaviour (I'm not sure, as it defaults to `animation: false`) or could it be a bug?

**Comment by ankane** [comment]
Hey @michaelneu, you need to put the code above inside the library option. It's being ignored as is.

**Comment by michaelneu** [comment]
Works as intended, thanks @ankane. I guess I misunderstood the docs, as one can configure the chart directly (e.g. with the `legend` option) without using the `library` option. 

Thanks for your quick response!

**Comment by ankane** [comment]
Chartkick provides convenience options for some customizations, but you have to use the library option for all others.

**Comment by kinjalchotaliya** [comment]
Hey @michaelneu if you can to switch to adapter highcharts you can set animation by following code:
`<%= line_chart [{name: "Total Users",data: data,lineWidth: 4,animation: {duration: 5000}}], colors: ['#3ac9d6'],adapter: "highcharts"%>`
