### ISSUE TITLE
setup json endpoint method advice

### ISSUE THREAD

**Issue by seanpaulkelley** [ankane/chartkick#330]
How do I add 'name' on my JSON implementation and also how to add second data line to chart using JSON.

I have this non-json approach working in my view, which displays air and soil in legend:
`= line_chart [{name: "soil", data: @soil_temperatures.map{|t| [t.created_at, t.temperature] }},
{name: "air", data: @air_temperatures.map{|t| [t.created_at, t.temperature] }}]`

I cannot get page to load without timeout in production so I want to implement the JSON end point recommendation with both data lines on same chart with legend.
in my view I use:
`= line_chart soil_chart_path, xtitle: "Time", ytitle: "Temp" `
which works for one data line and does not show legend

My json endpoint setup so far:
`  def soil_chart
    if params[:start_time] and params[:end_time]
      @temperatures = Temperature.range.where(:temp_type => 'soil')
    else
      @temperatures = Temperature.recent.where(:temp_type => 'soil') 
    end 
    render json: @temperatures.map{|t| [ t.created_at, t.temperature]}
  end`

I tried adding name: 'soil to my view line but it did not work
`= line_chart soil_chart_path, name: "soil", xtitle: "Time", ytitle: "Temp" `

As far as multiple series, I do not understand how I would use 
chart_json in my situation.

**Comment by ankane** [comment]
Hey @seanpaulkelley, use the same format as the inline version:

```ruby
render json: [{name: "soil", data: @soil_temperatures.map{|t| [t.created_at, t.temperature] }}, {name: "air", data: @air_temperatures.map{|t| [t.created_at, t.temperature] }}]
```

**Comment by seanpaulkelley** [comment]
thanks- works great!
