### ISSUE TITLE
How to correctly pass library options to Chart.js

### ISSUE THREAD

**Issue by bovender** [ankane/chartkick#331]
Hi, I'm having trouble passing `library` options to Chart.js.

My site has a dark gray background and I need to define the chart colors so they look alright against this dark background.

Here's an example:

    = line_chart fetch_my_data_from_rails_path,
        title: 'my chart title', ytitle: 'unit',
        library: { fontSize: "24" }

Of course I really want to change the color, not the font size. But no matter what I try, none of the options that I pass in the `library` hash are respected.

Is it a bug or am I missing something?

chartkick 2.2.2

**Comment by ankane** [comment]
Hey @bovender, see https://github.com/ankane/chartkick/issues/268.
