### ISSUE TITLE
Google Charts - Where to insert "mapsApiKey"

### ISSUE THREAD

**Issue by sebastianbinder** [ankane/chartkick#333]
When using `geo_chart` with city names, following error shows up in JS console:
`Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error`
This key is needed according to https://developers.google.com/chart/interactive/docs/basic_load_libs#load-settings.
I have an api key, but I simply don't know where to insert this key to make it work.
Thanks for your help!

**Comment by ankane** [comment]
Hey @sebastianbinder, I just released a new version that allows you to do:

```html
<script>
  Chartkick.configure({mapsApiKey: "secret"})
</script>
```

**Comment by sebastianbinder** [comment]
Great, I'll have a try later. Thank you!
