### ISSUE TITLE
Allow to initialize without embedded script tag

### ISSUE THREAD

**Issue by patleb** [ankane/chartkick#336]
It would be nice to have the option to initialize the pluggin without an embedded script tag. The implementation I use looks like [this](https://github.com/patleb/chartkick/commit/e6836901ffedd0012b237ba217350735deff2ca6).

The idea is that you could select the div with the class `js_chartkick_config` and do whatever you need/want afterward.

**Comment by ankane** [comment]
Hey @patleb, thanks for the idea. What do you see as the advantages of this approach vs the current one?

**Comment by patleb** [comment]
Hi @ankane, the only advantage is if your code base doesn't allow (as a philosophy/style guide) a script tag within the body. Also, we use a fork of pjax which ignores script tags within the body.
