### ISSUE TITLE
Line Chart how to remove "connection lines"

### ISSUE THREAD

**Issue by lut** [ankane/chartkick#337]
Hi ankane! Great library, I love it. 

I am using line_chart to represent temperature values over time. Values are recorded every minute, however I dont have values for all minutes, this creates "weird columns", is there a way to remove those line? See images below.

Now:
![screen shot 2017-03-09 at 23 41 59](https://cloud.githubusercontent.com/assets/3229948/23783657/c6623c12-0522-11e7-84e2-9a5aa7f0ceba.png)

Desired:
![desired](https://cloud.githubusercontent.com/assets/3229948/23783743/6bdbbfc4-0523-11e7-8e33-3c01de250c69.png)

**Comment by ankane** [comment]
Hey @lut, Chartkick doesn't provide a way to do this. You can research the `library` option to see if that can accomplish what you want, but I don't know of the top of my head.
