### ISSUE TITLE
Grouped Stacks – Column Chart

### ISSUE THREAD

**Issue by Nerian** [ankane/chartkick#338]
Hi,

How can I group multiple datasets into one group? In Charts I would use the `stack` option in the dataset and it will stack the datasets in one bar. But in ChartKick the `stack` option is ignored.  

```
new Chart('my-chart', {
          type: 'bar',
          data: {
              labels: ["T1", "T2", "T3"],
              datasets: [
                {
                  backgroundColor: chartColors.yellow,
                  label: 'A1',
                  stack: 'stack1',
                  data: [10, 20, 30]
                },
                {
                  backgroundColor: chartColors.green,
                  label: 'A2',
                  stack: 'stack1',
                  data: [20, 30, 50]
                },
                {
                  backgroundColor: chartColors.red,
                  label: 'B1',
                  stack: 'stack2',
                  data: [12, 19, 40]
                }
              ]
          }
      });
```

How can I replicate this in ChartKick?

This is what I tried:

```
= column_chart([{ name: 'A1', stack: 'stack1', data: [['t1', 1],['t2',2],['t3',3],['t4', 4]] }, { name: 'A2', stack: 'stack1', data: [['t1', 1],['t2',2],['t3',3],['t4', 4]] }, { name: 'B1', stack: 'stack2', data: [['t1', 1],['t2',2],['t3',3],['t4', 4]] }], stacked: true)
```

<img width="1101" alt="captura de pantalla 2017-03-10 a las 18 16 45" src="https://cloud.githubusercontent.com/assets/259568/23805334/c154dda6-05bd-11e7-9265-b4413b1e6ac6.png">

I expected that for each T, there would be two columns, one for the A1 and A2 datasets, and another one for the B1 datatset.

**Comment by ankane** [comment]
Hey @Nerian, if you include the master version of Chartkick.js in `app/assets/chartkick.js`, this should work. https://raw.githubusercontent.com/ankane/chartkick.js/master/chartkick.js

**Comment by Nerian** [comment]
It works. Thanks!
