### ISSUE TITLE
Question: How to create a highcharts multi-line report with two yAxis?

### ISSUE THREAD

**Issue by nirtzur** [ankane/chartkick#340]
Hi,

I am unable to create a two y-axis report using highcharts with multi-lines. I am trying to associate one of the lines with the second y-axis. However, I can't find a way to do that. Here is a sample code I'm using:

    column_chart( 
      [ { name: "A", data: {1 => 10, 2 => 20, 3 => 30, 4 => 40} },
        { name: "b", data: {1 => 5000, 3 => 6000, 5 => 7000, 1000 => 8000} } ],
        title: "some title",
        legend: "bottom",
        stacked: true,
        library: {
          series: [ { yAxis: 1 }, { yAxis: 2 } ],
          yAxis: [{ title: { text: 'data1' } }, { title: { text: 'Another title' }, opposite: true }],
          xAxis: { title: { text: 'some text' } }
        }
    )
 
I was able to create this easily with google charts.
Please assist.

Thanks
Nir

**Comment by ankane** [comment]
Hey @nirtzur, this isn't supported yet, but definitely something I'd like help with: https://github.com/ankane/chartkick.js/issues/79
