### ISSUE TITLE
Library options on initialization

### ISSUE THREAD

**Issue by laynetrain** [ankane/chartkick#341]
Looking into the source, it appears that Chartkick doesn’t support library options on initialization.

Chartkick chart upon initialization:
http://i.imgur.com/Zo5O4Q6.png

Same page refreshed:
http://i.imgur.com/X0Yayub.png

I tried passing the options to the chart manually at the point of initialization without success `<%= line_chart data, library: hash_of_library_options %>`

rails -v 5.0.1

**Comment by ankane** [comment]
Hey @laynetrain, Chartkick certainly supports the `library` option on initialization. I'd double check you're using it correctly.
