### ISSUE TITLE
How to pass params to geo_chart with displayMode: "markers" ?

### ISSUE THREAD

**Issue by MarkOsipenko** [ankane/chartkick#344]
Hi! How I can display posts on map with markers ?
For example I have geo chart

`      geo_chart Post.group(:state_name).count, `
`  library:` {
   `       region: 'US',`
`          resolution: 'provinces',`
`        },`
 

and it's work

But I want know how to pass params to geo_chart method for display map with markers.
My `Post` model has `city`, `latitude`, `longitude`, `country`, and `state_name` 
I also add `displayMode: 'markers'`, to `library`  and experimented with options and params but unsuccessfully.
I reed the Google chart documentation and find addColumns/addRows methods but it don't help.

**Comment by ankane** [comment]
Hey @MarkOsipenko, you'll need to use Google Charts directly for customizations that require more columns.

**Comment by MarkOsipenko** [comment]
@ankane thank you.
