### ISSUE TITLE
Chartkick.charts.redraw... changes x axis on linechart 

### ISSUE THREAD

**Issue by gcrofils** [ankane/chartkick#345]
We have a line chart like this :
`=  line_chart charts_website_visits_path([params])....`

Json looks like this : 

`curl 'http://192.168.1.133:3000/ws/charts/website_visits....`

`[{"name":"Visits","type":"area","data":{"March 20, 2017":9,"March 21, 2017":11,"March 22, 2017":9,"March 23, 2017":8,"March 24, 2017":12,"March 25, 2017":10,"March 26, 2017":9}},{"name":"Views","type":"spline","data":{"March 20, 2017":17,"March 21, 2017":9,"March 22, 2017":14,"March 23, 2017":11,"March 24, 2017":14,"March 25, 2017":20,"March 26, 2017":9}}]`

it gives a beautiful chart like this : 

<img width="865" alt="capture d ecran 2017-03-26 a 22 59 49" src="https://cloud.githubusercontent.com/assets/93443/24332499/37a7f0b0-127a-11e7-8dde-f265a7dec3a1.png">

But...

when we redraw the chart, there is a weird behavior

`Chartkick.charts['[chart-id]'].redraw()`

The x axis labels changes

first time : 

<img width="875" alt="capture d ecran 2017-03-26 a 23 00 01" src="https://cloud.githubusercontent.com/assets/93443/24332500/3f3cb932-127a-11e7-84a2-71c9f0f5ddef.png">

redraw again...

<img width="886" alt="capture d ecran 2017-03-26 a 23 00 10" src="https://cloud.githubusercontent.com/assets/93443/24332505/459545ce-127a-11e7-82e3-6b9d472993a7.png">

redraw again...

<img width="882" alt="capture d ecran 2017-03-26 a 23 00 17" src="https://cloud.githubusercontent.com/assets/93443/24332506/4c117c2e-127a-11e7-8d89-443fb75d3561.png">

redraw again

<img width="855" alt="capture d ecran 2017-03-26 a 23 18 16" src="https://cloud.githubusercontent.com/assets/93443/24332530/93561ae0-127a-11e7-997e-90bd8f2e568b.png">

Redraw works perfectly with `column_chart`

<img width="856" alt="capture d ecran 2017-03-26 a 23 17 36" src="https://cloud.githubusercontent.com/assets/93443/24332533/990001cc-127a-11e7-8a2f-270542585218.png">

Any hint ?

**Comment by ankane** [comment]
Hey @gcrofils, fixed with this commit: https://github.com/ankane/chartkick.js/commit/333212ede7c35d0dd5e4ff7de812c0ff0c125984

You can copy the latest `chartkick.js` into `app/assets/javascripts` to get the fix immediately.

**Comment by gcrofils** [comment]
Thanks @ankane ! it works like a charm.

I had also found out previous version worked with another date format like `"%d/%m"` for instance.
