### ISSUE TITLE
need Help with multiple series line chart

### ISSUE THREAD

**Issue by hundrog** [ankane/chartkick#346]
Hi all, I'm trying to show some data from different sources, I have my line chart working fine, but sometimes data arrives 1 second later and the lines don't show continuously

![image](https://cloud.githubusercontent.com/assets/17800468/24470578/98252dfa-147c-11e7-9596-3349ccdd8eb8.png)

here is my code
```ruby
<%= line_chart @messages.pluck(:source_id).uniq.map{|i| {
		name: Source.find(i).serial_number,
		data: @messages.where(source_id: i).last(30).pluck(:created_at, :some_data)
		} } %>
```
I was trying to use groupdate but the chart don't show, I'm doing it like this:
```ruby
<%= line_chart @messages.group_by_minute(:created_at).uniq.map{|i| {
		name: Source.find(i.source_id).serial_number,
		data: @messages.where(source_id: i.source_id).last(30).
		pluck(:created_at, :some_data)
		} } %>
```
And only show this:

![image](https://cloud.githubusercontent.com/assets/17800468/24470606/c2ee9206-147c-11e7-9ac2-2118f68f8185.png)

Some help or references please

**Comment by ankane** [comment]
Hey @hundrog, try looking up the spanGaps option of Chart.js.

**Comment by hundrog** [comment]
@ankane thank you, this was so easy, ps love your work

**Comment by ankane** [comment]
Thanks, glad it worked.
