### ISSUE TITLE
Chartkick is not defined error with Rails 5.0.2 in production only

### ISSUE THREAD

**Issue by jlefley** [ankane/chartkick#347]
I integrated chartkick with my Rails application by following the instructions on the home page. I added the gem to the Gemfile and modified my application.js to look like this:

```
//= require jquery
//= require jquery_ujs
//= require bootstrap-sprockets
//= require Chart.bundle
//= require chartkick
//= require turbolinks
//= require_tree .
```

In development on my local machine, everything works great. I deployed to the production server and the charts do not appear. I just see the "Loading..." text where the chart should be and I see "Chartkick is not defined" in the JavaScript console. I checked the compiled application.js and it looks like the chartkick code is in there but the Chatkick property does indeed not exist on window if I try to access it at the console.

I finally resolved the issue by removing the require statements from application.js, changing the include tag to read ```<%= javascript_include_tag 'application', 'Chart.bundle', 'chartkick', 'data-turbolinks-track': 'reload' %>``` in layouts/application.html.erb, and adding ```Rails.application.config.assets.precompile += %w( Chart.bundle )``` to config/initializers/assets.rb. I'm not sure why the original configuration didn't work but with these changes everything works as expected.

Any ideas what might be going on?

**Comment by ankane** [comment]
Hey @jlefley, I don't have any ideas. If the compiled `application.js` includes Chartkick and it's included on the page, it should work.

**Comment by jlefley** [comment]
OK yeah I'm not sure what the problem is either. Since I got it working as described, we can probably close this issue for now. I thought it was worth mentioning in case someone else has the same problem

**Comment by crivotz** [comment]
Similar problem for me

**Comment by gabsinator** [comment]
Check your chartkick gem version. (gem list --local |grep chart)

Had this issue and noticed that if I (as instructed) just put gem 'chartkick' in my Gemfile it will install versjon 1.4.0. 

Change it to gem 'chartkick', '~> 2.2.0' and run bundle install and it should grab the right version and work.
