### ISSUE TITLE
Chartkick.charts returning an empty object

### ISSUE THREAD

**Issue by dugjason** [ankane/chartkick#349]
When I try calling `Chartkick.charts` or `Chartkick.charts.["chart-1"].getChartObject()` from the console, I receive an empty object or `Cannot read property 'getChartObject' of undefined` response. The Google charts are loaded on my page; I'm wondering if there is anything obvious I'm missing, or any steps I need to take before I can access these charts ?
I'm using Ruby 2.4, Rails 5.0 and Chartkick 2.2.3

**Comment by ankane** [comment]
The only thing that comes to mind is you could be using an old version of Chartkick.js before the `charts` method was added.

**Comment by dugjason** [comment]
Fixed it! My `<%= javascript_include_tag "application" %>` was in the page footer
