### ISSUE TITLE
Passing an array of dates for axis ticks

### ISSUE THREAD

**Issue by alexanderburley** [ankane/chartkick#350]
Hi, I need my line graph to display the ticks of the horizontal axis as the months between June of 2016 and June of 2017. 

Is there anyway to accomplish this for a continuous graph? I am presuming the Google Charts doesn't parse strings into the Date object as I'm getting an '__a.getTime_ is not a function_' error where the graph should appear.

Am I missing something? 

Thanks

`hAxis: {format: 'MMM', ticks:["2016-06-01 00:00:00 UTC", "2016-07-01 00:00:00 UTC", "2016-08-01 00:00:00 UTC",
          "2016-09-01 00:00:00 UTC", "2016-10-01 00:00:00 UTC" "2016-11-01 00:00:00 UTC" "2016-12-01 00:00:00 UTC",
            "2017-01-01 00:00:00 UTC", "2017-02-01 00:00:00 UTC", "2017-03-01 00:00:00 UTC", "2017-04-01 00:00:00 UTC"
              "2017-05-01 00:00:00 UTC"]},
        vAxis: {title: 'Tuition (mins)', ticks: [120,240,360,480,600,720,840,960,1080]}`

**Comment by ankane** [comment]
Hey @alexanderburley, as you mentioned, sounds like it's expecting a `Date` object. Unfortunately, you can't pass `Date` objects through JSON, so you'll likely need to either:

1. Set the library options separately in JavaScript with the [Chartkick JavaScript API](https://github.com/ankane/chartkick#javascript-api) - `setOptions` method - OR
2. Use Google Charts directly

**Comment by alexanderburley** [comment]
Thanks for advice. Couldn't get it to work with setOptions so just using the charts directly now.
