### ISSUE TITLE
Set the xAxis range

### ISSUE THREAD

**Issue by nizovtsevnv** [ankane/chartkick#354]
Hello, I need to draw multiple month lines day by day, something like described on http://www.highcharts.com/demo/spline-irregular-time

Now I use next data: 
new Chartkick.LineChart("chart-1", [{"name":"March","data":{"01":1674,"02":1719,"03":1628,"04":1756,"05":1815,"06":1516,"07":1605,"08":1726,"09":1487,"10":1396,"11":1452,"12":1518,"13":1260,"14":1308,"15":1284,"16":1239,"17":1263,"18":1606,"19":1685,"20":1382,"21":1183,"22":1587,"23":1491,"24":1433,"25":1455,"26":1595,"27":1468,"28":1451,"29":1463,"30":1315,"31":1383}},{"name":"April","data":{"01":1518,"02":1635,"03":1455,"04":1440,"05":1575,"06":1578,"07":1565,"08":1701,"09":1632,"10":1563,"11":1522,"12":1462,"13":1558,"14":1520,"15":1717,"16":1677,"17":1743,"18":1486,"19":1118,"20":286}}], {});

But in this case I have broken chart lines with xAxis starts from 10, 11,...31 and after that 01, 02...09.
Could you advise how to draw these graphics correctly?

**Comment by ankane** [comment]
Hey @nizovtsevnv, you'll need to use an array for `data` instead of an object for the order to be preserved.

http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

**Comment by ankane** [comment]
You can also try:

```ruby
line_chart series, xtype: "number"
```

**Comment by nizovtsevnv** [comment]
Thank you very much, xtype: "number" really helps me!
