### ISSUE TITLE
Datepicker/Range Selector - Possibility to choose dates to show data

### ISSUE THREAD

**Issue by Rubioli** [ankane/chartkick#358]
Great `gem`.

I am using `ahoy gem` to track visits & `chartkick gem` to show the data to users.

As of today, my chart only displays last 7 days & I do it by `group_by_day(:started_at, last: 7)`. 
How can I add `datepicker` so users can select two dates and display data between selected/giving dates?

Thanks in advanced!

**Comment by Iqlaas** [comment]
Hi @Rubioli , hope this message finds you well.

Did you manage to solve this ? I also need to display data between 2 dates from a `datepicker`.
