### ISSUE TITLE
geo_chart uses Google API, is it free

### ISSUE THREAD

**Issue by Rubioli** [ankane/chartkick#366]
From my console I can see some warnings from `Google Maps API`.
![skjermbilde 2017-06-21 kl 00 07 01](https://user-images.githubusercontent.com/16593596/27358180-aba7dffa-5615-11e7-865a-30842f2947b4.png)
Is this free or do I need to purchase a plan after some numbers of requests?

**Comment by FanaHOVA** [comment]
@Rubioli free tier is 25k requests per 24 hours, so you should be fine. You can see more here https://developers.google.com/maps/documentation/javascript/usage

**Comment by Rubioli** [comment]
Thank man 👍
