### ISSUE TITLE
Chartkicks dates doesn't show up when inside bootstrap Tabs

### ISSUE THREAD

**Issue by Rubioli** [ankane/chartkick#367]
I am using `Chartkick` in my application. I have 2 charts in my dashboard.

When I have each chart in its own `div` *(which is visible when page is loaded)*, everything looks fine:

    .col-md-12
        = area_chart Visit.where(user: current_user).group_by_day(:started_at, last: 7).count
    
    .col-md-12
        = area_chart Visit.where(user: current_user).group_by_day(:started_at, last: 7).sum(:price)

[![works][1]][1]

But when I have them inside tabs *(CSS tabs or bootstrap tabs)*, dates in `X` just doesn't show up.

    .col-md-12
      #view-tab.tab-content
        #visits.tab-pane.fade.active.in
          .chart-visits-container
            = area_chart Visit.where(user: current_user).group_by_day(:started_at, last: 7).count
    
        #prices.tab-pane.fade
          .chart-spends-container
            = area_chart Visit.where(user: current_user).group_by_day(:started_at, last: 7).sum(:price)

[![Not working][2]][2]

Always chart that is `active` looks fine, but others have issue. I thought maybe the `js` for `tabs` causes the issue and I even tested with a pure CSS tab, but same issue.

Not sure what causes the issue. Any help is appreciated!

*PS: Chart data is correct, only X dates doesn't show up*

  [1]: https://i.stack.imgur.com/r5IWD.png
  [2]: https://i.stack.imgur.com/i4X3W.png

**Comment by ankane** [comment]
Hey @Rubioli, try calling `Chartkick.charts["chart-id"].redraw()` when the tab becomes active.

**Comment by ankane** [comment]
Cleaning up stale issues
