### ISSUE TITLE
Curve: false for one from series?

### ISSUE THREAD

**Issue by pruzicka** [ankane/chartkick#368]
Hi, 
is it possible to have only one line from series with "Curve: false" ?

I've tried this with no luck
<%= line_chart [
	{ data: moving_range, legend: true, name: "Moving Range", curve: false},
	{ data: moving_range_average, legend: true, name: "Average", library: {borderDash: [3,3]}},
	{ data: ucl_moving, legend: true, name: "Upper Control Limit"} 
	], legend: "bottom" %>

With one line only, it works just fine
<%= line_chart moving_range, legend: true, label: "Moving Range", curve: false %>

Thanks

**Comment by ankane** [comment]
Hey @pruzicka, per series options aren't supported right now (except for `library` with Chart.js).
