### ISSUE TITLE
refreshData() not working

### ISSUE THREAD

**Issue by homeworkhotline** [ankane/chartkick#369]
I have the following code:

`var chart = Chartkick.charts["piedb"]`
`chart.refreshData()`

And Im using action cable to run it every time the CallLog model is updated. The problem is, nothing changes... Ive tried for hours to figure it out and nothing works. Possible bug?

**Comment by ankane** [comment]
Hey @homeworkhotline, if you're using Action Cable, you probably need to use `updateData` to pass the new data.

**Comment by ankane** [comment]
No response... cleaning up issues
