### ISSUE TITLE
Geo Charts' Region Option

### ISSUE THREAD

**Issue by kaliaabhishek** [ankane/chartkick#370]
Hi,

Thanks a lot for this gem. Made my life simpler.

But I was wondering how to pass the region option in the google charts' `geo_chart` helper so that I am able to view a geo chart for the map of India ("IN").

`= geo_chart Publisher.group(:country).count, region: "IN"` doesn't seem to work.

Thanks in advance.

**Comment by fanjieqi** [comment]
Try this one:

`= geo_chart Publisher.group(:country).count, library: {region: 'IN'}`

> https://github.com/ankane/chartkick/issues/140

**Comment by ankane** [comment]
Exactly what @fanjieqi said (thanks @fanjieqi 👍 )

**Comment by kaliaabhishek** [comment]
Thanks for helping me out @fanjieqi and @ankane !
