### ISSUE TITLE
background color graph not working

### ISSUE THREAD

**Issue by vanessasoutoc** [ankane/chartkick#371]
I need background color is white for to download to the graphic. But not working.
Example to code:

<%= column_chart Usuario.group_by_month(:created_at, format: "%b %Y", last: 12).count , download: true, library: {backgroundColor: "#eee"}  %>

**Comment by ankane** [comment]
Hey @vanessasoutoc, Chart.js doesn't have a background color option, so there's no way to do this right now.

**Comment by richrines** [comment]
This also doesn't appear to be working with highcharts

**Comment by ankane** [comment]
@richrines see https://github.com/ankane/chartkick/issues/268#issuecomment-230115281
