### ISSUE TITLE
In ruby, how to pass chartkick graph to pdf using prawn?

### ISSUE THREAD

**Issue by rtmex** [ankane/chartkick#372]
I'm using chratkick with Chart.js on a Sinatra application I'm developing. I need to include a chrat_column graph into a pdf using the prawn gem. How can I download the graph to a png file without user intervention?.

**Comment by ankane** [comment]
Hey @rtmex, Chartkick isn't meant for server-side charts. I'd try something like https://github.com/vmpowerio/chartjs-node instead.
