### ISSUE TITLE
Wicked_pdf + Chartkick = Not load graphs

### ISSUE THREAD

**Issue by PedroPauloML** [ankane/chartkick#373]
Hi!
I'm get the error when I request to generate the pdf, but the graph of Chartkick not load.

![captura de tela 18](https://user-images.githubusercontent.com/21173324/27874053-9289ef98-6184-11e7-9fc4-56c40f34bf08.png)

Any tips?

**Comment by ankane** [comment]
Hey @PedroPauloML, looks like the JavaScript isn't being loaded. From the Wicked PDF docs:

> The wkhtmltopdf binary is run outside of your Rails application; therefore, your normal layouts will not work. If you plan to use any CSS, JavaScript, or image files, you must modify your layout so that you provide an absolute reference to these files. The best option for Rails without the asset pipeline is to use the wicked_pdf_stylesheet_link_tag, wicked_pdf_image_tag, and wicked_pdf_javascript_include_tag helpers or to go straight to a CDN (Content Delivery Network) for popular libraries such as jQuery.

**Comment by Owohlet** [comment]
I'm having the exact same issue. I used the helpers provided by wicked_pdf but somehow I don't think the javascript is being loaded in the pdf
for the pdf layout (`generate_pdf.pdf.erb`) I have these
`<%= wicked_pdf_javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>`
`<%= wicked_pdf_javascript_include_tag "https://code.jquery.com/jquery-3.2.1.min.js" %>`
`<%= wicked_pdf_javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.2.4/chartkick.min.js" %>`

which are the exact same assets I'm using in the HTML template and the charts work.
 I have tried to use  `javascript_delay: 9000` with no success. I've tried to change the gem to  `'wkhtmltopdf-binary-edge'` no luck. Any tips?

**Comment by ankane** [comment]
Chartkick doesn't officially support rendering outside a browser, so going to close. However, if anyone has pointers for this, happy to add them to the readme.

**Comment by tanakaworld** [comment]
I resolved this problem following code.

The point of this, using the option `window_status`, the helper `wicked_pdf_asset_base64` and redraw charts after `window_status` set.

As long as I tried, `<%= wicked_pdf_javascript_include_tag 'pdf' %>` is not working in production compiled assets, but `<%= javascript_include_tag wicked_pdf_asset_base64('application-pdf') %>` is working.

```ruby
# app/controllers/pdfs_controller
 
class PdfsController < ApplicationController
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "file_name",
               layout: "pdf",
               window_status: "FLAG_FOR_PDF" # Wait until window.status is equal to this string before rendering page
      end
    end
  end
end
```

```erb
<!-- app/views/layouts/pdf.html.erb -->

<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>

    <%= wicked_pdf_stylesheet_link_tag 'application' %>
   
    <!-- This is not working in production compiled assets. -->
    <!-- <%= wicked_pdf_javascript_include_tag 'pdf' %> -->
    <%= javascript_include_tag wicked_pdf_asset_base64('pdf') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
```

```javascript
// app/assets/javascripts/pdf.js

//= require libs/chartkick
//= require libs/loader

setTimeout((function () {
    window.status = "FLAG_FOR_PDF";
    Object.keys(Chartkick.charts).forEach(function (key) {
        Chartkick.charts[key].redraw();
    });
}), 3000);
```

**Comment by arturoduarte** [comment]
this is the solution for that case

https://stackoverflow.com/a/26817410/4142543
