### ISSUE TITLE
Unable to retrieve chart object in Rails 4

### ISSUE THREAD

**Issue by kenigbolo** [ankane/chartkick#376]
Currently I have the following require statements in my application.js
`//= require Chart.bundle
//= require chartkick`

In my views/layouts/application.html I have the include statement
`javascript_include_tag "https://www.google.com/jsapi", "chartkick"`

Everything works as it should including the charts and all but whenever I try to retrieve a chart using the id (as written in the documentation) I get back `undefined` as the response to the chart object. For example
`var chart = Chartkick.charts["chart-1"]`
when I log out `chart`on the console it evaluates to `undefined`. If I attempt to call any function on the object, e.g. `getChartObject()` this obviously throws an error since you cannot call that on an object that is undefined.

Not exactly sure where the issue is from but if it helps, my require statements for my application.js as as follows;
`//= require jquery`
`//= require jquery.turbolinks`
`//= require jquery_ujs`
`//= require jquery.inputmask`
`//= require jquery.inputmask.extensions`
`//= require jquery.inputmask.date.extensions`
`//= require bootstrap-sprockets`
`//= require bootstrap-sprockets`
`//= require clipboard`
`//= require Chart.bundle`
`//= require chartkick`

**Comment by ck3g** [comment]
If you are requiring your application in the bottom of the page, that might be a problem. 
From docs: https://github.com/ankane/chartkick#installation
> Note: In the instructions below, application.js must be included before the helper methods in your views

**Comment by kenigbolo** [comment]
@ck3g I actually use `content_for` tag and according to the docs I think that should suffice

**Comment by gabsinator** [comment]
Check your chartkick gem version. (gem list --local |grep chart)

Had this issue and noticed that if I (as instructed) just put gem 'chartkick' in my Gemfile it will install versjon 1.4.0. 

Change it to gem 'chartkick', '~> 2.2.0' and run bundle install and it should grab the right version and work.

**Comment by ankane** [comment]
Hey @kenigbolo, be sure your chart id is correct. Also, try running `Chartkick.charts["chart-1"]` in the console to see if it returns anything. If it does, it's like an issue with the order your code is executing.

**Comment by ankane** [comment]
Cleaning up stale issues
