### ISSUE TITLE
stacked bar chart using google charts

### ISSUE THREAD

**Issue by bennyzr** [ankane/chartkick#378]
<% data = [ { name: "Test", data: [["2010", 10], ["2020", 16], ["2030", 28]] } ] %>
    <%= bar_chart data, stacked: true, colors: ["#b00", "#666", "#555"] %>

produces a regular 3 bars bar chart in a single color (#555), not a stacked single bar chart. What am I doing wrong?

**Comment by reubenbrown** [comment]
This should accomplish what you are looking for:

```
<% data =[{ name: '2010', data: { 'Value' => 10 } }, { name: '2020', data: { 'Value' => 16 } }, { name: '2030', data: { 'Value' => 28 } }] %>
<%= bar_chart data, stacked: true, colors: ['#b00', '#666', '#555'] %>
```

**Comment by ankane** [comment]
Thanks for the assist @reubenbrown 👍
