### ISSUE TITLE
Tie color to a param of model?

### ISSUE THREAD

**Issue by dnorthrupva** [ankane/chartkick#380]
Let's say I have a Pie Chart, and a timeline graph. 
Pie Chart is a count of parameter `style` from controller `user`
The timeline is a breakdown of the `start_date` and `end_date` of the `style`.

Each graph is working properly but in the Pie Chart `style A` will have an orange color, but the timeline chart uses orange to break down a `users` style. Is it possible so instead each timeline bar referencing `style A` is orange?

**Comment by ankane** [comment]
Hey @dnorthrupva, you can use the `colors` option to control the color of each series for each chart. There's no built-in way to synchronize colors.
