### ISSUE TITLE
Legend issue for multiseries chart

### ISSUE THREAD

**Issue by gouravlele** [ankane/chartkick#381]
Legends are show for each series in graph, how can I you common legends for all series in chart.
![screenshot from 2017-08-11 15 08 55](https://user-images.githubusercontent.com/28781915/29208416-8d08aba0-7ea7-11e7-8dac-19e686c76d76.png)
Please help!

**Comment by ankane** [comment]
Hey @gouravlele, can you share the JavaScript that is generated by Chartkick?

**Comment by ankane** [comment]
Cleaning up stale issues
