### ISSUE TITLE
Combining two charts and show as one

### ISSUE THREAD

**Issue by Rubioli** [ankane/chartkick#382]
Is it possible to combine `line_chart` & `column_chart ` *(or other charts)* to one chart?

Lets say I have this two charts:

`= line_chart Visit.where(user: current_user).group_by_day(:started_at).count`

`= column_chart Visit.where(user: current_user).group_by_day(:started_at).sum(:price)`

As of now they show as two seperate charts, but Im looking for something like the picture below.

![skjermbilde 2017-08-15 kl 19 50 40](https://user-images.githubusercontent.com/16593596/29328500-19d71f50-81f3-11e7-9817-bb9f360f8acb.png)

Any help is appreciated!

**Comment by ankane** [comment]
Hey @Rubioli, Chartkick doesn't support any type of combo chart.
