### ISSUE TITLE
in pie chart, some small areas can't display value and percentage

### ISSUE THREAD

**Issue by catfishuang** [ankane/chartkick#384]
library: {pieSliceText:'value-and-percentage'}

see attachment

rails 4 .  chartkick 2.2.4

<img width="542" alt="dx-20170828 2x" src="https://user-images.githubusercontent.com/18095865/29765143-9453f316-8c0c-11e7-81f0-64a7e9cdf2af.png">

**Comment by ankane** [comment]
Hey @catfishuang, thanks for reporting. As far as I understand, this is how Google Charts chooses to display the data. I don't think there's anything Chartkick can do about it.
