### ISSUE TITLE
show proper number of days of each month ?

### ISSUE THREAD

**Issue by louy755** [ankane/chartkick#386]
Hello I am new to this great tool please help when I use :
  = line_chart @posts.group_by_day_of_month(:created_at).count
The chart will give me 31 days for every month by default how to fix this please by showing the proper number of days for each month like 28 days for Feb Not 31 :{
![feb](https://user-images.githubusercontent.com/22380950/31345264-c8d5bb8a-acda-11e7-966d-5ed3b2a122a5.jpg)

**Comment by ankane** [comment]
Hey @louy755, you should use `group_by_day` if you only want to show one month.

**Comment by louy755** [comment]
sure that is the proper way thank you so much!
