### ISSUE TITLE
Chartkick tooltip not working in Chrome

### ISSUE THREAD

**Issue by Raycoms** [ankane/chartkick#388]
As the title says, the chartkick tooltip doesn't show where the mouse points to in chrome, it has quite a strong offset to the left.

(It works well in Firefox).

**Comment by Raycoms** [comment]
Add: The offset increases with the amount of x categories.

**Comment by ankane** [comment]
Hey @Raycoms, can you share the JavaScript generated by Chartkick and a screenshot of the issue?

**Comment by Raycoms** [comment]
Hi, just checked it out and somehow it got fixed on your site already. thanks

**Comment by Kostronor** [comment]
While getting the javascript and screenshot the issue disappeared on chrome. Should it appear again, I'll get the relevant javascript and a screeenshot.
