### ISSUE TITLE
Problem with urls as data

### ISSUE THREAD

**Issue by Raycoms** [ankane/chartkick#389]
I tried to add the data as in #14 as a URL and found out that that doesn't work.

In order to solve that I followed the instruction of #14:

`  def limit_graph
    render json: {name: "Avail. Votes", data: User.calculate_seller_points.each}
  end` 

`area_chart limit_graph_path`

Which resulted in two graphs without any data, one for name and one for data.

The simple way:

    `render json: User.calculate_seller_points.each`

Things work perfectly fine, but I'd like to name that data.

**Comment by ankane** [comment]
Hey @Raycoms, try returning an array of hashes.

```ruby
render json: [{name: "Avail. Votes", data: User.calculate_seller_points.each}]
```
