### ISSUE TITLE
Add Feature for Timeline

### ISSUE THREAD

**Issue by ghost** [ankane/chartkick#39]
Are you able to add the ability to chart timelines?

(https://developers.google.com/chart/interactive/docs/gallery/timeline)

Thanks!

**Comment by yagudaev** [comment]
is it possible to use timelines with highcharts?

**Comment by yagudaev** [comment]
Found this: http://highcharts.uservoice.com/forums/55896-general/suggestions/804783-gantt-chart. Highcharts also has this on their roadmap for an official implementation. We could just use that for now in chartkick to allow for timeline to work
