### ISSUE TITLE
Using Chartkick with Slim Template language

### ISSUE THREAD

**Issue by zbaylin** [ankane/chartkick#391]
Hey everyone, 
I am trying to use chartkick with the slim template language instead of ERB. I have included the following in my layout.slim
`script src="http://www.google.com/jsapi"
script src="/scripts/chartkick.js"`
I also put `require 'chartkick'` at the top of my app.rb
When I try to create any chart, I get a NoMethodError for every chart.
I believe this has to do with Slim, but I could be wrong. 

Any help is appreciated!

**Comment by erickveras** [comment]
I normally use chartkick with slim and I dont have problems. The require needs to be in application.js

**Comment by ankane** [comment]
Hey @zbaylin, I’ve used Chartkick with Slim as well. I’d confirm the gem is installed and you’ve restarted your server.
