### ISSUE TITLE
Chartkick shows unsorted x axis though sorted data is given

### ISSUE THREAD

**Issue by mmgeo** [ankane/chartkick#392]
I am using highcharts-rails to build a graph.

Below is the format inputted into the graph.

		       [{"name":"A","data":[["November 2017",12],["December 2017",19]]},
				{"name":"B","data":[["October 2017",2],["November 2017",1],["November 2017",1],["December 2017",9]]},
				{"name":"C","data":[["November 2017",1]]},
				{"name":"D","data":[["October 2017",1],["November 2017",10],["November 2017",3],["November 2017",11],["December 2017",44]]},
				{"name":"E","data":[["November 2017",5],["November 2017",2],["December 2017",2]]},
				{"name":"F","data":[["November 2017",1]]},
				{"name":"F","data":[["October 2017",11],["November 2017",1],["November 2017",1],["November 2017",2],["December 2017",9]]}] 

in which the date is sorted, but sent seperately into the helper method in rails.

      def usage_left_column_chart(Adata, Bdata, Cdata, Ddata, Edata, Fdata, Gdata)
        column_chart [{name: "A", data: Adata},
                      {name: "B", data: Bdata},
                      {name: "C", data: Cdata},
                      {name: "D", data: Ddata},
                      {name: "E", data: Edata},
                      {name: "F", data: Fdata},
                      {name: "G", data: Gdata},
                       ], stacked: true,  
         library: {
         chart: {zoomType: 'x'},
         title: {text: "Count of clicks on left navigation per month"},
         subtitle: {text: 'Click and drag to zoom in.'},
         tooltip: {
          valueDecimals: 0
         },
         yAxis: {
           title: {
             text: 'Count'
           }
         } 
       }
      end

But the graph shows the date unsorted and random as below. Any way to fix this issue?
![clicks](https://user-images.githubusercontent.com/26531075/33219978-50b037d6-d113-11e7-906e-e9dcd2e173c5.png)

**Comment by mmgeo** [comment]
Any help on this issue please? @ankane

**Comment by ankane** [comment]
Hey @mmgeo, the data is sorted in the order you’re passing it in. One thing you can do is pass all the labels in the first series in the order you want.

**Comment by jao** [comment]
Hello, this might be related, I apologize if it is not:
```[
  {
    "name": "sac",
    "data": {
      "01": 0,
      "02": 0,
      "03": 0,
      "04": 0,
      "05": 0,
      "06": 0,
      "07": 0,
      "08": 0,
      "09": 0,
      "10": 0,
      "11": 0,
      "12": 0,
      "13": 0,
      "14": 1,
      "15": 0,
      "16": 0,
      "17": 0,
      "18": 0,
      "19": 0,
      "20": 0,
      "21": 0,
      "22": 0
    }
  },
  {
    "name": "my_subscriptions",
    "data": {
      "01": 0,
      "02": 0,
      "03": 0,
      "04": 0,
      "05": 0,
      "06": 0,
      "07": 0,
      "08": 0,
      "09": 0,
      "10": 0,
      "11": 0,
      "12": 0,
      "13": 0,
      "14": 0,
      "15": 0,
      "16": 0,
      "17": 0,
      "18": 1,
      "19": 0,
      "20": 0,
      "21": 0,
      "22": 0
    }
  },
  {
    "name": "?",
    "data": {
      "01": 0,
      "02": 0,
      "03": 0,
      "04": 0,
      "05": 0,
      "06": 0,
      "07": 0,
      "08": 0,
      "09": 0,
      "10": 0,
      "11": 0,
      "12": 0,
      "13": 0,
      "14": 0,
      "15": 0,
      "16": 0,
      "17": 0,
      "18": 0,
      "19": 0,
      "20": 0,
      "21": 1,
      "22": 0
    }
  }
]
```

`<%= column_chart @created_subscriptions, stacked: true %>`

<img width="996" alt="screenshot 2018-05-29 16 12 22" src="https://user-images.githubusercontent.com/13377/40679994-1af81584-635b-11e8-8877-aab78c40e4d2.png">

**Comment by ankane** [comment]
@jao This is a slightly different issue. You'll need to convert the data to an array if you want it to keep it's ordering, since hashes in JavaScript have no ordering. Chartkick may automatically convert Ruby hashes to arrays because of this in the future.
