### ISSUE TITLE
Chart.js global options

### ISSUE THREAD

**Issue by cseelus** [ankane/chartkick#394]
Searched all issues and the web, but didn't find anything. Is it possible with Chartkick to pass global options to Chart.js, like so:

```ruby
Chart.defaults.global.responsive = true;
Chart.defaults.global.maintainAspectRatio = false;
```

**Comment by ankane** [comment]
Hey @cseelus, you should be able to use the `library` option to set them.

```ruby
Chartkick.options = {
  library: {...}
}
```

**Comment by cseelus** [comment]
Hey @ankane, thanks for the reply. Are you shure this works? Tested `defaultFontColor ` [1]

```javascript
Chartkick.options = {
  library: {
    defaultFontColor: 'red'
}
```

… but without success.

[1] http://www.chartjs.org/docs/latest/general/fonts.html

**Comment by ankane** [comment]
Yes, I'm sure the `library` option works. Chartkick overrides font colors on the `scaleLabel` level (not `defaultFontColor`), so you'll need to do the same.

**Comment by cseelus** [comment]
Question was about [Chart.js global options](http://www.chartjs.org/docs/latest/general/fonts.html), which don't work.

**Comment by dmangeni** [comment]
@ankane @cseelus any change on accessing Chart.js global options from chartkick. I need to set default options for all the elements rather than individually
