### ISSUE TITLE
Format of date isn't kept

### ISSUE THREAD

**Issue by rept** [ankane/chartkick#395]
I have this data:

![days](https://user-images.githubusercontent.com/1388221/33666153-6f342a16-da99-11e7-97e0-5d05a6c6e2f6.jpg)

And I would like the chart to be displayed like that as well.  However I get this result:

![chart](https://user-images.githubusercontent.com/1388221/33666194-91c92f90-da99-11e7-8f32-53f88177c82a.jpg)

Is there a way to instruct chartkick not to do any interpretation on the dates and just display the strings that I've set?

**Comment by ankane** [comment]
Hey @rept, you can use the `discrete` option to prevent labels from being parsed.

```erb
<%= line_chart data, discrete: true %>
```

**Comment by rept** [comment]
Thanks, this seems to work.  Except for one issue I'm running into:
When displaying all days of a month, I only want to show the actual day, not include the month since that's already displayed on top.

When I do that, the order isn't being kept:

![order-wrong](https://user-images.githubusercontent.com/1388221/33933018-d00d8688-dff4-11e7-8a6e-b8e7019c2192.jpg)
This is by using:

`.group_by_period('day', :datetime, format: '%d')&.sum(:value)`

When I include the month (what I don't want to do) the order is kept correct.

![correct](https://user-images.githubusercontent.com/1388221/33933093-fc7a1664-dff4-11e7-9a1b-a1c0a19b00f0.jpg)

Here I use: `.group_by_period('day', :datetime, format: '%d/%m')&.sum(:value)`

How can I force it to keep the order of the data?

**Comment by rept** [comment]
Update: when using: '%-d' as format, it works correctly...
