### ISSUE TITLE
Chartkick/ChartJS not rendering chart

### ISSUE THREAD

**Issue by nynhex** [ankane/chartkick#396]
I'm using the latest chartkick gem 2.2.5 and I have bundled it, created and endpoint and a view, and included the Chartkick/Chartjs.bundle in my application.js like so

```
//= require jquery
//= require jquery_ujs
//= require tether
//= require popper
//= require turbolinks
//= require bootstrap
//= require bootstrap-datepicker
//= require selectize
//= require Chart.bundle
//= require chartkick
//= require_tree .
```
Here's what my controller endpoint looks like:

```
  def calls_by_day
    render json: Call.group_by_day(:transfer_date).count
  end
```

Here's my view:

```
<%= line_chart calls_by_day_charts_path %>
```

When I load the page, here is what is displayed, just raw JSON but no chart.

![json](https://image.ibb.co/k8n9Eb/Screen_Shot_2017_12_09_at_6_53_26_PM.png)

I read the directions and have used Chartkick before without issue in a Rails 3.2.x app.  But am having problems for some reason here.  I've read the instructions a few times so perhaps I'm overlooking something?  Any help is greatly appreciated.  Love the gem, just would enjoy getting it to work 👍

**Comment by ankane** [comment]
Hey @nynhex, it looks like you're loading the JSON endpoint rather than the view with the chart.

**Comment by nynhex** [comment]
@ankane Thanks for the information, I'm a bit tired working through this problem.  I am wondering if you can provide an example as to what I'm doing wrong.  I have the endpoint setup and was following the directions to load the line chart with the endpoint for a faster load.  Am I doing it wrong and if so what should I be declaring in the view?  Thanks for all your help!

**Comment by nynhex** [comment]
@ankane I tried switching the view portion like this

```
<%= line_chart Call.group_by_day(:transfer_date).count, library: {backgroundColor: "#F8F8F8"} %>
```
And it works, but it's slow because I'm assuming it's not rendering JSON.  I read in the docs that you can render JSON in the controller then call the endpoint in your line_chart method.  How can I get this functionality so my graphs load super fast and use JSON?

**Comment by ankane** [comment]
@nynhex You need two controller actions: one to render the json and another to render the chart view. [This episode of GoRails](https://gorails.com/episodes/charts-with-chartkick-and-groupdate) should also help make it clear.

**Comment by nynhex** [comment]
@ankane Thanks, the instructions in the docs were a bit confusing, I figured it out on my own.  Just needed to add a separate endpoint to render a JSON response.  All good now, thanks for your help.
