### ISSUE TITLE
Cannot render JSON and pass to endpoint in view

### ISSUE THREAD

**Issue by nynhex** [ankane/chartkick#397]
I had another open issue, but figured since it was solved, I'd open a new one.

In reading the directions for chartkick I see that I can render JSON in my endpoint then call the endpoint path in the line_chart or whatever method in the view.

```
Say Goodbye To Timeouts

Make your pages load super fast and stop worrying about timeouts. Give each chart its own endpoint.

<%= line_chart completed_tasks_charts_path %>
And in your controller, pass the data as JSON.

class ChartsController < ApplicationController
  def completed_tasks
    render json: Task.group_by_day(:completed_at).count
  end
end
```

However, when I do this the only thing that displays is rendered JSON.  How can I get the benefits of fast loading via JSON and have it display the chart properly?

**Comment by ankane** [comment]
@nynhex How is this different from #396?

**Comment by nynhex** [comment]
Sorry, it's not I guess.  I'll close this and follow the other issue.
