### ISSUE TITLE
How to visualize using group_by instead of groupdate using Chartkick

### ISSUE THREAD

**Issue by nynhex** [ankane/chartkick#398]
I'm using Chartkick 2.2.5 and Rails 5.1.4, and I have Units (vehicles) with a Status (Available/In service/etc) associated with it.  I'd like to be able to display a count of Units by status in a column or line chart.  So far here is the code I have in my view:

```
<%= column_chart Status.includes(:units).order("name asc").map {|s| {name: s.name, data: s.units.group_by{|u| u.name}.count}}, library: {backgroundColor: "#F8F8F8"} %>
```
This iterates through the status and displays them as seen here:

![screen](https://i.stack.imgur.com/SkOyS.png)

But it does not actually plot the units anywhere.  Perhaps my ruby is wrong (good possibility), but I'd like to figure out how to chart these units by status instead of a date column.  I realize this is not a "how to" section, but it would be nice if the docs had some sort of additional info on how to do this.  I'm pretty sure it's possible but from all of my Googling I've yet to find a decent solution.

**Comment by ankane** [comment]
@nynhex Please use StackOverflow for questions.
