### ISSUE TITLE
Strange behavior with turbolinks (works on first load, not later on)

### ISSUE THREAD

**Issue by ErCollao** [ankane/chartkick#400]
Hi! First of all, thanks for this great gem! I really love how easily I can add graphs to my apps!

I'm encountering a problem, I'm guessing it's because of the combination of chartkick, turbolinks, and async javascript loading (I recently added it to my app).

The first time I load a page (or when I refresh), it loads the graph perfectly. When I navigate away from the page, and then again back to it, it only shows the "Loading..." text. I'm guessing the turbolinks reload doesn't trigger the chartkick javascript.

Things that led me to this: I added `defer:true` to my production environment (when loading the javascript for application.js), which broke my charts (of course, chartkick wasn't loaded when the page was loaded). I added in the options hash `'defer': true` to chartkick, and that made it load perfectly on the first load.

Any ideas? Thanks in advance!

**Comment by ankane** [comment]
Hey @ErCollao, you can call:

```javascript
Chartkick.eachChart( function(chart) {
  chart.redraw();
});
```

to make charts redraw. I've tested Chartkick and Turbolinks with a fresh Rails app and it doesn't have this issue.

**Comment by ErCollao** [comment]
Thanks @ankane!

I've just tried executing your code on `'turbolinks:load'`, but it still behaves the same way 🤕

I'll try making a fresh app, and see if I replicate the error

**Comment by ankane** [comment]
Cleaning up stale issues
