### ISSUE TITLE
Chart.js handling default options stored in arrays

### ISSUE THREAD

**Issue by ryansmith23** [ankane/chartkick#403]
It seems like the function to merge the options from the default configuration and the chart instance ignores the case when an array of Hashes is given and just takes the instance's configuration.

For instance, say you've globally configured your yAxes in the initializer file such that gridLines do not display and the ticks have some padding. Then, applying any options to the yAxes at the time of invoking the chart helper will override all other global options relating to the yAxes.

Am I missing something here? Or was this a design choice to limit complexity?

**Comment by ankane** [comment]
Hey @ryansmith23, can you give a code sample of how options are merged and how you'd like them to be merged?

**Comment by ryansmith23** [comment]
Hey @ankane, here's a minimal example to try to illustrate what I'm talking about.

```
# config/initializers/chartkick.rb
Chartkick.options = {
  library: {
    scales: {
      xAxes: [{
        gridLines: { drawBorder: false }
      }]
    }
  }
}

# some view or helper
pie_chart(
  @data,
  library: {
    scales: {
      xAxes: [{
        scaleLabel: { fontColor: '#a00' }
      }]
    }
  }
)

# The resulting chart will end up with library options hash:
library: {
  scales: {
    xAxes: [{
      scaleLabel: { fontColor: '#a00' }
    }]
  }
}

# it has not retained the global configurations for the axes, but would have
# retained the global configurations if they weren't within an array. It also
# retains the global configurations if you don't set any options for the
# xAxes when invoking the chart function.

# I was expecting something like:
library: {
  scales: {
    xAxes: [{
      gridLines: { drawBorder: false }
      scaleLabel: { fontColor: '#a00' }
    }]
  }
}
```

I looked through the source a little while back and this happens because options are only merged together if they are hashes. If they are arrays, the global options get replaced with the instance options (if there are instance options). My first thought for a solution would be to check if the option is an array, then pad the shorter array to match the length of the other, zip the two together, and merge the hashes/values pairwise. However, this definitely would incur additional cost and may not be what everyone expects/desires. I also haven't spent much time with Google Charts or HighCharts, so I'm not sure if this would cause unexpected behavior with those libraries.

In the meantime, I have been getting by using helper functions which return a hash of some common configuration parameters that I pass to the `library` hash when creating a chart.

If you would like to add this, I can create a PR in the next week or so.

Thank you for all of your hard work, Chartkick is absolutely amazing!

**Comment by ankane** [comment]
Hey @ryansmith23, I see what you mean. I'm not sure if everyone will expect that same merge, so I'd prefer to leave it as is. I appreciate the suggestion 👍
