### ISSUE TITLE
Any way to disable 'dots' for line graphs?

### ISSUE THREAD

**Issue by maxiedaniels** [ankane/chartkick#404]
I'm using a large number of data points, and so the 'dots' turn into a mess of blobs. I'd like to just see the lines. Is there support for that?

**Comment by ankane** [comment]
Hey @maxiedaniels, check out the `points` option in the readme.

**Comment by maxiedaniels** [comment]
@ankane I’m sure I’m being dumb here but I’ve searched through the readme and can’t find a reference to points. I’ve also skimmed through the code and can’t find anything. Is it in a separate chart library?

**Comment by thijsre** [comment]
@maxiedaniels 
Hide points
```
<%= line_chart data, points: false %>
```

**Comment by ankane** [comment]
Thanks @thijsre
