### ISSUE TITLE
Documentation - Put examples of concrete data for line_chart

### ISSUE THREAD

**Issue by sordina** [ankane/chartkick#405]
I've been stuck for a while trying to generate a working line_chart because I can't see any examples of what data it is expecting, only database queries.

**Comment by sordina** [comment]
Such as:

```
          <%= line_chart([
            { name: "foo", data: { 20.day.ago => 1.0, 1.day.ago => 2.0 } },
            { name: "bar", data: { 20.day.ago => 5.0, 1.day.ago => 9.0 } },
          ]) %>
```

**Comment by ankane** [comment]
Hey @sordina, there's a similar example in the Data section: https://github.com/ankane/chartkick#data

**Comment by sordina** [comment]
Thanks @ankane  I might have missed that!

Closed :)
