### ISSUE TITLE
Memory consumption seems to be increased when updateData is called

### ISSUE THREAD

**Issue by medaka** [ankane/chartkick#415]
## phenomenon
When I monitored memory consumption of web browser, I've found that `updateData` method affect memory size.
Is there any way to avoid this and save memory consumption?

## Cause
`updateData` calls `new Chartkick.line_chart`, which creates new javascript object. It enlarges memory consumption.

## code

I've called `updateData` to refresh a graph image in .js.erb file:

```
var chart = Chartkick.charts["<%= id %> "];
chart.updateData(<%= raw data.to_json %>);
```

My web app calls api which includes this code every 30 seconds.
About 1 hour later, my pc is almost freezed because of lack of memory.

**Comment by medaka** [comment]
Thank you for your rapid response!
I've tried `chartkick.js` at chartkick.js repository and it works!!
I am looking forward to merging to this repository.

**Comment by ankane** [comment]
Great, glad it worked 👍
