### ISSUE TITLE
Using chartkick with webpacker

### ISSUE THREAD

**Issue by Spone** [ankane/chartkick#419]
Hi,

I'm trying to use chartkick with Chart.js and webpacker.

```rb
# Gemfile
# [...]
gem "chartkick", github: "ankane/chartkick"
```

```js
// package.json
// [...]
"dependencies": {
    "@rails/webpacker": "^3.2.1",
    "chart.js": "^2.7.1",
    "chartkick": "^2.3.0",
    // [...]
}
```

```js
// app/javascript/packs/application.js

import Chartkick from "chartkick";
window.Chartkick = Chartkick;

import Chart from "chart.js";
window.Chart = Chart;
```

In my view:

```slim
= pie_chart @data
```

When the page loads, in the browser console (Firefox), I get: `ReferenceError: Chartkick is not defined`

But then if I type `Chartkick` the variable exists.

![image](https://user-images.githubusercontent.com/38524/36547135-6bb6077e-17ed-11e8-99c2-8967dfbcbe36.png)

What do I do wrong?

**Comment by ankane** [comment]
Hey @Spone, make sure your pack is loaded before your charts.

**Comment by Spone** [comment]
I'm not sure how to do that. As a good practice, the JS pack should be at the end of the body (or marked as `defer`), right?

**Comment by ankane** [comment]
The `content_for` and `defer` options can help with that. See the docs for how to use them.

**Comment by Spone** [comment]
Thanks! I did not see the `defer` option initially :+1:
