### ISSUE TITLE
Error after updating from 2.2.5 to 2.3.1

### ISSUE THREAD

**Issue by nicovak** [ankane/chartkick#422]
Hello,

I updated chartkick from `2.2.5` to `2.3.1`
I ran into some issues, after some investigations, I think the error came from this file:
https://github.com/ankane/chartkick/blob/2e799984fe78dd52ee177f48616155cdefd2848f/vendor/assets/javascripts/chartkick.js#L584

It has been change in : https://github.com/ankane/chartkick/commit/77a36eea7a61389cecb14f42dd03b7aa1d74412f

But I only had the error on heroku in production. Locally all was working fine (maybe the cache).

Here is the config I used in `application.js`

```js
//= require Chart.bundle
//= require highcharts
//= require chartkick
```

And the code to call the chart:

```erb
<%= pie_chart @data, adapter: "highcharts" %>
```

Notice that I used some code to generate custom charts and It was working good while chartkick generated ones was throwing the error from the file above

```html
var chart = new Highcharts.Chart({}):
```

**Comment by ankane** [comment]
Hey @nicovak, can you paste the error, including the backtrace?

**Comment by ankane** [comment]
I'm able to reproduce. Working on a fix.

**Comment by ankane** [comment]
Pushed out Chartkick 2.3.2 due to severe nature (works in development but not in production). Thanks for reporting @nicovak 👍

**Comment by viktorsmari** [comment]
Verified that the update fixes console error
 `'No charting library found for e'` 
when chartkick works in development, but not production.
