### ISSUE TITLE
adding stepSize option

### ISSUE THREAD

**Issue by ivan-garanin** [ankane/chartkick#425]
It will be great to add stepSize option like this http://www.chartjs.org/samples/latest/scales/linear/step-size.html 

Thanks!

**Comment by ankane** [comment]
Hey @ivan-garanin, I believe you can use the `library` option for this.

**Comment by dominikw** [comment]
For everyone struggling with this, it was already solved right here:
https://github.com/ankane/chartkick/issues/339
