### ISSUE TITLE
Legend wont update

### ISSUE THREAD

**Issue by justcald** [ankane/chartkick#427]
I'm working with a multiple series line_chart trying to update the legend. 

First I tried this, and it doesn't do anything at all. 
`<%= line_chart  @data, legend: "right", adapter: "chartjs", height: "400px" %>`

Then I dug up this and it works for top and bottom, but throws an error for left and right.
`<%= line_chart @data, library: { legend: {position: "right"}, }, adapter: "chartjs"`

This is the error
`Error Loading Chart: Cannot read property '0' of undefined`

Like I said, the second option works fine for top and bottom, but not left and right. 

If I remove the `adapter: "chartjs"`, then the legend will update with the second option, but not the first. 

Maybe this isn't an issue, but any help would be great.

**Comment by ankane** [comment]
Hey @justcald, please follow the Contributing Guide instructions for reporting bugs.
