### ISSUE TITLE
Hightcharts no download button 

### ISSUE THREAD

**Issue by ivan-garanin** [ankane/chartkick#428]
Hi,
<img width="1409" alt="2018-03-26 23 14 11" src="https://user-images.githubusercontent.com/5081342/37930498-954967d0-314b-11e8-9fd7-0d87cf371c4c.png">
There is no download button when using `Hightcharts` insteed of `Chart.bundle`
Is there is any way to do something like this  https://gist.github.com/philfreo/0a4d899de4257e08a000 ? 
With `Chart.bundle` download option works great. Partial code:
```ruby
= line_chart [ { name: "Oxygen Level", data: oxygen_levels }, { name: "Hearth Rate", data: hearth_rates }], min: 50,  height: "600px", download: "Vitals from #{from}"
```
Thanks!

**Comment by ivan-garanin** [comment]
Fixed my issue by downloading  https://code.highcharts.com/modules/exporting.js
https://code.highcharts.com/modules/offline-exporting.js into  `vendor/assets/javascripts` and requiring them. Now Im able to download my charts as I want.

**Comment by ankane** [comment]
Hey @ivan-garanin, as the readme mentions, Chartkick only has built-in download support for Chart.js.
