### ISSUE TITLE
Column chart printing X axis out of order

### ISSUE THREAD

**Issue by nyousefi** [ankane/chartkick#429]
Column charts appear to be printing with the X axis out of order. For example, with this sample data:

```
data = []
data << { name: "A", data: {"2018-01-01" => 10, "2018-01-02" => 20, "2018-01-05" => 50} }
data << { name: "B", data: {"2018-01-02" => 20, "2018-01-03" => 20, "2018-01-04" => 50, "2018-01-05" => 10} }
data << { name: "C", data: {"2018-01-05" => 5} }
```

You get this chart:

<img width="988" alt="screen shot 2018-03-26 at 8 48 24 pm" src="https://user-images.githubusercontent.com/159396/37945991-d2202c52-3137-11e8-9b00-2365f9a164e2.png">

The X axis is clearly printing out of order, with the last date right smack in the middle of the chart.

Oddly, this behavior is dependent on the order of the data going in. That is, changing the data to be constructed like this:

```
data = []
data << { name: "C", data: {"2018-01-05" => 5} }
data << { name: "A", data: {"2018-01-01" => 10, "2018-01-02" => 20, "2018-01-05" => 50} }
data << { name: "B", data: {"2018-01-02" => 20, "2018-01-03" => 20, "2018-01-04" => 50, "2018-01-05" => 10} }
```

will generate a chart like this:

<img width="992" alt="screen shot 2018-03-26 at 8 52 23 pm" src="https://user-images.githubusercontent.com/159396/37946074-492302e8-3138-11e8-85c0-7333c756ae9d.png">

Now the last date is being put at the front of the chart.

Finally, using `stacked: true` on the chart doesn't fix this problem. 

Please let me know if you need any additional information. Thanks!

**Comment by ankane** [comment]
Hey @nyousefi, that's expected. Column charts are discrete, so there's no concept of a date axis.

**Comment by nyousefi** [comment]
This might be expected in terms of how the library is built, but I don't think this is an expected behavior from a users standpoint. I mean, **I** didn't expect a column chart to behave this way. I think if the X axis can be sorted it should be (unless you do `discrete: true`, like every other chart type). The sample data included shows a pretty good use case for this: why would you want data grouped by date in a column chart to NOT be sorted by the X axis?

Right now, I'm going to have to go through and pad all the data with empty date values to make sure the chart is printed correctly.  It just seems silly.

**Comment by ankane** [comment]
The only charts that default to a date axis are line and area. Dates can come in a wide number of formats, so trying to parse a date out of a string can be dangerous for chart types that typically don't have date labels. I've added it to the list of things to consider for Chartkick 3.
