### ISSUE TITLE
Multiple series based on attributes

### ISSUE THREAD

**Issue by markaharper** [ankane/chartkick#430]
Love Chartkick & Ahoy!!! So elegant. Thank you.

For those struggling to create a multiple series chart based on record attributes, perhaps you can add this example to your existing README.md examples.

It took me two days of struggles to figure it out, yet the answer is simple.

Perhaps an example like this one can help others spawn new ideas and expand their use of Chartkick.

--------------------------------------

Multiple series based on attributes

`<% stats_this_week = DailyStat.where("user_id = :user_id and DATE(created_at) > :start_date", start_date: 8.days.ago.to_date, user_id: user_id).group_by_day(:created_at) %>`

`<%= line_chart [ `
`{ name: "Total Links Out", data: stats_this_week.minimum(:outbounds_count_total)},` 
`{ name: 'Facebook', data: stats_this_week.minimum(:outbounds_count_facebook)}, `
`{ name: "Instagram", data: stats_this_week.minimum(:outbounds_count_instagram)}, `
`{ name: "Snapchat", data: stats_this_week.minimum(:outbounds_count_snapchat)}, `
`{ name: "Twitter", data: stats_this_week.minimum(:outbounds_count_twitter)}, `
`{ name: "YouTube", data: stats_this_week.minimum(:outbounds_count_youtube)} `
` ],`  
`ytitle: "Your Outbound Links This Week" %>`

**Comment by ankane** [comment]
Hey @markaharper, thanks for sharing, and sorry for not responding sooner. This example seems a bit complex to add to the readme, but happy to review suggestions if you'd like to submit a PR.
