### ISSUE TITLE
Option to disable assets pipeline support

### ISSUE THREAD

**Issue by n-rodriguez** [ankane/chartkick#431]
Hi,

I'm using chartkick with Webpack and it works very well. But when compiling assets, chartkick assets pipeline files are automatically generated because `chartkick.js` is [added to the pipeline](https://github.com/ankane/chartkick/blob/master/lib/chartkick/engine.rb#L6).

Is it possible to add an option to disable the assets pipeline support?

Thank you!

**Comment by ankane** [comment]
Hey @n-rodriguez, thanks the suggestion. I’m planning to remove this completely in Chartkick 3, so don’t want to add an option for it (especially since it doesn’t hurt anything).
