### ISSUE TITLE
Unable to set prefix using google charts

### ISSUE THREAD

**Issue by tonyvince** [ankane/chartkick#436]
I have been trying to set a prefix for pie chart data
```ruby
pie_chart data, prefix: "₹", width: "35rem", height: "35rem",
                        allowRedraw: true,
                        library: {
                          is3D: true,
                          pieSliceText: "label" 
                        }
```
but prefix is not showing up.

chartkick (2.3.4)
Ruby(2.4.1)
Rails(5.2.0)

**Comment by ankane** [comment]
Hey @tonyvince, the `prefix` option is not supported for Google Charts.

![screen shot 2018-05-16 at 11 27 39 am](https://user-images.githubusercontent.com/220358/40136253-357eba34-58fc-11e8-9403-7012fa143d39.png)

**Comment by tonyvince** [comment]
@ankane thanks for the clarification. May I know what is the recommended way of using prefixes with google charts? Thanks
