### ISSUE TITLE
How to remove transparency in column charts?

### ISSUE THREAD

**Issue by Spone** [ankane/chartkick#439]
Hi,

Here is what I currently have:

![image](https://user-images.githubusercontent.com/38524/41205937-eb6722e6-6cfc-11e8-8400-387633ce25e3.png)

For consistency with the pie chart, I would like the column chart to have a opacity of `1` (instead of the default, which is `0.5`).

There do not seem to be an option for that, if I read the source code: `addOpacity` is always called [here](https://github.com/ankane/chartkick/blob/master/vendor/assets/javascripts/chartkick.js#L526).

Is there a way to specify my own value for opacity?
If not, could we add an option for that?

Thanks in advance.

**Comment by ankane** [comment]
Hey @Spone, you should be able to use the newly released `dataset` option to customize the colors directly. You'll need to do the opacity calculation yourself and pass in the appropriate hex values. I don't think opacity is common enough to warrant it's own option right now.

**Comment by Spone** [comment]
Thank you, I got it working!

![image](https://user-images.githubusercontent.com/38524/41674400-2831047e-74c0-11e8-8f85-fb33cd140c4b.png)
