### ISSUE TITLE
processSeries Check if 1 series of multiple needs to be rebuilt

### ISSUE THREAD

**Issue by StephenOTT** [ankane/chartkick#44]
```
    // see if one series or multiple
    if (!isArray(series) || typeof series[0] !== "object" || isArray(series[0])) {
      series = [{name: "Value", data: series}];
      opts.hideLegend = true;
    } else {
      opts.hideLegend = false;
    }
```

To support multiple columns of data rather than a max of 2 columns this if statement in chartkick.js needs to be rebuilt.  The offending part of the statement is `isArray(series[0]))` which places the entire dataset into a object/hash.  

Looking over the code i think a refactor would be beneficial to separate Data Manipulation and generation of the charts.  Then use the process functions to call the needed manipulations and chart options as optional parameters

related: #42 and #43

**Comment by ankane** [comment]
Cleaning up issues
