### ISSUE TITLE
Format vertical bar number value

### ISSUE THREAD

**Issue by abidiqbalk** [ankane/chartkick#446]
Hi,

https://ibb.co/fqJv3U

I have added column chart to my project and I want to format deciamls to round values like 2.5 to 3 and 7.5 to 8. Is there any attribute defined to do this ?

Thanks!

**Comment by ankane** [comment]
Hey @abidiqbalk, please check out the [Help section](https://github.com/ankane/chartkick/blob/master/CONTRIBUTING.md#help) of the Contributing Guide.
