### ISSUE TITLE
Adapter to generate image (gif) charts to embed them into emails

### ISSUE THREAD

**Issue by FGRibreau** [ankane/chartkick#447]
Hello!

Would you be interested by an adapter for [Image-Charts](https://image-charts.com) (drop-in-replacement of the deprecated [Google Image Charts](https://developers.google.com/chart/image/) with gif support) so chartkick could be used to generate charts for email/bot embedding?

I'm starting this thread because someone on SO [already asked for it](https://stackoverflow.com/q/33805657/745121) and I can help with that (or you might want to do it yourself, just let me know!) :)

**Comment by ankane** [comment]
Hey @FGRibreau, neat idea. Chartkick adapters are currently written in JavaScript. It seems like this would need to be written in Ruby. Since it won't share much of the same code, I think it'll be better as a separate project.

**Comment by FGRibreau** [comment]
I've looked at the adapter code and it seems to perfectly fit inside `chartkick.js`, I would just need to had a fourth adapter to live along chart.js & so on, don't you think?

**Comment by FGRibreau** [comment]
Oh indeed, I know, just woke up should not have posted this hahaha. Indeed it would require a change on the ruby side :)
