### ISSUE TITLE
Library params ignored when other params are passed

### ISSUE THREAD

**Issue by leenasn** [ankane/chartkick#448]
Hi,

When I use the id option with library params, the library params are ignored. Example the code below gives me output as the first attached image:

`data = [["Branch 1", 600], ["Branch 2", 800]]`
`pie_chart data, id: "outstanding-chart", library: { is3D: true, pieSliceText: "value" }`

<img width="426" alt="screen shot 2018-08-30 at 3 43 00 pm" src="https://user-images.githubusercontent.com/559752/44845658-ca481580-ac6b-11e8-8b24-c6cc93f1d77e.png">

Bu when I remove the id param from the hash, 
`data = [["Branch 1", 600], ["Branch 2", 800]]`
`pie_chart data, library: { is3D: true, pieSliceText: "value" }`

<img width="330" alt="screen shot 2018-08-30 at 3 43 29 pm" src="https://user-images.githubusercontent.com/559752/44845700-e350c680-ac6b-11e8-8ad5-b369f7b3fafe.png">

I tried setting the Global options as recommended in the [README](https://github.com/ankane/chartkick/blob/ff73a436a62e1e4dadec390904f8ad76de80721a/README.md), but found the same behaviour. 

Is there anything wrong am doing with the way am calling the methods? I need both the library params and also need to set ID for the chart.

Thanks,
Leena

**Comment by ankane** [comment]
Hey @leenasn, can you include the rendered HTML and JavaScript for each chart?

**Comment by leenasn** [comment]
Hi @ankane,

Please find the HTML for each below:

## With ID param

`<div id="outstanding-chart" style="height: 300px; width: 100%; text-align: center; color: #999; line-height: 300px; font-size: 14px; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif;"><div style="position: relative;"><div dir="ltr" style="position: relative; width: 535px; height: 300px;"><div aria-label="A chart." style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%;"><svg width="535" height="300" aria-label="A chart." style="overflow: hidden;"><defs id="defs"></defs><rect x="0" y="0" width="535" height="300" stroke="none" stroke-width="0" fill="#ffffff"></rect><g><rect x="327" y="134" width="112" height="31" stroke="none" stroke-width="0" fill-opacity="0" fill="#ffffff"></rect><g column-id="Branch 1"><rect x="327" y="134" width="112" height="12" stroke="none" stroke-width="0" fill-opacity="0" fill="#ffffff"></rect><g><text text-anchor="start" x="344" y="144.2" font-family="'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif" font-size="12" stroke="none" stroke-width="0" fill="#444444">Branch 1</text></g><circle cx="333" cy="140" r="6" stroke="none" stroke-width="0" fill="#3366cc"></circle></g><g column-id="Branch 2"><rect x="327" y="153" width="112" height="12" stroke="none" stroke-width="0" fill-opacity="0" fill="#ffffff"></rect><g><text text-anchor="start" x="344" y="163.2" font-family="'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif" font-size="12" stroke="none" stroke-width="0" fill="#444444">Branch 2</text></g><circle cx="333" cy="159" r="6" stroke="none" stroke-width="0" fill="#dc3912"></circle></g></g><g><path d="M308,139.4L308,160.6A106,84.80000000000001,0,0,1,247.9916763464612,237.00215999812514L247.9916763464612,215.80215999812515A106,84.80000000000001,0,0,0,308,139.4" stroke="#264d99" stroke-width="1" fill="#264d99"></path><path d="M202,139.4L202,160.6L247.9916763464612,237.00215999812514L247.9916763464612,215.80215999812515" stroke="#264d99" stroke-width="1" fill="#264d99"></path><path d="M202,139.4L202,54.599999999999994A106,84.80000000000001,0,0,1,247.9916763464612,215.80215999812515L202,139.4A0,0,0,0,0,202,139.4" stroke="#3366cc" stroke-width="1" fill="#3366cc"></path><text text-anchor="start" x="269.4025230076038" y="129.65261510607843" font-family="'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif" font-size="12" stroke="none" stroke-width="0" fill="#ffffff">600</text></g><g><path d="M247.9916763464612,215.80215999812515L247.9916763464612,237.00215999812514A106,84.80000000000001,0,0,1,96,160.6L96,139.4A106,84.80000000000001,0,0,0,247.9916763464612,215.80215999812515" stroke="#a52b0e" stroke-width="1" fill="#a52b0e"></path><path d="M202,139.4L247.9916763464612,215.80215999812515A106,84.80000000000001,0,1,1,202,54.599999999999994L202,139.4A0,0,0,1,0,202,139.4" stroke="#dc3912" stroke-width="1" fill="#dc3912"></path><text text-anchor="start" x="111.59747699239621" y="157.5473848939216" font-family="'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif" font-size="12" stroke="none" stroke-width="0" fill="#ffffff">800</text></g><g></g></svg><div aria-label="A tabular representation of the data in the chart." style="position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden;"><table><thead><tr><th></th><th>Value</th></tr></thead><tbody><tr><td>Branch 1</td><td>600</td></tr><tr><td>Branch 2</td><td>800</td></tr></tbody></table></div></div></div><div aria-hidden="true" style="display: none; position: absolute; top: 310px; left: 545px; white-space: nowrap; font-family: Arial; font-size: 12px; font-weight: bold;">₹600 (42.9%)</div><div></div></div></div>
`
```
<script type="text/javascript">
  new Chartkick.PieChart("outstanding-chart", [["Branch 1",600],["Branch 2",800]], {"library":{"is3D":true,"pieSliceText":"value"}});
</script>

```

## Without ID param

`<div id="chart-1" style="height: 300px; width: 100%; text-align: center; color: #999; line-height: 300px; font-size: 14px; font-family: 'Lucida Grande', 'Lucida Sans Unicode', Verdana, Arial, Helvetica, sans-serif;"><div style="position: relative;"><div dir="ltr" style="position: relative; width: 535px; height: 300px;"><div aria-label="A chart." style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%;"><svg width="535" height="300" aria-label="A chart." style="overflow: hidden;"><defs id="defs"></defs><rect x="0" y="0" width="535" height="300" stroke="none" stroke-width="0" fill="#ffffff"></rect><g><rect x="327" y="58" width="112" height="31" stroke="none" stroke-width="0" fill-opacity="0" fill="#ffffff"></rect><g column-id="Branch 1"><rect x="327" y="58" width="112" height="12" stroke="none" stroke-width="0" fill-opacity="0" fill="#ffffff"></rect><g><text text-anchor="start" x="344" y="68.2" font-family="Arial" font-size="12" stroke="none" stroke-width="0" fill="#222222">Branch 1</text></g><circle cx="333" cy="64" r="6" stroke="none" stroke-width="0" fill="#3366cc"></circle></g><g column-id="Branch 2"><rect x="327" y="77" width="112" height="12" stroke="none" stroke-width="0" fill-opacity="0" fill="#ffffff"></rect><g><text text-anchor="start" x="344" y="87.2" font-family="Arial" font-size="12" stroke="none" stroke-width="0" fill="#222222">Branch 2</text></g><circle cx="333" cy="83" r="6" stroke="none" stroke-width="0" fill="#dc3912"></circle></g></g><g><path d="M294,141.8L294,160.20000000000002A92,73.60000000000001,0,0,1,241.91730399881538,226.51130867761805L241.91730399881538,208.11130867761807A92,73.60000000000001,0,0,0,294,141.8" stroke="#264d99" stroke-width="1" fill="#264d99"></path><path d="M202,141.8L202,160.20000000000002L241.91730399881538,226.51130867761808L241.91730399881538,208.11130867761807" stroke="#264d99" stroke-width="1" fill="#264d99"></path><path d="M202,141.8L202,68.2A92,73.60000000000001,0,0,1,241.91730399881538,208.11130867761807L202,141.8A0,0,0,0,0,202,141.8" stroke="#3366cc" stroke-width="1" fill="#3366cc"></path><text text-anchor="start" x="251.84359953285457" y="134.8675223069271" font-family="Arial" font-size="12" stroke="none" stroke-width="0" fill="#ffffff">₹600</text></g><g><path d="M241.91730399881538,208.11130867761807L241.91730399881538,226.51130867761808A92,73.60000000000001,0,0,1,110,160.20000000000002L110,141.8A92,73.60000000000001,0,0,0,241.91730399881538,208.11130867761807" stroke="#a52b0e" stroke-width="1" fill="#a52b0e"></path><path d="M202,141.8L241.91730399881538,208.11130867761807A92,73.60000000000001,0,1,1,202,68.2L202,141.8A0,0,0,1,0,202,141.8" stroke="#dc3912" stroke-width="1" fill="#dc3912"></path><text text-anchor="start" x="125.15640046714543" y="157.1324776930729" font-family="Arial" font-size="12" stroke="none" stroke-width="0" fill="#ffffff">₹800</text></g><g></g></svg><div aria-label="A tabular representation of the data in the chart." style="position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden;"><table><thead><tr><th>Classes</th><th>Revenue</th></tr></thead><tbody><tr><td>Branch 1</td><td>₹600</td></tr><tr><td>Branch 2</td><td>₹800</td></tr></tbody></table></div><div aria-label="A tabular representation of the data in the chart." style="position: absolute; left: -10000px; top: auto; width: 1px; height: 1px; overflow: hidden;"><table><thead><tr><th>Classes</th><th>Revenue</th></tr></thead><tbody><tr><td>Branch 1</td><td>₹600</td></tr><tr><td>Branch 2</td><td>₹800</td></tr></tbody></table></div></div></div><div aria-hidden="true" style="display: none; position: absolute; top: 310px; left: 545px; white-space: nowrap; font-family: Arial; font-size: 12px;">Branch 2</div><div></div></div></div>`

```
<script type="text/javascript">
  new Chartkick.PieChart("chart-1", [["Branch 1",600],["Branch 2",800]], {"library":{"is3D":true,"pieSliceText":"value"}});
</script>

```

Hope this helps. Surprisingly, the JS code generated looks the same, wonder why the behavior is different.

Thanks,
Leena

**Comment by ankane** [comment]
I get the same chart with both sets of code. I'd double check there aren't two charts with the same id on the page, as the 2nd one will override the first.

**Comment by leenasn** [comment]
@ankane thank you for the tip. That was my problem, I had multiple charts on the page. It started working when I commented everything and had only one.

Any tip on how to fix the same?

**Comment by ankane** [comment]
The settings work fine with multiple charts. You just need to make sure they don't have the same id.
