### ISSUE TITLE
Point tooltip with no label

### ISSUE THREAD

**Issue by JasonBarnabe** [ankane/chartkick#455]
Using `area_chart` I can set `label: 'Clicks'` so that the tooltip for points shows "Clicks: 123". What if I don't want any prefix here and just want to show "123"?

`label: nil` -> "Value: 123"
`label: ''` -> "Value: 123"
`label: ' '` -> " : 123"

**Comment by ankane** [comment]
Hey @JasonBarnabe, for Chart.js, there isn't a default label with Chartkick 2.0. For other charting libraries, there's no way to remove the label.
