### ISSUE TITLE
Get chart element on click

### ISSUE THREAD

**Issue by shazam1453** [ankane/chartkick#463]
Hey,

Was wondering if this is supported or not because I can't find documentation relating to chartkick--I want to be able to click on one of these slices and get the underlying slice data [Workstation, 9] or something along those lines (want to pass to the controller on click to get a list of the specific workstations making up the slice):

<img width="797" alt="screen shot 2018-11-26 at 6 34 13 pm" src="https://user-images.githubusercontent.com/26695836/49048756-ee06f300-f1a9-11e8-86ea-9f65ca6de19f.png">

It seems possible using chart.js--I've seen variations where people trigger alerts onclick using this API:

 https://www.chartjs.org/docs/latest/developers/api.html#getelementatevente

but don't see how to access a chartkick object via a chart.js API.  Let me know if there's something obvious I'm missing!

**Comment by ankane** [comment]
Hey, it may be supported through the `library` option, but I've never tried it. You can use the JavaScript API to get the Chart.js object from Chartkick, as well as access Chartkick charts.

https://github.com/ankane/chartkick#javascript-api

**Comment by shazam1453** [comment]
Sorry for taking so long to get back--didn't realize that API was grabbing the Chart.js object, but that helped!  In case anyone needs basic code to grab the label of their chart, this worked for me:

```
clickHandler = (evt) ->
  chart = Chartkick.charts['chart-1'].getChartObject()
  firstPoint = chart.getElementsAtEvent(evt)[0]
  console.log(chart)
  if firstPoint
    label = chart.data.labels[firstPoint._index]
    value = chart.data.datasets[firstPoint._datasetIndex].data[firstPoint._index]
    console.log("Label: " + label + "Value: " + value)
  return
```
