### ISSUE TITLE
Feature Request: Support for Chart.js Combo Bar Line Charts

### ISSUE THREAD

**Issue by jdefrance-stessa** [ankane/chartkick#467]
Sample Preview:
https://www.chartjs.org/samples/latest/charts/combo-bar-line.html

Is it already achievable today? Without losing ability to stack the bars eventually? 
Couldn't find out how therefore ended up - so far - using charts.js directly.
However, would love to leverage chartkick for this. 

![image](https://user-images.githubusercontent.com/44618880/49772749-45758a80-fca3-11e8-89fa-58e117770baf.png)

**Comment by ankane** [comment]
Hey @jdefrance-stessa, see #382, #270, and #79.
