### ISSUE TITLE
Rails number_to_human_size problem

### ISSUE THREAD

**Issue by emrahyildirim** [ankane/chartkick#468]
Hi,

Number_to_human_size is doing the calculation, but does not add KB, MB, GB, TB  to the end.

`<%= line_chart Item.group_by_month(:created_at).sum(:download).map{|k,v| [k, number_to_human_size(v)]} %>`

Thanks!

**Comment by ankane** [comment]
Hey @emrahyildirim, the value must be numeric for all the charts, as the chart doesn't know how to interpret "5 MB" vs "5 GB".

**Comment by ankane** [comment]
Lol, aren't you a coder?

**Comment by emrahyildirim** [comment]
I'm a network and system specialist. I'm too weak on the code. I'm new to ROR.

**Comment by emrahyildirim** [comment]
You misunderstood. Thanks anyway.
