### ISSUE TITLE
undefined method `sanitize_sql_array' for

### ISSUE THREAD

**Issue by WWGate** [ankane/chartkick#472]
Hello,

This is the first time I use chatkick and I tried to create the example from the documentation by adding this line to my app

`<%= line_chart User.group_by_day(:created_at).count %>`

it gives this error
`undefined method `sanitize_sql_array' for #<User::ActiveRecord_Relation:0x00007f4a9369c1b8>
Did you mean?  sanitize_for_mass_assignment`

any help please

**Comment by ankane** [comment]
Hi @WWGate, that seems to be related to Groupdate. Can you paste the full stack trace?

**Comment by WWGate** [comment]
Thanks @ankane  for fast reply

Here it is

`activerecord (5.1.6.1) lib/active_record/relation/delegation.rb:125:in `method_missing'
activerecord (5.1.6.1) lib/active_record/relation/delegation.rb:95:in `method_missing'
groupdate (4.1.1) lib/groupdate/magic.rb:113:in `time_zone_support?'
groupdate (4.1.1) lib/groupdate/magic.rb:123:in `check_nils'
groupdate (4.1.1) lib/groupdate/magic.rb:73:in `perform'
groupdate (4.1.1) lib/groupdate/magic.rb:156:in `block in process_result'
groupdate (4.1.1) lib/groupdate/magic.rb:155:in `each'
groupdate (4.1.1) lib/groupdate/magic.rb:155:in `process_result'
groupdate (4.1.1) lib/groupdate.rb:22:in `process_result'
groupdate (4.1.1) lib/groupdate/relation.rb:13:in `calculate'
activerecord (5.1.6.1) lib/active_record/relation/calculations.rb:41:in `count'
app/views/warehouse/dashboards/_monthly_agents_visits.html.erb:3:in `_app_views_warehouse_dashboards__monthly_agents_visits_html_erb___750525210391326310_69921183613920'
actionview (5.1.6.1) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.6.1) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.6.1) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.6.1) lib/action_view/template.rb:155:in `render'
actionview (5.1.6.1) lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
actionview (5.1.6.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.6.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.6.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.6.1) lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
actionview (5.1.6.1) lib/action_view/renderer/partial_renderer.rb:310:in `render'
actionview (5.1.6.1) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (5.1.6.1) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (5.1.6.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
app/views/warehouse/dashboards/index.html.erb:77:in `_app_views_warehouse_dashboards_index_html_erb__1852275452669361493_47140369845540'
actionview (5.1.6.1) lib/action_view/template.rb:157:in `block in render'
activesupport (5.1.6.1) lib/active_support/notifications.rb:168:in `instrument'
actionview (5.1.6.1) lib/action_view/template.rb:352:in `instrument_render_template'
actionview (5.1.6.1) lib/action_view/template.rb:155:in `render'
actionview (5.1.6.1) lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
actionview (5.1.6.1) lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
activesupport (5.1.6.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (5.1.6.1) lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
actionview (5.1.6.1) lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
actionview (5.1.6.1) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
actionview (5.1.6.1) lib/action_view/renderer/template_renderer.rb:50:in `render_template'
actionview (5.1.6.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.6.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.6.1) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.6.1) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.6.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (5.1.6.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.6.1) lib/action_controller/metal/rendering.rb:52:in `render_to_body'
actionpack (5.1.6.1) lib/action_controller/metal/renderers.rb:141:in `render_to_body'
actionpack (5.1.6.1) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.6.1) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.6.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (5.1.6.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/fadi/.rbenv/versions/2.5.3/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
activesupport (5.1.6.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.6.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (5.1.6.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (5.1.6.1) lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
actionpack (5.1.6.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (5.1.6.1) lib/action_controller/metal/implicit_render.rb:33:in `default_render'
actionpack (5.1.6.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.1.6.1) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.6.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.1.6.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.1.6.1) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.6.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.6.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.6.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.1.6.1) lib/active_support/notifications.rb:166:in `block in instrument'
activesupport (5.1.6.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.1.6.1) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.6.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.1.6.1) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
activerecord (5.1.6.1) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
actionpack (5.1.6.1) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.6.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.6.1) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.6.1) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.6.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.6.1) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.6.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.6.1) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.6.1) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.6.1) lib/action_dispatch/routing/route_set.rb:844:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.6.1) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.6.1) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.6.1) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.6.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.6.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.6.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.6.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.6.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.6.1) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.6.1) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.1.6.1) lib/rails/engine.rb:522:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'`

**Comment by ankane** [comment]
Not sure why that method doesn't exist, but from the code path, it looks like your database is missing time zone support. Be sure to follow the instructions in the Groupdate readme.

**Comment by ankane** [comment]
Should be fixed on Groupdate master. https://github.com/ankane/groupdate/commit/500e67306e4a0b2047a52f5baf16bb653407ea9e

**Comment by WWGate** [comment]
worked perfectly :+1: 

Thank you @ankane

**Comment by ankane** [comment]
Thanks for reporting 👍
