### ISSUE TITLE
Add an option for disabling default background opacity globally

### ISSUE THREAD

**Issue by bbugh** [ankane/chartkick#473]
Hi there, thanks for Chartkick, it makes charting easy. 

We have a set of default colors that are themed for our site, but when using them noticed that some charts (stacked column most recently) don't look very good because there's a partial opacity instead of a solid fill color. 

I dug around in ChartJS and couldn't find any options to disable the outline colored, and thought I was going a bit crazy until I saw [this code](https://github.com/ankane/chartkick/blob/0a066f97f44d1450c63d339131d21af8083dd6a6/vendor/assets/javascripts/chartkick.js#L589), which forces the opacity of `backgroundColor` to 50%, with no options to disable. Even if we pass colors per-chart, this code still forces the background color to be transparent. If there's some way to force it through the `library` options, that's still suboptimal as we have a lot of charts we'd have to specify it for.

Can you (or we, with a PR) add global option to either disable the opacity setting, or have a 0-1 scale setting so we can set it to 100% opaque?

Thank you!

**Comment by ankane** [comment]
Hey @bbugh, I don't think this is common enough to add. It's probably easiest to fork the project and change that line for your app.

**Comment by bbugh** [comment]
Thanks for the response @ankane! Yeah, forking is *possible*, but that's never ideal for getting out of sync and having to manage the package, especially for something so small. We picked chartkick because of the good (but overridable) defaults, and now that we're so invested it's tough to have this one small thing hold us up. 😢

This seems to me like a "convention over configuration" snafu, where we're missing the configuration option. This behavior isn't the default of the chart platforms, it's an opinionated design setting, and it would be nice if the library allowed us to change it. As far as I can tell it would be a SemVer-safe small tweak to add an option for opacity. 

We'd love if you'd consider a PR. Thanks for hearing my petition!

**Comment by ankane** [comment]
Hey @bbugh, as I mentioned before, I don't think it's common enough to support.
