### ISSUE TITLE
Can we remove/customise the text of tooltip?

### ISSUE THREAD

**Issue by aruprakshit** [ankane/chartkick#475]
Hi,

Can we remove/customise the text of tooltip? Right now I see it like:

<img width="691" alt="screenshot 2019-02-27 at 1 51 31 am" src="https://user-images.githubusercontent.com/3428463/53443689-444a3300-3a32-11e9-86c4-d9f52c3ba19c.png">

I want to remove the "Total Cost" text before 400. My code:

```ruby
def project_cost_breakdown
  # ... 
  @column_chart_data = [
    {
      name: "Budget & cost overrun",
      data: [['Budget & cost overrun', 100], ['Total cost', 300]]
    },
    {
      name: "Total cost",
      data: [['Budget & cost overrun', 400]]
    }
  ]

  respond_to do |format|
    format.html
  end
end
```

and rendered it like:

```slim
= column_chart @column_chart_data, stacked: true, title: 'Total cost vs. Budget',  prefix: '$'
```

It will be good if we can add the color of the column in place of the text "Total Cost". It should look like https://www.dropbox.com/s/db4tu7wsa5a9q7x/Screenshot%202019-02-26%20at%2010.00.27%20PM.png?dl=0 .

**Comment by ankane** [comment]
Hey @aruprakshit, Chartkick doesn't provide any helpers for customizing tooltips. You can try using the `library` option for it.

**Comment by aruprakshit** [comment]
@ankane Where it is documented could you please point me there?
