### ISSUE TITLE
Cannot read property 'redraw' of undefined

### ISSUE THREAD

**Issue by Kuassari** [ankane/chartkick#478]
After I checked every issue here and on Google but didn't found an answer, I ask here.
I have a problem when I go between pages in my app that Chartkick.charts[chart_id] is undefined, but when I refresh the page or change window size it's fixed. What's weird is that it draws the chart but it's compressed and small
I really don't know what's wrong.

in application.js:
   //= require chartkick
   //= require highcharts (I have file in vendor)

in gemfile:
   gem 'chartkick'

in html.haml file:
   = javascript_include_tag "//www.google.com/jsapi", "chartkick"
   ...
   ...
   :javascript
     $('.la_row').click(function(){
    var $chart_row = $(this).nextUntil('tr.la_row');
    $chart_row.toggle();
    setTimeout(function(){
      var chart_id = $chart_row.find(".highcharts-container").parent().attr("id"); // <- return a value
      var chart = Chartkick.charts[chart_id];  // <- undefined
      chart.redraw();
    }, 100);
  });

**Comment by ankane** [comment]
Hey @Kuassari, check out the Contributing Guide for where to get help with code.
