### ISSUE TITLE
charts not loading after turbolinks:load with option defer: true

### ISSUE THREAD

**Issue by ubugnu** [ankane/chartkick#480]
Don't know why, but using simply:
`gem 'chartkick'`
in Gemfile installs an old version that does not hold patch 52a2728e6667902b8aac3315b73214b5828491eb. So we must specify github path to get the patched version:
`gem 'chartkick', git: "https://github.com/davegudge/chartkick"`
after a `bundle` the misbehaviour dissapears.

**Comment by ankane** [comment]
Hey @ubugnu, that commit was never merged. `defer` shouldn't be used with Turbolinks.

**Comment by marckohlbrugge** [comment]
Hi @ankane could you elaborate on why Turbolinks should not be used with `defer`? From what I've read people are actually using Turbolinks with `defer: true` successfully, myself included.

Right now it's only `Chartkick` which isn't working for me. It works fine when loading the page directly (as I did add `defer: true` to the charts), but when visiting the page through Turbolinks the charts aren't loaded.

I added the following code snippet as a temporary workaround, but it seems a bit hacky. The proposed patch (`52a2728`) seems like a cleaner solution.

```
document.addEventListener("turbolinks:load", function() {
  Chartkick.eachChart( function(chart) {
    chart.redraw();
  });
});
```

**Comment by ankane** [comment]
@marckohlbrugge The `defer` option only listens for the page load event, which is why you're seeing that behavior. Feel free the use that patch if it works for you, but charts should work with Turbolinks without the `defer` option.

**Comment by ankane** [comment]
Just pushed a new `edge` branch with an improved `defer` approach (no inline JavaScript). Let me know how it works for you:

```ruby
gem 'chartkick', github: 'ankane/chartkick', branch: 'edge'
```

**Comment by marckohlbrugge** [comment]
**It works!** Chartkick now works fine with deferred Turbolinks. 🎉
