### ISSUE TITLE
Decimal and prefix not working?

### ISSUE THREAD

**Issue by maxiedaniels** [ankane/chartkick#483]
Currently using highcharts.

Code is:

`<%= line_chart [data_goes_here], points: true, prefix: "$", decimal: ".", legend: true, curve: true, width: "1200px", height: "800px"`

Yet my graphs still come out with no prefix, and a comma for the decimal separator.

**Comment by ankane** [comment]
Hey @maxiedaniels, make sure on the latest version of Chartkick.
