### ISSUE TITLE
Callback on refresh in remote source

### ISSUE THREAD

**Issue by inyerade** [ankane/chartkick#484]
I use a enpoint with the refresh option, this works perfect, but I need to update a html text every refresh. I think to use some like "change" but I do not found.

My workaround is some like this:

   ```
     $( document ).ajaxComplete(function( event, xhr, settings ) {
            var text = "Update";
            if( settings.url.search( endpoint_URL) == 0){
                $("#text").html( text );
            }
        });
```
I think a refresh/draw callback can be a good option

**Comment by ankane** [comment]
Hey @inyerade, thanks for the suggestion. I don’t think this situation is common enough to warrant adding a new hook right now.
