### ISSUE TITLE
Getting empty element on click

### ISSUE THREAD

**Issue by rept** [ankane/chartkick#486]
I create my chart like this:

`= line_chart @parameter.grouped_data(@period, {date: @date}), suffix: ' ' + (@parameter.parameter_type.unit || ''), discrete: true, id: "param-chart"`

and use the following code to hook an onClick event to the chart after creation:

```
if ($('#param-chart').length > 0) {
  chart = Chartkick.charts['param-chart'];
  document.getElementById('param-chart').onclick = function(evt) {
    var activePoint;
    activePoint = chart.getChartObject().getElementAtEvent(evt);
    if (activePoint.length) {
      return console.log(activePoint);
    }
  };
}
```

I also tried: chart.chart.getElementAtEvent(evt);

but I'm always getting back an empty array.

When going through the chartjs code I see on this line:

```
module.exports = {
	// Helper function for different modes
	modes: {
		single: function(chart, e) {
			var position = getRelativePosition(e, chart);
```

The position X and Y are both NaN.  Is it possible that somehow the coordinates aren't correctly translated?  

BTW If this is not a ChartKick issue just let me know and I'll close it.  I've used ChartJS without ChartKick in other projects and the code always worked for me, that's why I'm not sure.

Thanks.

**Comment by ankane** [comment]
Hey @rept, check out the Contribute Guide for where to get help with your code.
