### ISSUE TITLE
Bar chart Y-axis labels regression

### ISSUE THREAD

**Issue by cernyjakub** [ankane/chartkick#490]
There is a regression with Y-axis labels on bar chart. On 3.0 all is OK, upgrading to 3.1 or 3.2 is skipping some labels. Only happens with 5 or more items in the dataset.

Example:

`bar_chart [['a',1],['b',2],['c',3],['d',2],['e',1]]`

Result in 3.0:

![chart (4)](https://user-images.githubusercontent.com/442576/59020834-0f2c5880-884b-11e9-948e-753d9aecd966.png)

Result in 3.1 and 3.2:

![chart (3)](https://user-images.githubusercontent.com/442576/59020858-1a7f8400-884b-11e9-9d9e-d6d8bf81752a.png)

Happens with Chart.js adapter - so probably caused by using new Chart.js version.

**Comment by ankane** [comment]
Hey @cernyjakub, thanks for reporting 👍 Fixed on master.

**Comment by mitchell-green** [comment]
Hi @ankane 👋. Thanks for fixing this 🙏. Any idea when these changes will be released in a new version of the gem?

**Comment by rileyradoll** [comment]
Hey @ankane Thanks a lot, happy to see this is fixed. I'm also wondering, do you have an idea when an updated version of the gem will be released?

**Comment by ankane** [comment]
Just pushed a new version.

**Comment by rileyradoll** [comment]
@ankane Thanks again!
