### ISSUE TITLE
Chartkick stuck at loading when trying to load new chart with ujs without using jquery

### ISSUE THREAD

**Issue by BakiVernes** [ankane/chartkick#491]
Hi,

So in my project I have a chart that show up on page load. After that there are multiple options and the chart refreshes by clicking on one of those options. The refresh utilizes rails-ujs and it works fine when using jQuery like this:
`$("#graph").html('<%= j render("graph", history_graph: @history_graph )%>');`
But when trying this without jQuery like this:
`document.getElementById("graph").innerHTML = '<%= j render("graph", history_graph: @history_graph )%>'`
the graph just says "Loading..." and nothing happens. I've tried looking into jQueries .html() method and executing the code directly without any luck. Also tried the insertAdjacentHTML method with the same result. Anyone have any idea?

Versions:
  Rails 5.2
  Latest chartkick

**Comment by ankane** [comment]
Hey @BakiVernes, please check out the Contributing Guide for where to get help with code.
