### ISSUE TITLE
Multiple series order

### ISSUE THREAD

**Issue by rept** [ankane/chartkick#492]
I use a multiple series like the example specifies:

        = column_chart @grouped_data.map { |p1_param| {name: p1_param[:desc], data: p1_param[:data]} }

This is how the data looks like.  I never know which values will appear first.

![data](https://user-images.githubusercontent.com/1388221/60016133-95d39900-9685-11e9-8276-9f6687da39bf.jpg)

The resulting chart is this:

![chart](https://user-images.githubusercontent.com/1388221/60016206-c87d9180-9685-11e9-88c1-ad3b0caca460.jpg)

6u and 7u are displayed first, although 0u, 1u, 2u, 3u, 4u, 5u should appear first.

Is there a way to have it sorted like that or should I manually insert 0 values for missing keys?

**Comment by ankane** [comment]
Hey @rept, check out https://github.com/ankane/chartkick/issues/392
