### ISSUE TITLE
Can spaces in line_chart name control if it uses Time range or Names?

### ISSUE THREAD

**Issue by viktorsmari** [ankane/chartkick#494]
When using no space in the `Test2` string:
`<%= line_chart [['Test 1', 0.143],['Test2', 0.148]] %>`

![2019-06-28_15-19-46](https://user-images.githubusercontent.com/1689020/60345053-617b1800-99b8-11e9-922f-2ccee9c8822d.png)
*Look at the bottom axis*

And when using a space in `Test 2` string:
`<%= line_chart [['Test 1', 0.143],['Test 2', 0.148]] %>`
![2019-06-28_15-21-28](https://user-images.githubusercontent.com/1689020/60345069-6dff7080-99b8-11e9-86f2-743f100197f0.png)

When looking at the bottom axes, one shows the Date, the other shows the name.

The **objective** is to to something like this:
![2019-06-28_15-25-20](https://user-images.githubusercontent.com/1689020/60345292-fb42c500-99b8-11e9-9f5d-e7cbb9ae6abd.png)

**Comment by ankane** [comment]
@viktorsmari It looks like `Test 1` and `Test 2` parse as a valid dates in JavaScript (with `new Date(...)`), so it's treated as a date/time axis. You can use `discrete: true` to force a discrete/categorical axis.

**Comment by viktorsmari** [comment]
Thanks, that solved it.
I read the docs but it was not clear to me what `discrete` does.
