### ISSUE TITLE
Find the way to make a mirror horizontal bar chart 

### ISSUE THREAD

**Issue by tifafracica** [ankane/chartkick#496]
Hi guys, maybe someone need a mirror bar chart. i make it in this way:

``<div style="display: flex;">
                  <div class="bar-chart">
                    <%= bar_chart @linechartdata,
                    colors: ["#ea3732"],
                    id: "bar-chart", width: "220px", height: "300px",
                    library: {
                        
                        scales: {
                          xAxes: [{
                            gridLines: {
                              display: false,
                              drawBorder: false,
                              barThickness: 6,  
                              maxBarThickness: 8

                            },
                            ticks:{
                              display: false,
                              reverse: true,
                            }
                            
                          }],
                          yAxes: [{
                            gridLines: {
                              display: false,
                              drawBorder: false,
                              barPercentage: 0.1
                              
                              
                            },
                            ticks:{
                              display: false,
                              reverse: true,
                            }
                            
                          }]
                        
                      }
                    }
                    %>
                  </div>
                  <div class="bar-chart2">
                    <%= bar_chart @linechartdata,
                    colors: ["#4bb2bd"],
                    id: "bar-chart2", width: "220px", height: "300px",
                    library: {
                        backgroundColor: "green",
                        scales: {
                          xAxes: [{
                            gridLines: {
                              display: false,
                              drawBorder: false,
                            },
                            ticks:{
                              display: false,
                            }
                            
                          }],
                          yAxes: [{
                            gridLines: {
                              display: false,
                              drawBorder: false,
                            },
                            ticks:{
                              mirror: false,
                              display: false,
                            }
                            
                          }]
                        
                      }
                    }
                    %>
                  </div>
                </div>
            </div>
`

in the CSS
`.bar-chart2{
  margin-left: -10px;
}`

final result
![image](https://user-images.githubusercontent.com/42949898/61400420-963b0a80-a8a6-11e9-89b4-5bb41a82b1e6.png)

iI hope this information can be useful to someone who needs it.

**Comment by ankane** [comment]
Hey @tifafracica, thanks for sharing 👍 Going to close, but this should show up on Google and GitHub search.
