### ISSUE TITLE
[Idea] Remove forced stacking on area charts

### ISSUE THREAD

**Issue by AdmSteele** [ankane/chartkick#498]
I was unable to remove stacking on area charts using chartkick for highchairs without forking the repo and removing the lines from chartkick.js where it is being hardcoded to on: https://github.com/AdmSteele/chartkick/commit/0def95cede718644e09bbe51c5ece695f71094cc ...unless I am missing something, there is no other way to turn stacking off for area charts using chartkick.

With those lines removed, it then defaults to no stacking, and it can still be easily enabled in the library options if needed. This way would certainly be better for my case. Thoughts?

**Comment by ankane** [comment]
Hey @AdmSteele, thanks for reporting. This is a bug with `stacked: false`. Fixed in https://github.com/ankane/chartkick.js/commit/78df4c0320dee5c18b846a320020991aaccd5530
