### ISSUE TITLE
Using global.timezoneOffset to set a Time Zone with Highchart

### ISSUE THREAD

**Issue by Phazz** [ankane/chartkick#50]
Thanks for the useful library.
I am looking to use this feature of Highchart:
http://highcharts.uservoice.com/forums/55896-general/suggestions/2542204-set-timezone

See the example:
http://jsfiddle.net/highcharts/y6Q7p/

What would be the best way to use this with chartkick ?

Thanks again,

**Comment by yush93** [comment]
What is the equivalent for rails?
