### ISSUE TITLE
customize x axis y axis key

### ISSUE THREAD

**Issue by lastlink** [ankane/chartkick#500]
Is it possible to read the x-axis and y-axis from a key rather than having parse into an array that works? https://www.chartjs.org/docs/latest/charts/line.html#dataset-properties

**Comment by ankane** [comment]
Hey @lastlink, I don't fully understand the question, but if it's not in the readme, you'll need to use the `library` or `dataset` option for it.

**Comment by lastlink** [comment]
From what I can tell for the line graph it uses an array of 2 value arrays e.g. [[1,1]]. it would be great if it would use keys from an array of objects [{xvalue:"",yvalue:""}]

**Comment by ankane** [comment]
Ah, I see. Unfortunately, I think this will conflict with multiple series. What's the reason for wanting support for another data format?

**Comment by ankane** [comment]
Cleaning up issues
