### ISSUE TITLE
Unable to use endpoints for charts

### ISSUE THREAD

**Issue by rlgreen91** [ankane/chartkick#501]
Hello,

I'm trying to use individual endpoints to render my charts.  For context, I have a page containing the charts located at `app/views/analytics/index.html.erb` and a corresponding `AnalyticsController`.  However, I run into an error `undefined local variable or method` each time I try to load the page.

Is there a particular format I should be following to have it recognize the path?  I have a custom endpoint `visits_by_day` - should I refer to it in the view as `visits_by_day_charts_path` or `visits_by_day_analytics_path` or something else?  The first two options yield that undefined error.

**Comment by ankane** [comment]
Hey @rlgreen91, please check out the Contributing Guide for where to get help.
