### ISSUE TITLE
Polar area charts in vue.js is posible???

### ISSUE THREAD

**Issue by tifafracica** [ankane/chartkick#503]
Hi guys!

It's a very good chart gem! I love it!

I working with Vue.js and I need do a Polar-area Chart but I very confused and I don't know how do it. someone can't teach me??

![image](https://user-images.githubusercontent.com/42949898/63701308-16845200-c7fb-11e9-931e-e6e4d0d71faa.png)

thanks!

**Comment by ankane** [comment]
Hey @tifafracica, Chartkick doesn't support polar charts. For Vue.js, I'd check out https://github.com/apertureless/vue-chartjs.
