### ISSUE TITLE
Width 100% is not respected with bootstrap

### ISSUE THREAD

**Issue by iraszl** [ankane/chartkick#504]
I'm not sure if this is a bug, but I think it is. If I put the chart into a bootstrap 4 column, with the option: width: "100%", the chart will fill out the whole page width instead of remaining with the column.

Example code in haml:
```
.container
  .row
    .col-lg
      area_chart @data, width: "100%"
    .col-lg
      some other content in the second column
```

**Comment by ankane** [comment]
Hey @iraszl, the `width` option just adds it to the style of the div, so don't think it's an issue with Chartkick.
