### ISSUE TITLE
Chartkick and special groupdate

### ISSUE THREAD

**Issue by ferdi2005** [ankane/chartkick#505]
`<%= line_chart Creator.all.group_by_day { |u| u.photos.first.created_at }.count, xmin: '2019-09-01', xmax: '2019-09-30'%>
`
doesn't work because this returns to Chart.js only the number 2 and not the array.

**Comment by ankane** [comment]
Hey @ferdi2005, please check out the Contributing Guide for where to get help.

**Comment by ferdi2005** [comment]
Isn’t this a bug? This function is documented.
