### ISSUE TITLE
Pie Chart Colors turns black when upon hover 

### ISSUE THREAD

**Issue by bahijmansour** [ankane/chartkick#506]
Using Chartkick with Vuejs to display Pie Chart and changing colors attribute is working well like this: 
`<pie-chart :data="pieChartData"  :colors="colorsData"></pie-chart>`

This is the index.js part working fine :
```
// Pie-chart
        pieChartData: [
           ['Bananas', 25], ['Strawberry', 25], ['Blueberry', 25],['Apples', 25]
        ],
        
        colorsData: [
           ["yellow"], ["red"], ["blue"],["green"]
        ],
```

Screenshot of the displayed graph: 
![image](https://user-images.githubusercontent.com/44373615/64267240-f442b080-cf2d-11e9-921d-e36fd7aab688.png)

However when I hover my pointer on the graph color turns black:
![image](https://user-images.githubusercontent.com/44373615/64267313-16d4c980-cf2e-11e9-898d-5708161f6b6a.png)

Is there a way of setting color upon hover like default graph does? I noticed default graph changes transparency upon hover?

**Comment by ankane** [comment]
Hey @bahijmansour, colors should be an array, not an array of arrays.

```js
colorsData: ["yellow", "red", "blue", "green"]
```
