### ISSUE TITLE
React Chartkick Chartjs Xaxis line and number missing

### ISSUE THREAD

**Issue by milyaswearenova** [ankane/chartkick#507]
I am creating a chart and it misses few xaxis lines as shown in the attached image. I tried different options properties available in chartjs and chartkick but its not getting fixed.

![image](https://user-images.githubusercontent.com/55190397/64693987-01bde480-d4b2-11e9-912a-2425228c4e3b.png)

**Here is the react code:**

import React from 'react';
import { LineChart } from 'react-chartkick';
import 'chart.js';

let data = [
  {
    name: 'Category 1',
    data: { '25-May-19': 2.88, '01-Sep-19': 1, '05-Sep-19': 1 }
  },
  {
    name: 'Category 2',
    data: { '25-May-19': 2.76, '01-Sep-19': 5, '05-Sep-19': 5 }
  },
  {
    name: 'Category 3',
    data: { '25-May-19': 3.44, '01-Sep-19': 5, '05-Sep-19': 5 }
  },
  {
    name: 'Category 4',
    data: { '25-May-19': 3.99, '01-Sep-19': 1, '05-Sep-19': 1 }
  },
  {
    name: 'Category 5',
    data: { '25-May-19': 4.12, '01-Sep-19': 5, '05-Sep-19': 5 }
  },
  {
    name: 'Category 6',
    data: { '25-May-19': 2.8, '01-Sep-19': 5, '05-Sep-19': 5 }
  },
  {
    name: 'Category 7',
    data: { '25-May-19': 3.86, '01-Sep-19': 5, '05-Sep-19': 5 }
  }
];

export default function ProgressGraph(props) {
  return (
    lt&; LineChart data={data} curve={false} adapter="chartjs" min={1} max={5} /gt&;
  );
}

**Comment by ankane** [comment]
Hey @milyaswearenova, you'll need to use the `library` option if you'd like to customize the gridlines. Check out the Contributing Guide for where to get help.
