### ISSUE TITLE
Chart flicker with cached turbolinks and remote url

### ISSUE THREAD

**Issue by mmccall10** [ankane/chartkick#509]
With turbolinks cached pages and using a remote url charts will load for split second (including animations), render "Loading...", then render the chart after the ajax request.  I haven't found a good solution to get around this yet. 

I have tried something like this:
```javascript
document.addEventListener('turbolinks:before-cache', function () {
  Chartkick.eachChart((chart) => {
    let chartObject = chart.getChartObject();
    if (chartObject) {
      chartObject.destroy()
    }
  })
});
```
This works some of the time. Outside of turning off the turbolinks cache is there a recommended way to get around this or have chartkick use the existing page element for the html option and redraw without showing the default loading? Looks like this might be similar to #390 .

**Comment by aledalgrande** [comment]
Seems like the solution is adding this to your `<head>`:
```html
<meta name="turbolinks-cache-control" content="no-preview">
```
You won't see the cache previews any more, which is what is causing the double load and flicker.

**Comment by mmccall10** [comment]
@aledalgrande ahhhh good catch. Thank you!

**Comment by ankane** [comment]
Hey @aledalgrande, thanks for sharing!
