### ISSUE TITLE
Not working with webpacker

### ISSUE THREAD

**Issue by perezperret** [ankane/chartkick#510]
After following the instructions exactly as in the readme, I still get a "Chartkick not defined" error

**Comment by ankane** [comment]
Hey @perezperret, unfortunately, I'm not sure how to reproduce as it works fine with a fresh Rails app. A few things to try:

1. Make sure you're using the latest version of Chartkick
2. Make sure you're using the latest version of Chartkick.js
3. Make sure the pack you add the `require` lines to is included on pages with charts

**Comment by perezperret** [comment]
Hey, I'm really sorry. I published the issue by accident and I still needed to do some research to add context. Thanks for your prompt reply. It was an unrelated issue. For what it's worth. I had a css and a js pack both named "application" and that was causing webpacker not to load the js one.

**Comment by ankane** [comment]
Hey @perezperret, glad it's working and thanks for sharing what you found. I'm sure it'll help someone in the future.
