### ISSUE TITLE
[Idea] Add ability to have multi-colored line charts

### ISSUE THREAD

**Issue by snex** [ankane/chartkick#513]
It would be nice if there were an option to have different colored line segments in a line chart based on some attribute of each data point.

For example, you are charting daily temperatures, and on days where it rained, you want to color the line segments differently than days where it was sunny. This enables users to quickly see possible trends in temperature based on the weather (i.e. temperature always falls when it rains).

Thank you.

**Comment by ankane** [comment]
Hey @snex, thanks for the suggestion. I think it's probably not common enough to add to Chartkick, but it looks like you can do it with Chart.js: https://stackoverflow.com/questions/35249498/how-to-change-line-segment-color-of-a-line-graph-in-chart-js
