### ISSUE TITLE
How to use dates in line chart when some are missing?

### ISSUE THREAD

**Issue by georgeu2000** [ankane/chartkick#514]
I have data in the following format:

```
{
        "date" => "2019-10-21",
        "count" => 2
    },
{
        "date" => "2019-11-02",
        "count" => 5
    }
```

And would like to create a line chart with dates as the X axis. But some of the dates are missing (as you can see).

I see there is a way to do it with GroupDate `series: false`, but this app uses Mongoid and GroupDate does not seem to work with it.

So, is there a way to pass a set of points to Chartkick or another way of doing this?

Thank you!

**Comment by ankane** [comment]
Hey @georgeu2000, you can use Groupdate on arrays and hashes with `series: true`.

**Comment by georgeu2000** [comment]
Thanks for your quick reply!

I'm not sure if I am using groupdate correctly. I have:

    data = {
        "date" => "2019-10-21",
        "count" => 2
    },
    {
        "date" => "2019-11-02",
        "count" => 5
    }

    data.group_by_day(series: true){| g | g[:date] }

that emits 

```
    Fri, 01 Nov 2019 => [],
    Sat, 02 Nov 2019 => [
        [0] {
            "count" => 5,
             "date" => "2019-11-02"
        }
    ]
```

Which is OK, but then I have:

    .map{| date, ary | [ date , ary&.first&.dig('count') || 0 ]}
    .to_h

to coerce it into the correct format for Chartkick.

Is this the best way to do it?

**Comment by ankane** [comment]
@georgeu2000 Yeah, that's more or less how I would do it.
