### ISSUE TITLE
Tooltip not showing in chrome but showing in firefox

### ISSUE THREAD

**Issue by hkleow** [ankane/chartkick#515]
Hi guys i have a strange bug. My line graph tool tip is not showing on google chrome but its working on firefox 
<img width="327" alt="Screen Shot 2019-11-14 at 3 25 13 PM" src="https://user-images.githubusercontent.com/15167345/68835513-3852ee00-06f3-11ea-929c-0e6e48fc7a2a.png">
<img width="269" alt="Screen Shot 2019-11-14 at 3 25 24 PM" src="https://user-images.githubusercontent.com/15167345/68835526-3d17a200-06f3-11ea-9f6a-226ca2db55b3.png">
is there anything i did wrong? :/

`<%= line_chart get_graph_project_path(session[:keyword_id]), colors: ["#2196f3"], min: 1, max: 100,discrete: true, legend: false, messages: {empty: "No Ranking Yet... :("} ,library: { 
  scales: {
    yAxes: [{
      ticks: {
        reverse: true,
      },
      allowDecimals: false 
    }]
  }}, adapter: "chartjs" %>
`

**Comment by ankane** [comment]
Hey @hkleow, I'm not really sure how to reproduce. It may be related to other JavaScript on the page. Can you try reproducing with a fresh Rails app?

**Comment by hkleow** [comment]
Managed to fixed it. Not sure why, all the sudden it was working again, might be some javascript file conflicting it. :/
