### ISSUE TITLE
Reverse Y Axis but fill below the line

### ISSUE THREAD

**Issue by hkleow** [ankane/chartkick#518]
Hey guys, i am trying to fill below y axis line after i reverse, i tried to use area_chart but it would flipped the fill upside down instead. but somehow this stackoverflow managed to do it with chartjs, but i somehow can't replicate it, i tried put the fill: "start" in datasets:{} as shown on  https://chartkick.com/ but its still not working. any idea? thanks  

https://stackoverflow.com/questions/49173976/chart-js-reverse-y-axes-but-keep-background-fill-underneath-line

```
<%= line_chart get_graph_project_path(keyword_id), colors: ["#2196f3"], min: 1, max: 100,discrete: true, legend: false, messages: {empty: "No Ranking Yet... :("} , dataset: {fill: "start", backgroundColor: ['rgba(50, 66, 92, 0.3)' ]}, 
library: { 
  scales: {
    yAxes: [{
      ticks: {
        reverse: true,
      },
      allowDecimals: false 
    }]
  }}, adapter: "chartjs" %>
```

**Comment by ankane** [comment]
Hey @hkleow, please check out the Contributing Guide for where to get help.
