### ISSUE TITLE
Thanks for your amazing work!

### ISSUE THREAD

**Issue by replicat0r** [ankane/chartkick#519]
Hi! 

Just a small issue at bottom, I am a solo independent developer, and just doing my own small projects, I have been using this, blaze and ahoy to track user activity in my app. Honestly just wanted to say thank you for all your amazing contributions. These libs you have open sourced is probably one of the better gems/lib in the ruby ecosystem, using these libraries have greatly speed up my work flow and allow me to be productive in my very limited time!  

Thank you for all your hard work and actively maintaining these project, helping devs like me with our projects!! 

Just very quickly wanted to do a sanity check here, whats the proper way to enable localization? I am using rails 6 with webpacker, this is how my application.js looks

    import Chartkick from "chartkick";
     window.Chartkick = Chartkick;

    import Chart from "chart.js";
    window.Chart = Chart;

    Chartkick.configure({language: "es"})
    
But it does not seem to be working, am i missing something?

**Comment by ankane** [comment]
Hi @replicat0r, thanks for the note.

Re language: the `language` option only applies to Google Charts. Happy to accept a PR to set the time format for Chart.js.
