### ISSUE TITLE
[Idea] Stacked bar chart

### ISSUE THREAD

**Issue by Nikhil-Wagh** [ankane/chartkick#520]
The bar chart now works just fine. 
It would be great if you could implement stacked bar charts ([something like this](https://www.highcharts.com/demo/bar-stacked)).

**Comment by ankane** [comment]
Hey @Nikhil-Wagh, you should be able to use `stacked: true` for stacked bar charts.

**Comment by Nikhil-Wagh** [comment]
Is there any doc I can refer to?

**Comment by ankane** [comment]
Yes, search for "stacked" in the readme or on https://chartkick.com/
