### ISSUE TITLE
[Idea] New adapter based on D3.js

### ISSUE THREAD

**Issue by emacesa** [ankane/chartkick#521]
What do you think about adding a fourth adapter based on **D3.js**?

**Comment by ankane** [comment]
Hey @emacesa, thanks for the suggestion. Is there a D3 charting library you'd use?

**Comment by emacesa** [comment]
Hi Ankane thanks for your reply
I submitted this idea to you because my team and I are using your excellent gem in a very profitable way in various Rails projects. We use it mainly because with the same interface we choose the library to use; based on the need, we draw some charts with Highchart others with chart.js.
For our projects in the future we will have to use a Network-type graphic. Unfortunately Highchart (https://www.highcharts.com/docs/chart-and-series-types/network-graph) has bad performances for this type of chart and actually Chartkick does not support it explicitly.

With my development team for three months we started working on a javascript library, its name is EasyD3.js which allows you to create the same types of charts supported by Chartkick using simple calls to methods (like just **render_pie_chart(some_basic_options)**), avoiding the countless lines of js code required by D3 to get the simplest pie chart.

The same library already supports the network chart which on D3 has performances tens of times better than Highchart

In parallel we have developed EasyD3 a ruby ​​gem that allows you to integrate EasyD3.js into Rails through helpers calls.

These two projects are currently developed within our team and have not been released to the public domain for now.

Throughout the development we were inspired and we took your excellent Chartkick project as a model so that a possible integration was simpler

At present we have contacted you because there are 2 possible ways for us:
    • Begin to use the EasyD3 gem and EasyD3.js gradually in all our projects in parallel, slowly and progressively abandoning Chartkick
    • Write to you asking if you are available for this integration which would allow us to avoid abandoning Chartkick for all the cases in which we already use it now since we can have the network graphics available on D3 that we will need more and more in the future.

obviously we would prefer the second hypothesis
Hope I explained the needs..

**Comment by crondaemon** [comment]
Hi, I am part of @emacesa team. If we take the way of integrating, I see 2 possible scenarios:

1. use EasyD3.js as new rendering engine. Advantage: easier integration, less code for chartkick. Disadvantage: the rather new code lives outside chartkick, hence it will be less tested/fixed
1. use the EasyD3.js code straight into chartkick. Advantage: chartkick users will have direct contact with the glue code bringing to D3. Disadvantage: a LOT more code to add to chartkick.

To reduce the impact of the scenario 2, a split of the library could be put in place. Basically to date you have a single giant js file, with all the implementation for the 3 engines. Splitting it into 4 files (a main file + 1 file per engine), would not reduce the code, but at least would help developers of a single engine not to mess up with other engines code.

Let us know what you think, and thanks again for your effort.

**Comment by ankane** [comment]
Hey @emacesa and @crondaemon, thanks for the detailed explanation! It's probably best to release  it as a separate JS project and gem for now. It should allow you to iterate much faster on it, and from my side, maintaining support for another JS library adds a lot of work.

Chartkick.js does have experimental support for [adapters](https://github.com/ankane/chartkick.js#custom-adapters), but it's not well-documented, and I'm not sure if anyone has used it. Also, it doesn't support new chart types, which it sounds like you need.

**Comment by crondaemon** [comment]
Our idea is to provide you the code suitable for chartkick, in order to reduce the effort for the inclusion on your side. D3 is a really powerful library and I think chartkick would really benefit from this support. Releasing our code as separate libraries would require to migrate all our project, currently using chartkick, to EasyD3, because we don't want to have projects with multiple graphical libraries.

Would you reconsider the merge based on our availability to provide you support for D3?

**Comment by ankane** [comment]
I think it's better as a separate library.
