### ISSUE TITLE
loading chart from js erb Rails 6 (Ajax loading)

### ISSUE THREAD

**Issue by rupinder0007gill** [ankane/chartkick#524]
I am trying to reload the chart using Rails 6 js.erb Ajax call.
I have tried the solution from similar issue #193 but not working for me.

![image](https://user-images.githubusercontent.com/36261457/73942190-a8e56180-4914-11ea-83dd-dcbf9f50a24e.png)
Fig.1
chart load perfectly when the page loads.
__________________________________________________________

![image](https://user-images.githubusercontent.com/36261457/73942360-e77b1c00-4914-11ea-8e41-dfeee9f2d7ec.png)
Fig.2

Chart view after changing data range from a date picker and reloading through Ajax.
__________________________________________________________

![image](https://user-images.githubusercontent.com/36261457/73942507-31640200-4915-11ea-88d4-fe0372dddc83.png)
Code.1

code for loading chart through partial on the main page.

__________________________________________________________

![image](https://user-images.githubusercontent.com/36261457/73942737-94ee2f80-4915-11ea-813f-85b91f10340f.png)
Code.2

Partial code to create a chart.

__________________________________________________________

![image](https://user-images.githubusercontent.com/36261457/73942870-d088f980-4915-11ea-81dd-eb738c2b618a.png)
code.3 

Js erb code to reload chart.

__________________________________________________________

My Debug Notes:- It seems I am receiving the right data after ajax but the script to create chart is not being executed that comes along.
When I copy and paste the script in the browser console chart got created.

**Comment by ankane** [comment]
Hey @rupinder0007gill, `innerHTML` will not execute script tags, so you'll need to use a solution that does. Please check out the Contributing Guide for where to get additional help.
