### ISSUE TITLE
Feature request: autodisplay closest data to cursor on chart

### ISSUE THREAD

**Issue by yshmarov** [ankane/chartkick#525]
Hovering on a datapoint circle on a chart can be uncomfortable. 

It would be great to autodisplay the data from the closest datapoint from the mouse cursor:

![image](https://user-images.githubusercontent.com/13472945/74524473-637df100-4f1f-11ea-9c25-e968ecbfb92b.png)

**Comment by ankane** [comment]
Hey @yshmarov, thanks for the suggestion. This is already planned as the default for Chartkick 4 (https://github.com/ankane/chartkick/issues/489) but may add an option for it earlier since there's not a specific timeline yet.

**Comment by ankane** [comment]
Hey @yshmarov, decided to increase the `hitRadius` for Chartkick 4 instead of showing the closest point by default, but you can use this code to do it: https://github.com/ankane/chartkick/pull/528#issuecomment-623200836. Thanks for the suggestion!
