### ISSUE TITLE
Display only one entry of an table "Order" 

### ISSUE THREAD

**Issue by MrGrashopper** [ankane/chartkick#527]
Hi,

I want to display only one entry of an table Order (using HAML)
Something like this:

-orders.each do |order|
   = pie_chart order.group(:used_by,:packeges_ordered)
end

I get "undefined method `group' for #<Order:0x00007ff63f66f340>"

When I write "= pie_chart order" then my whole columns of this entry is displaying. But I only want to show 2/3 like used_by / packeges_ordered.

But I alwas get an error (Cannot group, endefined method for order etc.)
How can I limit the columns of only one entry? 

When I do it for mulitiple order everything works fine:
orders.group(:title).sum(:used_by)
orders.group(:title).group_by_month(:created_at, format: "%m %Y").sum(:price)

Maybe it's a rails issue idk.

Thank you

**Comment by ankane** [comment]
Hey @MrGrashopper, check out the Contributing Guide for where to get help.
