### ISSUE TITLE
Custom Color to each bars

### ISSUE THREAD

**Issue by dev-darenas** [ankane/chartkick#533]
I am using chartkick with google adapter and I have seen than Bar charts with google you can configure color for each bar, just need to add the color after the value, [ 'Tittle Bar', 10, 'blue' ], you can read about this here 

https://developers.google.com/chart/interactive/docs/gallery/columnchart#coloring-columns

but how can I custom bar color with chartkick, I tried with 

In the controller 
`
@data = [
        ["Copper", 8.94, "", "#b87333"],
        ["Silver", 10.49, "silver"],
        ["Gold", 19.30, "gold"],
        ["Platinum", 21.45, "color: #e5e4e2"]
]
`
in the view
`
= column_chart @data
`

but it doesn't work, the bars keep the same color, is there some way to get it? I need to draw 5 bars with different colors each

**Comment by ankane** [comment]
Hey @dev-darenas, please check out the Contributing Guide for where to get help customizing charts.
