### ISSUE TITLE
Brave Browser : Display Issue

### ISSUE THREAD

**Issue by countalucard2022** [ankane/chartkick#534]
Hi Everyone,

Not sure if this is worth raising as an issue, but decided to do so as Im a brave browser user and literally wasted few time trying to verify what's the issue, what was happened to my css, why does chart isn't working (y axis).

![image](https://user-images.githubusercontent.com/6740123/83288827-96ba6680-a216-11ea-81fd-520ef041bbfe.png)

![image](https://user-images.githubusercontent.com/6740123/83288837-9c17b100-a216-11ea-88c1-839345277871.png)

Before I raised this , I re-validate my issue in different browser (chrome/firefox/edge) and no problem at all.

Edge:
![image](https://user-images.githubusercontent.com/6740123/83288992-e5680080-a216-11ea-8f39-e34c8719a89b.png)

**Comment by ankane** [comment]
Hey @countalucard2022, can you paste the JavaScript generated by Chartkick?

**Comment by countalucard2022** [comment]
Hi @ankane , sorry late response. I don't see anything wrong on the js generated.

Brave:
<script type="text/javascript">
  new Chartkick["LineChart"]("chart-1", [["Sat",3],["Sun",2],["Mon",2],["Tue",7],["Wed",2],["Thu",3],["Fri",3]], {"messages":{"empty":"Nothing to show "}});
</script>

Chrome

<script type="text/javascript">
  new Chartkick["LineChart"]("chart-1", [["Sat",3],["Sun",2],["Mon",2],["Tue",7],["Wed",2],["Thu",3],["Fri",3]], {"messages":{"empty":"Nothing to show "}});
</script>

**Comment by ankane** [comment]
Hey @countalucard2022, here's what I see in Brave with that code.

<img width="834" alt="Screen Shot 2020-05-30 at 4 19 19 PM" src="https://user-images.githubusercontent.com/220358/83340811-77145400-a291-11ea-9873-a8841c8c8092.png">

My guess is something else on the page is causing it.

**Comment by countalucard2022** [comment]
I disabled pretty much all my modification js/css, I will try with the fresh project and update as needed. Thanks for checking.
