### ISSUE TITLE
Are Tables (Only with Google Charts) deprecated ?

### ISSUE THREAD

**Issue by diogopublio** [ankane/chartkick#535]
Are Tables (Only with Google Charts) deprecated ?

I see you had in some commits ago: https://github.com/releaseplatform/chartkick/blob/6ac9334416fd1f81d22721235d0d559d5803355b/README.md

But it is not in the documentation now. Any reason why ?

**Comment by ankane** [comment]
Hey @diogopublio, that's a fork. Chartkick doesn't support tables (doesn't try to support all chart types).

**Comment by diogopublio** [comment]
you are right, my mistake.

I see that this [PR](https://github.com/ankane/chartkick/pull/348) was not merged to master
