### ISSUE TITLE
Scale of secondary AXIS

### ISSUE THREAD

**Issue by leoplct** [ankane/chartkick#538]
I am creating a 2-lines chart (chart.js) but they have a different scale (%/$ or 1,000 and %). 
How can I set to print the chart two scales?

<%= line_chart @goals.map { |goal|
    {name: goal.name, data: goal.feats.group_by_week(:created_at).count}
} %>

**Comment by ankane** [comment]
Hey @leoplct, check out the Contributing Guide for where to get help.
