### ISSUE TITLE
Prefix/Suffix different for two axis

### ISSUE THREAD

**Issue by leoplct** [ankane/chartkick#540]
**First**
I have to add a prefix/suffix different for each series. I cannot add two prefix/suffix using the standard method (<%= line_chart data, prefix: "$" %>), so I have to use library: {}.

**Describe the bug**
Cannot add a JS function as a text in a ruby file.
Error Loading Chart: function(value, index, values) {return '$' + value} is not a function

**To reproduce (chart.rb)** 
```
line_chart(url,points: false, precision: 2,  messages: {empty: "No data"}, library: {scales: {
        yAxes: [
          {
            id: 'AMOUNT',
            type: 'linear',
            position: 'left',
            scaleLabel: {display: true, labelString: "amount"},
            ticks: {callback: "function(value, index, values) {return '$' + value}"},
          },
          {
            id: 'KPI',
            type: 'linear',
            position: 'right',
            scaleLabel: {display: true, labelString: 'KPI (%)'},
            ticks: {
                suggestedMin: 0,
                suggestedMax: 100
            }
            
          }
        ]
      }
    })
```
**HTML generated by Chartkick**

```html
<script type="text/javascript">
  new Chartkick["LineChart"]("chart-1", "/analytics/chart.json?chart=amount\u0026rolling_days=1", {"points":false,"precision":2,"messages":{"empty":"No data"},"library":{"scales":{"yAxes":[{"id":"spend","type":"linear","position":"left","scaleLabel":{"display":true,"labelString":"Spend,Sales"},"ticks":{"callback":"function(value, index, values) {return '$' + value}"}},{"id":"acos","type":"linear","position":"right","scaleLabel":{"display":true,"labelString":"ACoS (%)"},"ticks":{"suggestedMin":0,"suggestedMax":100}}]}}});
</script>
```

**Comment by ankane** [comment]
Hey @leoplct, it's not possible to embed functions in JSON, so you'd need to use the JS library directly to accomplish this.

**Comment by leoplct** [comment]
ok, any other way to add a different prefix/suffix (eg. $, %) for each series?

**Comment by ankane** [comment]
There isn't any built-in functionality for multiple y-axes right now, but happy to review a PR if it's something you'd like to add. My initial thoughts on how it could look are here: https://github.com/ankane/chartkick.js/issues/79 (prefix/suffix could be nested under `y2` as well).

**Comment by ankane** [comment]
Cleaning up issues
