### ISSUE TITLE
Localization for date label formats

### ISSUE THREAD

**Issue by taq** [ankane/chartkick#542]
Sorry to open this issue, but I've already tried a lot of things but didn't worked.

I'm trying to localize the Charts.js date labels. I need they to change from YYYY-MM-DD to DD/MM/YYYY. I could not find a clear way to do that, already checked some posts and Chart.js.

**Comment by ankane** [comment]
Hey @taq, unfortunately, I don't have the bandwidth to help with customizing charts. There should be a link for where to get help when creating a new issue.
