### ISSUE TITLE
Can't Draw vertical line in a bar_chart

### ISSUE THREAD

**Issue by Muhammad-Saqib-980** [ankane/chartkick#547]
Hi i am using bar_chart to display a chart in my slim file which is working fine.But I want to draw a vertical line indicating a boundary for each bar is there any way for that because i have search every where if that is possible can anyone please guide me.
My chart look like this
![Screenshot from 2020-08-20 06-46-23](https://user-images.githubusercontent.com/50771695/90778483-882d9980-e2b1-11ea-9375-988d31a8b59d.png)
my code for that chart is 
`=bar_chart @all_loads.map{|j| ["#{j.name} - #{j.city}", j.load_count]}.sort_by{|m| m[0] }, height: @bar_chart_height `

**Comment by ankane** [comment]
Hey @Muhammad-Saqib-980, check out the new issue page for where to get help customizing charts.

**Comment by Muhammad-Saqib-980** [comment]
issue is that there is not a way to add any vertical line or bar that is an issue.
