### ISSUE TITLE
Sinatra support for Chart.js and Highcharts

### ISSUE THREAD

**Issue by blakegearin** [ankane/chartkick#549]
**Is your feature request related to a problem? Please describe.**
While using `chartkick.js` with Sinatra it seems the charting library being used is Google Charts. I would like to be able to switch between Chart.js, Google Charts, and Highcharts

**Describe the solution you'd like**
1. Provide different flavors `chartkick.js` for different charting libraries
OR
2. More documentation around how to use the existing `chartkick.js` with Chart.js and Highcharts. For instance, do other `.js` files need to be downloaded and included with a script tag? If so, what should be downloaded?

**Additional context**
For Chart.js I tried the following:
1. Downloaded `Chart.min.js` version `2.9.3` from a [Chart.js CDN](https://www.jsdelivr.com/package/npm/chart.js) ([raw file](https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js))
2. Added line 3 to my `layout.haml` file (which was previously working, displaying a chart using Google Charts))
```haml
1 %script{ src: '//www.google.com/jsapi' }
2 %script{ type: 'text/javascript', src: "/javascripts/chartkick.js" }
3 %script{ type: 'text/javascript', src: "/javascripts/Chart.min.js" }
```
3. Got this error in the browser console:
```
chartkick.js:1763 Uncaught Error: This method is not implemented: either no adapter can be found or an incomplete integration was provided.
```

**Comment by ankane** [comment]
Hey @blakegearin, thanks for the suggestion! You'll need to use `Chart.bundle.js` instead of `Chart.min.js`. I've expanded the docs in the readme.
