### ISSUE TITLE
Support lazy loading Chartkick

### ISSUE THREAD

**Issue by AlecRust** [ankane/chartkick#551]
## Is your feature request related to a problem? Please describe.
(_I am also using `defer: true` on my main application bundle and Turbolinks like in https://github.com/ankane/chartkick/issues/536_)

I'd like to avoid loading `chartkick` and `chart.js` npm dependencies in my main `application.js` and only load them when I'm on a page containing a chart. To do this I'm doing the following:

`app/webpacker/packs/application.js`
```js
import '../charts'
```

`app/webpacker/charts.js`
```js
document.addEventListener('turbolinks:load', () => {
  const charts = document.querySelectorAll('.js-chartkick-chart')
  if (charts.length) {
    Promise.all([import('chartkick'), import('chart.js')])
  }
})
```

If Chartkick's `defer: true` is set, this works when loading a page (without Turbolinks) containing charts.

However if I load a different page not containing charts, then navigate to the page containing charts via Turbolinks, although no JS errors occur the charts stay in "Loading" state.

I have tried redrawing the charts like the following but same behaviour:

```js
document.addEventListener('turbolinks:load', () => {
  const charts = document.querySelectorAll('.js-chartkick-chart')
  if (charts.length) {
    if (typeof Chartkick !== 'undefined') {
      Chartkick.eachChart(function (chart) {
        chart.redraw()
      })
    } else {
      Promise.all([import('chartkick'), import('chart.js')])
    }
  }
})
```

The `turbolinks` branch you created in https://github.com/ankane/chartkick/issues/536 partly fixes this issue for me, in that if the npm dependencies are loaded, when I navigate away and back via Turbolinks the charts are successfully redrawn. However the branch also seems to change the `defer` option behaviour such that it no longer waits for the page to load, so loading a page (without Turbolinks) containing charts now breaks.

## Describe the solution you'd like

Assuming the `turbolinks` branch will be merged in, I wonder if you could consider the case above also? I think if Chartkick's `defer: true` behaviour on `turbolinks` branch matched current `master` it would fix my issue.

In the meantime I will disable Turbolinks on links to pages containing charts.

**Comment by ankane** [comment]
Hey @AlecRust, the current plan is to make all charts deferrable by default in Chartkick 4 (see https://github.com/ankane/chartkick/issues/536#issuecomment-720229441 for more details).

In the situation described above, you'll need to make sure Chart.js is loaded before Chartkick, so you'll probably want to put them in the same JavaScript file.

**Comment by AlecRust** [comment]
@ankane yay for deferrable by default!

I'm not entirely sure what you mean by "put them in the same JavaScript file" but using the `deferrable` branch with the following works great for me i.e. both when navigating in via Turbolinks and when reloading the page on its own:

```js
document.addEventListener('turbolinks:load', () => {
  const charts = document.querySelectorAll('.js-chartkick-chart')
  if (charts.length) {
    Promise.all([import('chartkick'), import('chart.js')]).then(([Chartkick]) => {
      // NOTE: The following will be part of Chartkick 4.0
      // https://github.com/ankane/chartkick/issues/536#issuecomment-720229441
      window.dispatchEvent(new Event('chartkick:load'))

      Chartkick.destroyAll = function () {
        for (var id in Chartkick.charts) {
          Chartkick.charts[id].destroy()
          delete Chartkick.charts[id]
        }
      }

      document.addEventListener('turbolinks:before-render', () => {
        Chartkick.destroyAll()
      })
    })
  }
})
```
While this solves my problem, I'm curious about your "make sure Chart.js is loaded before Chartkick" statement. Are you suggesting I change the order in the import array? In all your documentation I see `chartkick` loaded before `chart.js`.

**Comment by ankane** [comment]
@AlecRust Great to hear it's working. When it's released, the code that's currently running after both Chartkick.js and Chart.js are loaded will be part of Chartkick.js, so the pattern above will cause a `No charting library found` error when Chartkick.js loads first. You can either:

1. Make sure Chartkick.js is imported after Chart.js finishes loading OR
2. Load them in the same file/pack and import that

**Comment by AlecRust** [comment]
Understood, many thanks!

**Comment by ankane** [comment]
Just released Chartkick 4, which should support this (no need for any of the `window.dispatchEvent` or `Chartkick.destroyAll()` code). Thanks for the suggestion and helping to test earlier!
