### ISSUE TITLE
Incorrect scale tick while Chartjs using bytes and custom option (min)

### ISSUE THREAD

**Issue by adamaiken89** [ankane/chartkick#555]
**Version**
3.4.1

**Describe the bug**
I am trying to apply both bytes and a custom option `min` at the same time.
The graphs axis y shows a list of number on the axis.
And unfortunately, applying rounding nor precision both do not work.
**To reproduce**
```
line_chart result,
               bytes: true,
               library: {
                 scales: {
                   yAxes: [
                     {
                       ticks: {
                         min: 1234324234234
                       }
                     }
                   ]
                 }
               }
```

**Screenshot by Chartkick**
<img width="1016" alt="Screenshot 2020-11-12 at 10 58 51 AM" src="https://user-images.githubusercontent.com/6821806/98890100-31adb100-24d6-11eb-94ae-922d132275a5.png">

**Comment by ankane** [comment]
Hey @adamaiken89, sorry for the delay. `round` and `precision` only apply to tooltips, not axis labels, so you'll need to pass a round value of megabytes for the minimum if you want to avoid decimals.
