### ISSUE TITLE
Popup on short horizontal chart is cut

### ISSUE THREAD

**Issue by literakl** [ankane/chartkick#557]
**Describe the bug**

I have a narrow chart. When I move a mouse pointer over it, the popup with values is displayed over the chart area. But because the chart is short and there is not enough space, the popup is cut. I tried to hide the tooltip without luck.

![image](https://user-images.githubusercontent.com/6383287/99182614-28228400-2736-11eb-89b1-3bff6e27ecbf.png)

**To reproduce**

    import Chartkick from "vue-chartkick";
    import Chart from "chart.js";
    Vue.use(Chartkick.use(Chart));

    <bar-chart
      :data="chartData"
      suffix="%"
      height="100px"
      :colors="['#28a745', '#007bff', '#ffc107', '#dc3545']"
      :stacked="true"
      :library="{ options: { tooltips: false } }"
    >
    </bar-chart>

See the code sandbox https://codesandbox.io/s/pensive-williamson-upohe?file=/src/components/HelloWorld.vue:185-418

**Comment by ankane** [comment]
Hey @literakl, it looks like that's how Chart.js handles tooltips for small charts, so not sure there's much Chartkick can do.

To disable tooltips with Vue Chartkick, use `library="{tooltips: {enabled: false}}"`.

**Comment by literakl** [comment]
Ok
