### ISSUE TITLE
scatter chart - axis with datetime fields

### ISSUE THREAD

**Issue by riddhibacancy** [ankane/chartkick#558]
Hey @ankane 

I have data something like this..
[[Tue, 05 Jan 2021 01:44:16 -0500, "10"], [Sat, 19 Dec 2020 09:51:53 -0500, "100"], [Thu, 07 Jan 2021 00:34:04 -0500, "20"], [Tue, 05 Jan 2021 05:34:50 -0500, "90"]]

I want to use scatter chart, with label in proper date format in x-axis, but label and tooltip not come up with proper datetime format

please guide to move further

**Comment by ankane** [comment]
Hey @riddhibacancy, Chartkick scatter charts only support numeric columns. You'll need to fork the project or use the underlying charting library directly for other column types.

**Comment by riddhibacancy** [comment]
> Hey @riddhibacancy, Chartkick scatter charts only support numeric columns. You'll need to fork the project or use the underlying charting library directly for other column types.

Thanks, It will be really great If Chartkick will support datetime fields with scatter chart

**Comment by ankane** [comment]
Hey @riddhibacancy, you can try using the code from [this PR](https://github.com/ankane/chartkick.js/pull/122), but don't think it's common enough to support right now.
