### ISSUE TITLE
Error Loading Chart: Unauthorized

### ISSUE THREAD

**Issue by cicchello82** [ankane/chartkick#559]
Hi,
I'm trying to render a column chart asynchronously with json render and path in helper, but I always receive the messagge " Error Loading Chart: Unauthorizes.
Anyone could help me?
Regards,
Giacomo

**Comment by ankane** [comment]
Hi @cicchello82, it sounds like there's an authentication issue with the endpoint you're calling. Check out the new issue page for where to get help.
