### ISSUE TITLE
How to change the default language / locale for Google Charts?

### ISSUE THREAD

**Issue by felixding** [ankane/chartkick#56]
I'm sorry if it's not an issue of chartkick, but after googling a bit I still have no clue.

What I want to do is set the default language to "zh" no matter what locales users use. So that the labels on line charts would be in Chinese.

According to [Google's documentation](https://developers.google.com/chart/interactive/docs/library_loading_enhancements#loadwithlocale), I should be able to set the language by using the `language` parameter:

```
google.load('visualization', '1', {'packages':['corechart'], 'language': 'ja'});
```

I tried with `line_chart api_console_page_index_path, library: {language: "zh"}` but it doesn't work.

Can you please help me?

**Comment by fwuensche** [comment]
I'm facing the same issue for HighCharts. 

I tried to setOptions as seen below but still can't make it work. 

    = javascript_include_tag 'highcharts', 'chartkick'
    :javascript
      Highcharts.setOptions({
        lang: {
            months: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
        }
      });

When I 'getOptions' through the console, the months are perfectly set. 

![screen shot 2015-06-06 at 17 33 57](https://cloud.githubusercontent.com/assets/1740848/8021350/53f7168e-0c72-11e5-916a-c84613f4ef46.png)

Any idea on how to make it work?
