### ISSUE TITLE
Support for Mixed charts?

### ISSUE THREAD

**Issue by weiserma** [ankane/chartkick#565]
Is there a way to build a mixed chart?

Mixed Chart Types
With Chart.js, it is possible to create mixed charts that are a combination of two or more different chart types. A common example is a bar chart that also includes a line dataset.

When creating a mixed chart, we specify the chart type on each dataset.

```
var mixedChart = new Chart(ctx, {
    data: {
        datasets: [{
            type: 'bar',
            label: 'Bar Dataset',
            data: [10, 20, 30, 40]
        }, {
            type: 'line',
            label: 'Line Dataset',
            data: [50, 50, 50, 50],
        }],
        labels: ['January', 'February', 'March', 'April']
    },
    options: options
});

```

**Comment by ankane** [comment]
Hey @chiperific, sorry for the delay. It's not supported right now, and not something I'm looking to add at the moment.
