### ISSUE TITLE
Hide one or more legend labels (but not all)

### ISSUE THREAD

**Issue by fakeharxy** [ankane/chartkick#581]
Hello, I have searched existing issues and I _believe_ this is unique... 

Is there a way to not show a legend for some line chart data but not others? I see there is quite a complicated way in native chart.js, but it involves a JS callback in the invocation of the graph which I'm not sure is possible via Ruby. 

Is this possible? Many thanks

**Comment by ankane** [comment]
Hey @fakeharxy, Chartkick doesn't have an option for it, so you'll need to use the approach from the underlying charting library. There's not a way to pass JS callbacks from Ruby, so you'd need to use the JavaScript API/Chartkick.js directly.

**Comment by fakeharxy** [comment]
Thanks for looking into it. 👍
