### ISSUE TITLE
Is there any convenient way to hide all items at once?

### ISSUE THREAD

**Issue by hxingpax** [ankane/chartkick#582]
**First**
Did, not discussed yet.

**~~Is your feature request related to a problem? Please describe.~~**

**Describe the solution you'd like**
Some times I'd like to hide all the lines/charts, only show the one I m interested. So far, seems like I have to hide all the other items one by one. Is it possible to hide them all at once?

**~~Additional context~~**

**Comment by ankane** [comment]
Hey @hxingpax, if the underlying charting library supports it, you can try using the `library` option.
