### ISSUE TITLE
Rails 7 / Propshaft support

### ISSUE THREAD

**Issue by seanwmitchell** [ankane/chartkick#588]
Is it possible to add in support or documentation for use of Rails 7 / Propshaft installations.

**Comment by ankane** [comment]
Hey @seanwmitchell, the existing Rails 7 instructions (for Importmap, esbuild, and Webpack) should work with both Sprockets and Propshaft.

**Comment by seanwmitchell** [comment]
Okay, I'll try again. It was just showing "Loading ..." for me when I tried it earlier, so I reverted to sprockets.

**Comment by ankane** [comment]
Cleaning up issues
