### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by berti92** [ankane/chartkick#592]
If you set `policy.script_src :self, :https` in the config/content_security_policy.rb, then it's not possible to use this gem. Chrome will raise an error in the console:

> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https:". Either the 'unsafe-inline' keyword, a hash ('XXXXXXXXXX'), or a nonce ('nonce-...') is required to enable inline execution.

Is this known and do you fix this or do I need to change some settings in the gem?

Thank you very much :)

**Comment by ankane** [comment]
Hey @berti92, check out the docs for how to configure CSP.
