### ISSUE TITLE
More formatting options on chart legends

### ISSUE THREAD

**Issue by elarue53078** [ankane/chartkick#593]
In discussing chartkick implementations, our team noticed certain ways we'd like to format the legend that we seem to be unable to do:

1) The legend seems to put all the legend objects on one line; we would like the option to put each element on its own line.
2) In connection with the above, we would like to left-align the legend elements. Currently only the default center alignment appears to be available.
3) The color keys are currently rectangles. We would like to change this to squares.

**Comment by ankane** [comment]
Hey @elarue53078, you can use `library` option to make make customizations that the underlying charting library supports.

**Comment by bhanubhakta** [comment]
@ankane I am using the options like this:

```ruby
library: { legend: { display: false, position: 'bottom', labels: { usePointStyle: true, boxWidth: 6 } } }```

Also tried:

```ruby
library: { options: { plugins: { legend: { display: true, position: 'bottom', labels: { usePointStyle: true, boxWidth: 6 } } } } }```

Also tried:
Also tried:

```ruby
library: { options: { legend: { display: true, position: 'bottom', labels: { usePointStyle: true, boxWidth: 6 } } } }```

None worked. I am using `Chart.js` and it has the options I provided above.

Am I doing something wrong?

**Comment by maxlein** [comment]
This is also not working for me

**Comment by bborn** [comment]
You need to configure the legend within the Chart.js `plugins` key:

```
<%= line_chart(@data,
      library: {
        plugins: {
          legend: {
            labels: {
              usePointStyle: true,
            },
          },
        },
      },
    ) %>
