### ISSUE TITLE
Charts stuck at "Loading..." [example included]

### ISSUE THREAD

**Issue by patwalls** [ankane/chartkick#598]
Looked everywhere and I cannot figure out why my charts are stuck at loading...

Here is the real world example reproduced, feel free to inspect the page and view page source, etc

https://www.starterstory.com/charts

Thank you for any help!

**Comment by ankane** [comment]
Hey @patwalls, check out the new issue page for where to get help.

**Comment by johnpitchko** [comment]
Having the same issue here. No errors on console or Rails process. Looked around for the 'new issue page' but didn't find anything in this GH repo page or the chartkick website.

**Comment by Salomanuel** [comment]
> Looked everywhere and I cannot figure out why my charts are stuck at loading...
> 
> Here is the real world example reproduced, feel free to inspect the page and view page source, etc
> 
> https://www.starterstory.com/charts
> 
> Thank you for any help!

sorry for the necroposting, but I noticed that in @patwalls example, the chart loads jolly well
how did you achieve this outstanding result? how did you get it to work?

(All long help threads should have a sticky globally-editable post at the top saying 'DEAR PEOPLE FROM THE FUTURE: Here's what we've figured out so far ... (quote))

**Comment by MtnBiker** [comment]
https://www.starterstory.com/charts now shows Loading...
