### ISSUE TITLE
Add support for chart.js 4.x

### ISSUE THREAD

**Issue by kwent** [ankane/chartkick#601]
### Add support for chart.js 4.x

https://www.chartjs.org/docs/latest/migration/v4-migration.html

**Comment by ankane** [comment]
Hey @kwent, added to Chartkick.js in https://github.com/ankane/chartkick.js/commit/945b170870410b64e6d51a3f0df7c46e7e869289, but want to do some more testing before releasing and upgrading the gem.

**Comment by ankane** [comment]
Quick update: I've done a lot of testing with different asset frameworks (importmaps, jsbundling esbuild, jsbundling webpack, jsbundling rollup, webpacker, sprockets), including support for plugins (#597), and am pretty happy with things.

There's an issue with the latest Chart.js (4.1.2) and Webpacker (which uses Webpack 4), which is resolved by https://github.com/chartjs/Chart.js/pull/11037, so planning to release Chartkick 5 once that's out.

**Comment by ankane** [comment]
Chartkick 5 is out with support for this 🎉
