### ISSUE TITLE
Add combo bar/line charts

### ISSUE THREAD

**Issue by jmarbach** [ankane/chartkick#602]
**As a** developer
**I want** to be able to combine multiple chart types, such as line and bar charts
**So that** I can create visualizations that show a series and an aggregation of a series in one graph

**Given** a developer wants to show bar and line charts at once
**When** the developer configures their chartkick chart
**Then** they specify `combo_bar_line` and within the data array they specify the two series to display

e.g. 
```
<%= combo_bar_line [
    {
      name: "Series 1",
      data ...,
      dataset: { }
    },
    {
      name: "Series 2",
      data: ...,
      dataset: { }
    }
  ]
%>

```

**Context**
- Support for additional chart types is a top-roadmap item: https://github.com/ankane/chartkick/issues/489
- Chart.js supports bar/line charts as of 4.0.1: https://www.chartjs.org/docs/latest/samples/other-charts/combo-bar-line.html

**Comment by ankane** [comment]
Hey @jmarbach, thanks for the suggestion, but I'm not looking to add any more chart types right now.

**Comment by suxur** [comment]
@jmarbach This can be achieved already, though it's not very apparent. You just need to pass the type of chart you want in one of the datasets. Taking your example, you can do...

```rb
<%= line_chart [
    {
      name: "Series 1",
      data ...,
      dataset: {
        type: "line"
       }
    },
    {
      name: "Series 2",
      data: ...,
      dataset: { 
        type: "bar"
      }
    }
  ]
%>
```

**Comment by MtnBiker** [comment]
How do you add chart `title`, `min`, `max`? I am overlaying line_charts. 

` <%= line_chart [
     
       {
         name: "Systolic",
        data: BloodPressure.where(statdate: Time.now - 3.month..Time.now).pluck(:statdate, :systolic) 
       },
        {name: "Diastolic",
        data: BloodPressure.where(statdate: Time.now - 3.month..Time.now).pluck(:statdate, :diastolic)
       }
    ]
    %>`

**Comment by armanivvv** [comment]
> @jmarbach This can be achieved already, though it's not very apparent. You just need to pass the type of chart you want in one of the datasets. Taking your example, you can do...
> 
> ```ruby
> <%= line_chart [
>     {
>       name: "Series 1",
>       data ...,
>       dataset: {
>         type: "line"
>        }
>     },
>     {
>       name: "Series 2",
>       data: ...,
>       dataset: { 
>         type: "bar"
>       }
>     }
>   ]
> %>
> ```

Amazing. I was already looking for another charting package. This saved me 95% of the way. Now to figure out if it can be forced in the HighCharts adaptor.

<img width="903" alt="SCR-20240614-mymp" src="https://github.com/ankane/chartkick/assets/39682219/f902849d-3560-4379-be1c-c32b3ffc2aa6">
