### ISSUE TITLE
Chartkick 2.0

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick#61]
Super. Easy. Customization.

Game plan:
- [x] discrete values for line charts
- [x] fully customizable div
- [ ] more advanced data type
- [ ] custom tooltips
- [ ] custom libraries and chart types
- [x] ability to specify a library if multiple libraries are loaded
- [x] access to Chartkick objects
- [ ] ability to trigger event to render chart

Possibly:
- [ ] more chart types (geo, sparklines)
- [ ] examples w/o Groupdate
- [ ] export to image
- [ ] themes
- [ ] updated colors

**Comment by nozpheratu** [comment]
SVGs can be generated server-side using PhantomJS:
https://github.com/pstephan1187/PhantomJS-Google-Charts

Example:
```ruby
data = {"type" => "PieChart", "options" => {"title" => "Type of Fruit Eaten", "width" => "400", "height" => "300", "is3D" => true, "pieSliceText" => "value"}, "theData" => [['Task', 'Hours per Day'], ['Work', 11], ['Eat', 2], ['Commute', 2], ['Watch TV', 2], ['Sleep', 7]]}.to_json
require 'tempfile'
file = Tempfile.new(['a', '.txt'], "#{Rails.root}/tmp")
file.write(data)
File.chmod(444, file.path)
file.rewind
Phantomjs.run("./path/to/trigger.js", file.path)
```
