### ISSUE TITLE
Rails 7 Setup Additional Step Needed

### ISSUE THREAD

**Issue by Jake839** [ankane/chartkick#613]
To get the charts to load in Rails 7, put <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %> in application.html.erb
Source: https://www.appsloveworld.com/ruby-on-rails/100/486/chartkick-not-loading-in-ruby-on-rails-7

**Comment by ankane** [comment]
Hi @Jake839, the current instructions work fine for Rails 7.

**Comment by Jake839** [comment]
Oh ok Andrew. It actually wasn’t working for me until I did that step. I’m using Rails 7.0.6. I am a junior dev tho haha.

**Comment by Jake839** [comment]
Add me on LI if you like. https://www.linkedin.com/in/jshap/

**Comment by elbzero** [comment]
Thanks so much! I had the same issue and this fixed it, @ankane could be consider re-opening this issue?

FYI I'm on rails (7.0.8) with chartkick (5.0.6) and using webpacker
In my yarn lock chartkick@^5.0.1 with chart.js@^4.4.2

Initially when I added import "chartkick/chart.js"; I kept getting Error Loading Chart: No charting libraries found - be sure to include one before your charts, after adding @Jake839 suggested change it loads fine.

**Comment by zhenshuo** [comment]
The official instructions are working for my Rails 7.1.3 project with Importmap. I was facing the same issue, then realised it's because I didn't add `<%= javascript_importmap_tags %>` to `application.html.erb`

**Comment by marckohlbrugge** [comment]
I'm on Rails 7.2.2 and the charts show fine on first page load, but are deleted and not recreated when browsing with Turbo Drive.

Adding `<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>` leads to some interesting behavior:

1. On the first page load, the chart loads fine, but now lacks any custom styling I provided with the view helper.
2. When browsing with Turbo Drive, the charts now load fine WITH my custom styling.

@ankane Perhaps this peculiar behavior helps gain some insights into some of the other Turbo related issues people run into.
