### ISSUE TITLE
Conflicts with Action_text from rails and do not displaying in production(Heroku)

### ISSUE THREAD

**Issue by alejandrotoledoweb** [ankane/chartkick#621]
I am working on a project where I have some form using `rich_text_area`. They were working fine until I imported the chartkick js dependencies in the application.js file:
`// import "chartkick";`
`// import "Chart.bundle";`

The `rich_text_area` became disable to use.

Also, the charts are displaying fine for development env but for production does not work. I was making sure the js and the gem are correctly installed but not luck so far.

**Comment by ankane** [comment]
Hi @alejandrotoledoweb, this doesn't seem like an issue with Chartkick (but rather something with your production environment).
