### ISSUE TITLE
Support for inline plugins

### ISSUE THREAD

**Issue by ycha28** [ankane/chartkick#623]
It would be great if chartkicks supported inline plugins. I'm trying to implement the plugin described in this SO post (https://stackoverflow.com/questions/51323890/chart-js-stacked-bar-chart-sorting-values-in-bar-by-value), but I don't see a way to add an inline plugin to my Chart.js chart through Chartkick at the moment.

**Comment by ankane** [comment]
Hi @ycha28, thanks for the suggestion. However, I don't think it's common enough to add / support.
