### ISSUE TITLE
Unable to download graph

### ISSUE THREAD

**Issue by aldrienht** [ankane/chartkick#628]
**Describe the bug**
Download works on Chrome browser but not with Safari (tested) or Firefox
```
<%= line_chart data, download: true %>
```

Use other browser like Safari - and you'll get error like:

```
Refused to load data:image/png;base64,... because it does not appear in the frame-src directive of the Content Security Policy.
```

**Comment by ankane** [comment]
Hi @aldrienht, from the error message, you'll need to update your Content Security Policy.

**Comment by aldrienht** [comment]
Hi @ankane - any advice on how to do it correctly, my Rails app is embedded to Shopify Admin (iframed) - Thanks in advance!
