### ISSUE TITLE
Feature request: support named values in data

### ISSUE THREAD

**Issue by tfwright** [ankane/chartkick#63]
In order to specify properties for points (including custom attributes), data needs to support more than just `x => y` values.  

See [option #3 here](http://api.highcharts.com/highcharts#series.data)

**Comment by austinarchibald** [comment]
I second this. I tried formatting the data like the highcharts api says, `{x: 2, y: 3, name: 'point'}` but it only accepts `[2,3]`. Didn't know why it didn't work until I saw this request. Chart doesn't work in first format. I can set the data to `[2,3, 'point']` but and the third item is shown in the rendered javascript, but not sure how to 'access' it so I can put it in a tooltip or datalabel. I can access series name just fine but not the data point name.

**Comment by gitjul** [comment]
glad I ran into this, I've been trying to get this to work for a while now. I thought maybe I could do this via `library` option but nope, data = `undefined` overrides that (I'm using `react-chartkick`). I don't see a workaround, is there one?
I think it could be enough to allow for the library > series > data attr to override the data attr input.

**Comment by ankane** [comment]
Going to close this one out after five years. A new data format may be added in the future if needed to support specific features.
