### ISSUE TITLE
Support for spider or radar, and donut chart

### ISSUE THREAD

**Issue by regdog** [ankane/chartkick#69]
It's a very good chart gem! But it lacks donut, and spider charts. Any plan for these typical charts?

**Comment by 34code** [comment]
:+1: for the pieHole reference! We are using this library over at THRED and the team loves the simplicity of the library! Thanks @ankane :)

**Comment by jeremygradisher** [comment]
Nice! I was looking to get the donut chart to work with the chartkick gem, this did the trick. Thank you! <%= pie_chart Project.group(:status).count, library: {pieHole: 0.5} %>

**Comment by michaelminter** [comment]
Would like to see donut chart like: http://www.highcharts.com/demo/pie-donut

**Comment by rabinprithvi** [comment]
Great work! Do Radar Charts of Chart.js works fine with the lastest ChartKick? 
Thank you.

**Comment by pinzonjulian** [comment]
@rabinprithvi did you manage to do radar charts?

**Comment by ankane** [comment]
For those following along, there's now a `donut: true` option you can set for donut charts.

For the other charts types, I don't plan to support additional chart types at this time. Chartkick.js has experimental support for custom adapters, so someone could try to implement this chart type as a separate gem. https://github.com/ankane/chartkick.js#custom-adapters
