### ISSUE TITLE
How to reload charts on user input?

### ISSUE THREAD

**Issue by sonxurxo** [ankane/chartkick#74]
Is there a way to reload the chart when user produces some input? For example, user can enter a date range, or similar.

If there's not such a feature, it would be great to have it.

Congrats for the library!

**Comment by sman591** [comment]
+1 for interval updates, whether Chartkick has it built in or just simply enables developers to make it possible.

**Comment by phlegx** [comment]
+1 enabling developers to add it's own form.

**Comment by mikewagz** [comment]
+1 for a dynamic reload based on a parameter change (ie. change a chart from 'all' to a certain year).

**Comment by ankane** [comment]
Chartkick now has a `refresh` option to refresh the data at regular intervals.

To update all charts on user input, you can now do something like:

```javascript
Chartkick.eachChart( function(chart) {
  chart.updateData(chart.getDataSource() + "?some_param=abc");
});
```
