### ISSUE TITLE
Can't add colors in bar charts

### ISSUE THREAD

**Issue by sasharevzin** [ankane/chartkick#77]
Hello,

I tried different number of combinations but still can't find a way:

``` ruby
data = [['title1', 5, 'red'], ['title 2', 10, 'blue']]
```

``` rails
<%= bar_chart data, colors: ['red', 'blue'] %> 
<%= bar_chart data, library: {colors: ['red', 'blue']} %>
```

Any ideas how to push colors to bar charts?

Thank you

**Comment by jtlindsey** [comment]
Any possibility of opening this back up to enable changing colors on each bar in column chart? Is there a way to add column titles?

Here is the code I am using on my rails html.erb:
```
<%= column_chart networth_data, colors: ["green", "#FF0000"], library: {
          backgroundColor: "#FFF", height: 265} %>
```
And in my helper file:
```
  def networth_data
    [
      {name: "Assets", data: {"NetWorth": 6582.13}}, 
      {name: "Liabilities", data: {"NetWorth": 10500.32}}
    ]
  end
```


I got it to work without multiple series, but I lost the column titles:
![screen shot 2015-07-02 at 1 36 46 am](https://cloud.githubusercontent.com/assets/7409277/8470606/fdb451a8-205b-11e5-9d49-873d4f485758.png)

The default column chart has the column titles but still chant change the color of each column. Color applies to all columns:

![screen shot 2015-07-02 at 1 46 58 am](https://cloud.githubusercontent.com/assets/7409277/8470627/60f7b52a-205c-11e5-8e46-d350337c4039.png)

Code for that was:
from model
```
     [
       ["Assets", 6582.13], 
       ["Liabilities", 10500.32]
     ]
```
to html.erb
```
<%= column_chart data, 
        library: {
          backgroundColor: "#FFF", height: 265,
          :colors => ['green', 'red']
        } %>
```
