### ISSUE TITLE
Hide legend only when data given in single series format

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick#8]
We want to hide the legend when only graphing a single series, like:

``` erb
<%= line_chart User.group_by_day(:created_at).count %>
```

However, if the data is provided as:

``` erb
<%= line_chart @goals.map{|goal|
    {:name => goal.name, :data => goal.feats.group_by_week(:created_at).count }
} %>
```

and there is only one series, we still want to show the legend, since the title of the chart will be something like "Goals per Week".

**Comment by gpinkham** [comment]
i was just in here looking to see why the legend doesn't show on a GeoChart and I suspect this might be why.. before I dig just wanted to get your thoughts..   thanks!
