### ISSUE TITLE
Display values in chart

### ISSUE THREAD

**Issue by timoroemer** [ankane/chartkick#80]
Hello - i've been googling for a while now and i am unable to solve it:
Is there any way to display the values of a line chart at the data points? Like this:
![](http://i.stack.imgur.com/lFYtx.png)

I am using google charts and haven't been able to figure that out. Anyway you can help?

As a side note: This gem is great!

**Comment by mfrederickson** [comment]
I'd like to have the ability for annotations [in a stacked bar chart] also.

**Comment by bnzelener** [comment]
Anyone make any progress with this?  I'd like to be able to label stacked bar charts as well!

**Comment by shabbir-ahmed** [comment]
With big data > 500 rows


![screenshot-127 0 0 1 3000-2016-12-06-14-38-39](https://cloud.githubusercontent.com/assets/9017121/20918538/d252b3ee-bbc1-11e6-9823-f7561a8b0174.png)

**Comment by echan00** [comment]
Same here, I'd love this feature

**Comment by solson** [comment]
I've needed this, too, especially for stacked bar/column charts where not even the tooltips give you the total.

**Comment by murilolopes** [comment]
Hi, this feature was released?

**Comment by erickveras** [comment]
I need this feature using chartjs library with column_chart. Is there any solution using this api ?

**Comment by ankane** [comment]
It looks like Chart.js now has an official plugin for this, which you can use with Chartkick: https://github.com/chartjs/chartjs-plugin-datalabels

As for Google Charts, I don't think this is going to happen as it's likely a bigger change and not something I think I can support in the long run. I'm sure this isn't the outcome everyone in this thread wanted, but I appreciate all of the feedback.
