### ISSUE TITLE
How to fire a jquery event on chart load?

### ISSUE THREAD

**Issue by mgraulich** [ankane/chartkick#82]
I've been stuck on this for a while... I'm trying to fire a jquery event when the piechart loads in order to prepend a $ sign to the chart slice text but can seem to figure out which event to listen for.

**Comment by adampash** [comment]
Any update on this? I was also hoping to attach some logic to the chart's load event.

**Comment by itkin** [comment]
+1

**Comment by ankane** [comment]
Just fyi, no plans to add chart load events at the moment.
