### ISSUE TITLE
using content_for

### ISSUE THREAD

**Issue by marine44** [ankane/chartkick#85]
Excellent plugin!!! Having an issue using content_for...

My Layout

``` html
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= yield :charts_js %>
  </head>
  <body>
  <%= yield %>

  <%= javascript_include_tag 'application' %>
 </body>
</html>
```

Then my view

``` html
<%= line_chart ({"Football" => 10, "Basketball" => 5}), content_for: :charts_js %>
```

Gives me the error: Uncaught ReferenceError: Chartkick is not defined

How is content_for meant to be used?

**Comment by wuliwong** [comment]
I am receiving the same error. What was the solution for this issue? @ryanharnwell

**Comment by sharp** [comment]
Same issue,  I do not plan to waste time on this gem ：） 100+ open / 100+ closed

**Comment by ankane** [comment]
Hey @sharp, that's your choice, but please have some empathy for open source contributors before you comment in the future - on both this and other open source projects.

**Comment by ACPK** [comment]
@ankane Is this still an issue as I'm facing it?

**Comment by VicoErv** [comment]
year passed, and i m facing this problem

**Comment by VicoErv** [comment]
i can't use highcharts too

**Comment by VicoErv** [comment]
```
<%= timeline @js_array, adapter: "Highcharts" %>
```

```
//= require rails-ujs
//= require turbolinks
//= require jquery
//= require highcharts
//= require chartkick
//= require_tree .
```

**Comment by ankane** [comment]
Hey @VicoErv, the timeline chart only works with Google Charts (as mentioned in the readme). Also, content_for has worked consistently for years, so it's likely an issue with your app. I'd try following the readme instructions exactly.

**Comment by VicoErv** [comment]
thanks for your reply, my issue just for timeline, i think i can use another adapter. the rest is good and work as it is.
