### ISSUE TITLE
Options to speed up geochart

### ISSUE THREAD

**Issue by theonegri** [ankane/chartkick#86]
Geochart is really slow when displaying a lot of markers.
In my case I have 6101 markers to display all over the USA.

There is an undocumented way make things faster, that would be awesome.

http://savedbythegoog.appspot.com/?id=22d60bcbfa4ebc0f79cdc697daa208b15e4e07ba

**Comment by itkin** [comment]
+1

**Comment by ankane** [comment]
Closing this out since it's been idle for a while and no longer plan to track enhancements in the issue tracker. Hope you're doing well @theonegri and @itkin
