### ISSUE TITLE
Adding a second y-axis to a chart

### ISSUE THREAD

**Issue by coreyleveen** [ankane/chartkick#90]
Hi Andrew,

I'm trying to add a second y-axis to my chart so that my other line will scale properly. 

Is this possible? 

Thanks very much for your help!

-Corey

**Comment by aromatt** [comment]
+1

**Comment by hal-henningsmoen** [comment]
I am adding a second Y-Axis to line charts and it works fine using google charts.  Pass your axis specifications and series specifications through the :library param.  
eg:
line_chart foo_data, library: { vAxes: { 0 => {logScale: false, maxValue: 100 }, 1 => {logScale: false, maxValue: 100, format:"#'%'" } }, series: { 0 =>  {targetAxisIndex: 0 }, 1 => {targetAxisIndex: 0 }, 1 => {targetAxisIndex: 1}  }}
Will plot three curves: the first two against a standard numeric y axis and the third on a  y axis with the correct range for percentages.

**Comment by Aeramor** [comment]
I was able to do this with just adding, which correctly assigned to correct min/max etc.
```ruby
line_chart chartkick_json_admin_outreach_messages_path, library: { vAxes: { 0 => {logScale: false}, 1 => {logScale: false} }, series: { 0 => {targetAxisIndex: 1 }, 1 => {targetAxisIndex: 0 }, 1 => {targetAxisIndex: 0}, 2 => {targetAxisIndex: 0} }}
```

**Comment by hal-henningsmoen** [comment]
Min/Max value is set automatically based on min/max values of the data.   Explicitly setting max value is only necessary if you want a specific range (eg a percent scale should range between 0 and 100.)

**Comment by Aeramor** [comment]
Sorry, I meant that I'm able to do this with the default chart library (Highcharts) without any changes.
If it wasn't supported before it seems to be now.

**Comment by SathishSampath** [comment]
I am using Chartkick with Highchart. I tried Aeramor's Answer. But its not working.
My code is 
<%= line_chart testchart_path, library: { vAxes: { 0 => {logScale: false}, 1 => {logScale: false} }, series: { 0 => {targetAxisIndex: 1 }, 1 => {targetAxisIndex: 0 }}} %>

The testchart_path returns json of two time varying series with same X axis values. 
My doubts is should I give the name of series in the above code, in the series part?   I am not getting the Chart with two Y axis. Only standard MultiSeries Chart with single Y axis is displayed
