### ISSUE TITLE
Stacked column chart data format not obvious

### ISSUE THREAD

**Issue by datwright** [ankane/chartkick#92]
How do you actually need to format `data` to generate a stacked column chart?

``` erb
<%= column_chart data, stacked: true %>
```

This is the hash structure you get when you do something like `Task.group(:x).group(:animal).count`:

``` ruby
{[x1, "dog"] => 1, [x1, "pig"] => 4, [x2, "dog"] => 3, [x2, "pig"] => 5}
```

I was hoping that would just work, but no such luck.

Also tried using Google's structure but that didn't work either
https://developers.google.com/chart/interactive/docs/gallery/columnchart#StackedColumns

**Comment by guyisra** [comment]
Can you please give an example of how the data needs to be constructed? I can't seem to create a stacked chart..

**Comment by san** [comment]
I still can't figure out how to format data for stacked chart. Can someone give an example please?

Thanks.
