### ISSUE TITLE
Tremendously slow loading because 'http:' is missing

### ISSUE THREAD

**Issue by rjbruin** [ankane/chartkick#98]
Chartkick was making my project incredibly slow because the installation instructions said to include the Google JS API using the link '//www.google.com/jsapi'. It turns out that adding 'http:' to that link solves this problem. I found this solution on [StackOverflow](https://stackoverflow.com/questions/20693935/rails-chartkick-google-charts-load-times-extremely-long/20710813#20710813).

I would suggest you change the installation instructions to use the 'http:' prefix to ensure no other users suffer from this issue.

**Comment by ankane** [comment]
Cleaning up issues. The instructions now say to use `https` for everything.
